const chapter15 = {
    number: 15,
    title: 'The Supreme Person',
    total_verses: 20,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 6,
            estimated_minutes: 4,
            verses: [
                { verse_number: 1, sanskrit: 'श्रीभगवानुवाच। ऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम्। छन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित्।।', transliteration: 'shri bhagavan uvacha: urdhva-mulam adhah-shakham ashvattham prahur avyayam', explanations: { en: 'Krishna describes the eternal ashvattha (pipal) tree with roots above and branches below; its leaves are the Vedas — one who knows it is the knower of the Vedas.', hi: 'कृष्ण अविनाशी अश्वत्थ (पीपल) वृक्ष का वर्णन करते हैं जिसकी जड़ें ऊपर और शाखाएँ नीचे हैं; इसके पत्ते वेद हैं - जो इसे जानता है, वही सच में वेदों का ज्ञाता है।' } },
                { verse_number: 2, sanskrit: 'अधश्चोर्ध्वं प्रसृतास्तस्य शाखा गुणप्रवृद्धा विषयप्रवालाः। अधश्च मूलान्यनुसन्ततानि कर्मानुबन्धीनि मनुष्यलोके।।', transliteration: 'adhash chordhvam prasritas tasya shakha guna-pravridhha vishaya-pravalah', explanations: { en: 'Its branches spread below and above, nourished by the qualities; its shoots are the sense objects; its roots spread downward, creating the bonds of action in the human world.', hi: 'इसकी शाखाएँ नीचे और ऊपर दोनों ओर फैली हैं, प्रकृति के गुणों से पोषित होकर; इसकी कोंपलें इंद्रिय-विषय हैं; इसकी जड़ें नीचे मनुष्यलोक में फैलकर कर्मों के बंधन बनाती हैं।' } },
                { verse_number: 3, sanskrit: 'न रूपमस्येह तथोपलभ्यते नान्तो न चादिर्न च सम्प्रतिष्ठा। अश्वत्थमेनं सुविरूढमूलमसङ्गशस्त्रेण दृढेन छित्त्वा।।', transliteration: 'na rupam asyeha tathopalabhyate nanto na chadirna cha sampratishtha', explanations: { en: 'Its form cannot be perceived here, nor its end, beginning, or foundation — cutting down this deeply rooted ashvattha tree with the strong sword of non-attachment...', hi: 'इसका असली स्वरूप यहाँ नहीं दिखाई देता, न इसका अंत पता चलता है, न आदि, न इसका आधार - इस गहरी जड़ों वाले अश्वत्थ वृक्ष को अनासक्ति के दृढ़ हथियार से काटकर...' } },
                { verse_number: 4, sanskrit: 'ततः पदं तत्परिमार्गितव्यं यस्मिन्गता न निवर्तन्ति भूयः। तमेव चाद्यं पुरुषं प्रपद्ये यतः प्रवृत्तिः प्रसृता पुराणी।।', transliteration: 'tatah padam tat parimargitavyam yasmin gata na nivartanti bhuyah', explanations: { en: '...then one should seek that goal from which, having gone, beings return no more — taking refuge in that primal Person from whom the ancient current of creation flowed.', hi: '...फिर उस परम लक्ष्य की खोज करनी चाहिए जहाँ पहुँचकर प्राणी फिर कभी नहीं लौटते - उस आदि पुरुष की शरण में जाना चाहिए जिससे यह प्राचीन सृष्टि-प्रवाह उत्पन्न हुआ है।' } },
                { verse_number: 5, sanskrit: 'निर्मानमोहा जितसङ्गदोषा अध्यात्मनित्या विनिवृत्तकामाः। द्वन्द्वैर्विमुक्ताः सुखदुःखसंज्ञैर्गच्छन्त्यमूढाः पदमव्ययम्।।', transliteration: 'nirmana-moha jita-sanga-dosha adhyatma-nitya vinivrittakamah', explanations: { en: 'Free from pride and delusion, having overcome the fault of attachment, ever dwelling in the self, with desires turned away, freed from the pairs of opposites such as pleasure and pain — the undeluded reach that imperishable state.', hi: 'अभिमान और मोह से मुक्त, आसक्ति के दोष पर विजय पाए हुए, सदा आत्मा में स्थित, इच्छाओं से विमुख, सुख-दुःख जैसे द्वंद्वों से मुक्त - ऐसे अमोहित लोग ही उस अविनाशी पद को प्राप्त करते हैं।' } },
                { verse_number: 6, sanskrit: 'न तद्भासयते सूर्यो न शशाङ्को न पावकः। यद्गत्वा न निवर्तन्ते तद्धाम परमं मम।।', transliteration: 'na tad bhasayate suryo na shashankona pavakah', explanations: { en: 'That place is not illumined by the sun, moon, or fire — going there, beings do not return — that is his supreme abode.', hi: 'उस स्थान को न सूर्य प्रकाशित करता है, न चंद्रमा, न अग्नि - वहाँ पहुँचकर प्राणी फिर नहीं लौटते - वही उसका परम धाम है।' } },
            ],
            questions: [{ question_text: 'The inverted tree — roots above, branches below — is a striking image. What does it suggest about the relationship between source and manifestation?', options: [{ text: 'That nature violates physical laws', is_correct: false }, { text: 'That the visible world hangs from an invisible source, like branches from a root we cannot see — reminding us that what is most real and foundational is not what is most visible, and that all manifest experience derives from something beyond it', is_correct: true }, { text: 'That we should meditate standing on our heads', is_correct: false }], explanation: 'The inverted tree is an ancient Vedic image: the source is "above" — not spatially but in terms of ontological priority. Manifestation hangs from it like branches from a root. Cutting the tree with the sword of non-attachment means releasing identification with the branches and finding the root — returning to source.', difficulty: 'application', hi: { question_text: 'उल्टा वृक्ष - जड़ें ऊपर, शाखाएं नीचे - एक चौंकाने वाली छवि है। यह स्रोत और अभिव्यक्ति के बीच के संबंध के बारे में क्या सुझाती है?', options: [{ text: 'कि प्रकृति भौतिक नियमों का उल्लंघन करती है', is_correct: false }, { text: 'कि दृश्य संसार एक अदृश्य स्रोत से लटका है, जैसे शाखाएं उस जड़ से जिसे हम नहीं देख सकते - यह हमें याद दिलाता है कि जो सबसे वास्तविक और मूलभूत है वह सबसे दृश्यमान नहीं है, और सारा प्रकट अनुभव उससे परे किसी चीज़ से उपजता है', is_correct: true }, { text: 'कि हमें सिर के बल खड़े होकर ध्यान करना चाहिए', is_correct: false }], explanation: 'उल्टा वृक्ष एक प्राचीन वैदिक छवि है: स्रोत "ऊपर" है - स्थानिक रूप से नहीं बल्कि तात्विक प्राथमिकता के अर्थ में। अभिव्यक्ति उससे वैसे ही लटकती है जैसे जड़ से शाखाएं। अनासक्ति की तलवार से वृक्ष को काटने का मतलब है शाखाओं के साथ पहचान छोड़ना और जड़ को खोजना - स्रोत की ओर लौटना।' } }],
        },
        {
            part_number: 2,
            verse_start: 7,
            verse_end: 11,
            estimated_minutes: 4,
            verses: [
                { verse_number: 7, sanskrit: 'ममैवांशो जीवलोके जीवभूतः सनातनः। मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति।।', transliteration: 'mamaivamsho jiva-loke jiva-bhutah sanatanah', explanations: { en: 'An eternal fragment of himself — the living self in the world — draws to itself the six senses including mind, which rest in Prakriti.', hi: 'उसी का एक सनातन अंश इस जीवलोक में जीव बनकर, मन सहित छह इंद्रियों को, जो प्रकृति में स्थित हैं, अपनी ओर खींचता है।' } },
                { verse_number: 8, sanskrit: 'शरीरं यदवाप्नोति यच्चाप्युत्क्रामतीश्वरः। गृहीत्वैतानि संयाति वायुर्गन्धानिवाशयात्।।', transliteration: 'shariram yad avapnoti yach chapy utkramati ishvarah', explanations: { en: 'When the master (the soul) takes on a body and when it departs, it takes these senses along, as the wind takes fragrances from their place.', hi: 'जब स्वामी (आत्मा) शरीर धारण करता है और जब वह उसे छोड़ता है, तब वह इन इंद्रियों को साथ ले जाता है, जैसे वायु सुगंध को उसके स्रोत से अपने साथ ले जाती है।' } },
                { verse_number: 9, sanskrit: 'श्रोत्रं चक्षुः स्पर्शनं च रसनं घ्राणमेव च। अधिष्ठाय मनश्चायं विषयानुपसेवते।।', transliteration: 'shrotram chakshuh sparshanam cha rasanam ghranam eva cha', explanations: { en: 'Presiding over the ear, eye, touch, taste, smell, and mind — this one experiences the objects of the senses.', hi: 'कान, आँख, स्पर्श, रस और गंध की इंद्रियों के साथ-साथ मन पर अधिष्ठित होकर, यह आत्मा विषयों का भोग करता है।' } },
                { verse_number: 10, sanskrit: 'उत्क्रामन्तं स्थितं वापि भुञ्जानं वा गुणान्वितम्। विमूढा नानुपश्यन्ति पश्यन्ति ज्ञानचक्षुषः।।', transliteration: 'utkramantam sthitam vapi bhunjanam va gunanvitam', explanations: { en: 'The deluded do not see the one departing, dwelling, or experiencing endowed with qualities — but those with the eye of knowledge see.', hi: 'मोहित लोग शरीर छोड़ते, रहते या गुणों सहित भोग करते हुए इस आत्मा को नहीं देख पाते - परंतु जिनके पास ज्ञान की आँख है, वे इसे देख लेते हैं।' } },
                { verse_number: 11, sanskrit: 'यतन्तो योगिनश्चैनं पश्यन्त्यात्मन्यवस्थितम्। यतन्तोऽप्यकृतात्मानो नैनं पश्यन्त्यचेतसः।।', transliteration: 'yatanto yoginash chainam pashyanty atmany avasthitam', explanations: { en: 'Striving yogis see him established in the self; the striving but unrefined, mindless ones do not see him.', hi: 'प्रयत्नशील योगी उसे अपनी आत्मा में स्थित देख पाते हैं; परंतु प्रयत्न करने पर भी जिनका मन अपरिष्कृत और असावधान है, वे उसे नहीं देख पाते।' } },
            ],
            questions: [{ question_text: 'Krishna says the individual self is "an eternal fragment of myself." What does this imply about the relationship between individual and universal consciousness?', options: [{ text: 'That individuals are completely separate from God', is_correct: false }, { text: 'That individual awareness is not alien to the universal — it is a particularization of it, the way a wave is a particularization of the ocean, not separate from it but not identical to it in form', is_correct: true }, { text: 'That the individual self will eventually be destroyed', is_correct: false }], explanation: 'Fragment here doesn\'t mean a broken-off piece — it means a living expression of the whole. The individual self (jiva) participates in the universal (Brahman) the way a flame participates in fire. This implies that self-knowledge and knowledge of the divine are ultimately the same inquiry.', difficulty: 'application', hi: { question_text: 'कृष्ण कहते हैं कि व्यक्तिगत आत्मा "स्वयं का एक सनातन अंश" है। यह व्यक्तिगत और सार्वभौमिक चेतना के बीच के संबंध के बारे में क्या दर्शाता है?', options: [{ text: 'कि व्यक्ति ईश्वर से पूरी तरह अलग हैं', is_correct: false }, { text: 'कि व्यक्तिगत जागरूकता सार्वभौमिक से अलग नहीं है - यह उसकी एक विशिष्टता है, ठीक जैसे लहर समुद्र की एक विशिष्टता है, उससे अलग नहीं पर रूप में उसके समान भी नहीं', is_correct: true }, { text: 'कि व्यक्तिगत आत्मा अंततः नष्ट हो जाएगी', is_correct: false }], explanation: 'यहां अंश का मतलब टूटा हुआ टुकड़ा नहीं है - इसका मतलब है समग्र की एक जीवंत अभिव्यक्ति। व्यक्तिगत आत्मा (जीव) सार्वभौमिक (ब्रह्म) में वैसे ही भाग लेती है जैसे एक लौ अग्नि में भाग लेती है। इसका तात्पर्य है कि आत्म-ज्ञान और ईश्वर का ज्ञान अंततः एक ही खोज हैं।' } }],
        },
        {
            part_number: 3,
            verse_start: 12,
            verse_end: 20,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 12, sanskrit: 'यदादित्यगतं तेजो जगद्भासयतेऽखिलम्। यच्चन्द्रमसि यच्चाग्नौ तत्तेजो विद्धि मामकम्।।', transliteration: 'yad aditya-gatam tejo jagad bhasayate\'khilam', explanations: { en: 'The light in the sun that illumines the entire world, the light in the moon, the light in fire — know that light to be his.', hi: 'सूर्य में जो तेज है जो समस्त संसार को प्रकाशित करता है, चंद्रमा में जो तेज है, अग्नि में जो तेज है - उस तेज को उसी का जानो।' } },
                { verse_number: 13, sanskrit: 'गामाविश्य च भूतानि धारयाम्यहमोजसा। पुष्णामि चौषधीः सर्वाः सोमो भूत्वा रसात्मकः।।', transliteration: 'gam avishya cha bhutani dharayamy aham ojasa', explanations: { en: 'And entering the earth he supports all beings with his energy; and nourishing all the herbs, he becomes the moon of liquid essence.', hi: 'और पृथ्वी में प्रवेश करके वह अपने ओज से सभी प्राणियों को धारण करता है; और सभी औषधियों को पोषित करता हुआ वह रसमय चंद्रमा बन जाता है।' } },
                { verse_number: 14, sanskrit: 'अहं वैश्वानरो भूत्वा प्राणिनां देहमाश्रितः। प्राणापानसमायुक्तः पचाम्यन्नं चतुर्विधम्।।', transliteration: 'aham vaishvanaro bhutva praninam deham ashritah', explanations: { en: 'Becoming the digestive fire in the bodies of living beings, joined with the incoming and outgoing breaths, he digests the four kinds of food.', hi: 'प्राणियों के शरीर में जठराग्नि (वैश्वानर) बनकर, प्राण और अपान वायु से युक्त होकर, वह चार प्रकार के अन्न को पचाता है।' } },
                { verse_number: 15, sanskrit: 'सर्वस्य चाहं हृदि सन्निविष्टो मत्तः स्मृतिर्ज्ञानमपोहनं च। वेदैश्च सर्वैरहमेव वेद्यो वेदान्तकृद्वेदविदेव चाहम्।।', transliteration: 'sarvasya chaham hridi sannivishto mattah smritir jnanam apohanam cha', explanations: { en: 'He is seated in the hearts of all; from him come memory, knowledge, and removal of doubt. He alone is to be known by all the Vedas; he is the maker of the Vedanta and the knower of the Vedas.', hi: 'वह सभी के हृदय में विराजमान है; उसी से स्मृति, ज्ञान और संशय का निवारण होता है। वही समस्त वेदों द्वारा जानने योग्य है; वही वेदांत का रचयिता और वेदों का ज्ञाता है।' } },
                { verse_number: 16, sanskrit: 'द्वाविमौ पुरुषौ लोके क्षरश्चाक्षर एव च। क्षरः सर्वाणि भूतानि कूटस्थोऽक्षर उच्यते।।', transliteration: 'dvav imau purushau loke ksharas chakshara eva cha', explanations: { en: 'There are two Persons in the world: the perishable and the imperishable. All beings are the perishable; the one standing at the summit is called the imperishable.', hi: 'इस संसार में दो पुरुष हैं: क्षर (नाशवान) और अक्षर (अविनाशी)। सभी प्राणी क्षर हैं; जो शिखर पर अडिग खड़ा है, उसे अक्षर कहा जाता है।' } },
                { verse_number: 17, sanskrit: 'उत्तमः पुरुषस्त्वन्यः परमात्मेत्युदाहृतः। यो लोकत्रयमाविश्य बिभर्त्यव्यय ईश्वरः।।', transliteration: 'uttamah purushhas tv anyah paramatmety udahritah', explanations: { en: 'But the supreme Person is another — called the Paramatman — who enters and sustains the three worlds, the imperishable Lord.', hi: 'परंतु परम पुरुष तो इनसे भी भिन्न है - उसे परमात्मा कहा जाता है, जो तीनों लोकों में प्रवेश करके उन्हें धारण करता है, वह अविनाशी ईश्वर है।' } },
                { verse_number: 18, sanskrit: 'यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः। अतोऽस्मि लोके वेदे च प्रथितः पुरुषोत्तमः।।', transliteration: 'yasmat ksharatito\'ham aksharadin api cottamah', explanations: { en: 'Because he transcends the perishable and is higher even than the imperishable — therefore in the world and in the Vedas he is known as the supreme Person (Purushottama).', hi: 'क्योंकि वह क्षर से परे है और अक्षर से भी श्रेष्ठ है - इसीलिए संसार में और वेदों में वह पुरुषोत्तम के नाम से विख्यात है।' } },
                { verse_number: 19, sanskrit: 'यो मामेवमसम्मूढो जानाति पुरुषोत्तमम्। स सर्वविद्भजति मां सर्वभावेन भारत।।', transliteration: 'yo mam evam asammudho janati purushottamam', explanations: { en: 'One who knows him thus, undeluded, as the supreme Person — knowing all, they worship him with their whole being, Arjuna.', hi: 'जो कोई उसे इस प्रकार, अमोहित होकर, पुरुषोत्तम के रूप में जानता है, वह सब कुछ जानते हुए अपने पूरे अस्तित्व से उसकी उपासना करता है, अर्जुन।' } },
                { verse_number: 20, sanskrit: 'इति गुह्यतमं शास्त्रमिदमुक्तं मयानघ। एतद्बुद्ध्वा बुद्धिमान्स्यात्कृतकृत्यश्च भारत।।', transliteration: 'iti guhyatamam shastram idam uktam maya\'nagha', explanations: { en: 'Thus this most secret scripture has been declared by him, O sinless one. Understanding this, one becomes wise and has accomplished all there is to accomplish, Arjuna.', hi: 'इस प्रकार यह अत्यंत गोपनीय शास्त्र उनके द्वारा कहा गया है, हे निष्पाप। इसे समझकर मनुष्य बुद्धिमान बन जाता है और उसका जीवन-कर्तव्य पूर्ण हो जाता है, अर्जुन।' } },
            ],
            questions: [{ question_text: 'Krishna says he is the light in the sun, the fire in digestion, the memory in the mind. What changes when you habitually recognize the divine in ordinary, natural processes rather than only in special religious moments?', options: [{ text: 'You stop doing ordinary activities and only meditate', is_correct: false }, { text: 'Ordinary life becomes suffused with an awareness of the sacred — sunlight, warmth, digestion, memory are no longer neutral background facts but expressions of the same presence you might seek in prayer; the sacred is everywhere or nowhere', is_correct: true }, { text: 'You become superstitious about natural phenomena', is_correct: false }], explanation: 'This is one of the Gita\'s most radical teachings: the divine is not reserved for ritual, prayer, or special practice. It is the actual light you see by, the actual energy that processes your food. Recognizing this doesn\'t diminish devotion — it expands its territory to include all of life.', difficulty: 'application', hi: { question_text: 'कृष्ण कहते हैं कि वे सूर्य में प्रकाश हैं, पाचन में अग्नि हैं, मन में स्मृति हैं। जब आप आदतन विशेष धार्मिक क्षणों के बजाय सामान्य, प्राकृतिक प्रक्रियाओं में ईश्वर को पहचानते हैं, तो क्या बदलता है?', options: [{ text: 'आप सामान्य गतिविधियां करना बंद कर देते हैं और केवल ध्यान करते हैं', is_correct: false }, { text: 'सामान्य जीवन पवित्रता की जागरूकता से भर जाता है - धूप, गर्मी, पाचन, स्मृति अब तटस्थ पृष्ठभूमि तथ्य नहीं रहते बल्कि उसी उपस्थिति की अभिव्यक्तियां बन जाते हैं जिसे आप प्रार्थना में खोज सकते हैं; पवित्रता या तो हर जगह है या कहीं नहीं', is_correct: true }, { text: 'आप प्राकृतिक घटनाओं के बारे में अंधविश्वासी बन जाते हैं', is_correct: false }], explanation: 'यह गीता की सबसे क्रांतिकारी शिक्षाओं में से एक है: ईश्वर कर्मकांड, प्रार्थना या विशेष साधना के लिए आरक्षित नहीं है। यह वह वास्तविक प्रकाश है जिससे आप देखते हैं, वह वास्तविक ऊर्जा है जो आपके भोजन को पचाती है। इसे पहचानना भक्ति को कम नहीं करता - यह उसके क्षेत्र को पूरे जीवन तक फैला देता है।' } }],
        },
    ],
};

module.exports = chapter15;
