const chapter12 = {
    number: 12,
    title: 'The Yoga of Devotion',
    total_verses: 20,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 7,
            estimated_minutes: 4,
            verses: [
                { verse_number: 1, sanskrit: 'अर्जुन उवाच। एवं सततयुक्ता ये भक्तास्त्वां पर्युपासते। ये चाप्यक्षरमव्यक्तं तेषां के योगवित्तमाः।।', transliteration: 'arjuna uvacha: evam satata-yukta ye bhaktas tvam paryupasate', explanations: { en: 'Arjuna asks: those who are constantly devoted to Krishna and worship him with love, and those who worship the imperishable unmanifest — which of these knows yoga best?', hi: 'अर्जुन पूछते हैं — जो भक्त निरंतर प्रेमपूर्वक कृष्ण की उपासना करते हैं, और जो अविनाशी निराकार तत्व की उपासना करते हैं — इनमें से योग को सबसे अच्छी तरह कौन जानता है?' } },
                { verse_number: 2, sanskrit: 'श्रीभगवानुवाच। मय्यावेश्य मनो ये मां नित्ययुक्ता उपासते। श्रद्धया परयोपेतास्ते मे युक्ततमा मताः।।', transliteration: 'shri bhagavan uvacha: mayy aveshya mano ye mam nitya-yukta upasate', explanations: { en: 'Krishna says: those who fix their minds on him and worship him with constant devotion and supreme faith — these he considers the most perfected in yoga.', hi: 'कृष्ण कहते हैं — जो लोग अपना मन मुझमें लगाकर, निरंतर भक्ति और परम श्रद्धा के साथ मेरी उपासना करते हैं, उन्हें मैं योग में सबसे सिद्ध मानता हूँ।' } },
                { verse_number: 3, sanskrit: 'ये त्वक्षरमनिर्देश्यमव्यक्तं पर्युपासते। सर्वत्रगमचिन्त्यं च कूटस्थमचलं ध्रुवम्।।', transliteration: 'ye tv aksharam anirdeshyam avyaktam paryupasate', explanations: { en: 'But those who worship the imperishable, indefinable, unmanifest — all-pervading, unthinkable, unchanging, immovable, eternal...', hi: 'परंतु जो अविनाशी, अनिर्वचनीय, अव्यक्त — सर्वव्यापी, अचिन्त्य, अपरिवर्तनशील, स्थिर और नित्य तत्व की उपासना करते हैं...' } },
                { verse_number: 4, sanskrit: 'सन्नियम्येन्द्रियग्रामं सर्वत्र समबुद्धयः। ते प्राप्नुवन्ति मामेव सर्वभूतहिते रताः।।', transliteration: 'sanniyamyendriya-gramam sarvatra sama-buddhayah', explanations: { en: '...restraining all the senses, equal-minded everywhere, delighting in the welfare of all beings — they also reach him.', hi: '...अपनी सभी इंद्रियों को वश में रखकर, सर्वत्र समान बुद्धि रखते हुए, सभी प्राणियों के कल्याण में रत रहकर — वे भी कृष्ण को ही प्राप्त करते हैं।' } },
                { verse_number: 5, sanskrit: 'क्लेशोऽधिकतरस्तेषामव्यक्तासक्तचेतसाम्। अव्यक्ता हि गतिर्दुःखं देहवद्भिरवाप्यते।।', transliteration: 'klesho\'dhikataras tesham avyaktasakta-chetasam', explanations: { en: 'But the effort is greater for those whose minds are attached to the unmanifest — for the unmanifest path is difficult for embodied beings to reach.', hi: 'परंतु जिनका मन अव्यक्त में आसक्त है, उनके लिए प्रयास अधिक कठिन होता है — क्योंकि देहधारियों के लिए अव्यक्त का मार्ग पाना दुष्कर है।' } },
                { verse_number: 6, sanskrit: 'ये तु सर्वाणि कर्माणि मयि संन्यस्य मत्पराः। अनन्येनैव योगेन मां ध्यायन्त उपासते।।', transliteration: 'ye tu sarvani karmani mayi sannyasya mat-parah', explanations: { en: 'But those who dedicate all their actions to him, taking him as the supreme goal, meditating on him with exclusive devotion and worshipping him...', hi: 'परंतु जो अपने सभी कर्म कृष्ण को अर्पित करके, उन्हें ही परम लक्ष्य मानकर, अनन्य भक्ति से उनका ध्यान करते हुए उनकी उपासना करते हैं...' } },
                { verse_number: 7, sanskrit: 'तेषामहं समुद्धर्ता मृत्युसंसारसागरात्। भवामि नचिरात्पार्थ मय्यावेशितचेतसाम्।।', transliteration: 'tesham aham samuddharta mrityu-samsara-sagarat', explanations: { en: '...for those whose minds are fixed on him — he becomes quickly their deliverer from the ocean of death and rebirth, O Arjuna.', hi: '...जिनका मन कृष्ण में स्थिर है, उन्हें वे शीघ्र ही मृत्यु और संसार के सागर से पार लगा देते हैं, हे अर्जुन।' } },
            ],
            questions: [{ question_text: 'Krishna says the path via the formless/unmanifest is harder for embodied beings. Why might abstract, formless worship be more difficult than devotion to a personal form?', options: [{ text: 'Because the formless path requires more ritual', is_correct: false }, { text: 'Because the human mind and heart are shaped by embodied experience — they naturally reach for something they can relate to, love, and direct their attention toward; formless meditation offers no anchor for the heart\'s natural tendency to move toward what it loves', is_correct: true }, { text: 'Because the formless path leads to a lesser destination', is_correct: false }], explanation: 'This isn\'t a dismissal of the formless path — it is equally valid. Krishna is being pragmatic: the human organism runs on relationship and love. Giving the heart something it can move toward — a presence, a face, a name — uses the heart\'s natural capacity rather than working against it.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 8,
            verse_end: 12,
            estimated_minutes: 4,
            verses: [
                { verse_number: 8, sanskrit: 'मय्येव मन आधत्स्व मयि बुद्धिं निवेशय। निवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः।।', transliteration: 'mayy eva mana adhatsva mayi buddhim niveshaya', explanations: { en: 'Fix your mind on Krishna alone, let your intellect enter into him — you will dwell in him alone hereafter, without doubt.', hi: 'अपने मन को कृष्ण में ही स्थिर करो, अपनी बुद्धि को उन्हीं में लगाओ — इसके बाद तुम निःसंदेह उन्हीं में निवास करोगे।' } },
                { verse_number: 9, sanskrit: 'अथ चित्तं समाधातुं न शक्नोषि मयि स्थिरम्। अभ्यासयोगेन ततो मामिच्छाप्तुं धनञ्जय।।', transliteration: 'atha chittam samadhatum na shaknoshi mayi sthiram', explanations: { en: 'If you cannot steadily fix your mind on him, then seek to reach him by the practice of yoga, Arjuna.', hi: 'यदि तुम अपने मन को कृष्ण में स्थिर नहीं रख पाते, तो अभ्यास योग के माध्यम से उन्हें पाने का प्रयास करो, हे अर्जुन।' } },
                { verse_number: 10, sanskrit: 'अभ्यासेऽप्यसमर्थोऽसि मत्कर्मपरमो भव। मदर्थमपि कर्माणि कुर्वन्सिद्धिमवाप्स्यसि।।', transliteration: 'abhyase\'py asamartho\'si mat-karma-paramo bhava', explanations: { en: 'If you are unable even to practice, be devoted to actions for his sake — even doing actions for his sake, you will attain perfection.', hi: 'यदि अभ्यास करने में भी असमर्थ हो, तो कृष्ण के कार्यों में लगन से जुट जाओ — उनके लिए कर्म करते हुए भी तुम सिद्धि प्राप्त कर लोगे।' } },
                { verse_number: 11, sanskrit: 'अथैतदप्यशक्तोऽसि कर्तुं मद्योगमाश्रितः। सर्वकर्मफलत्यागं ततः कुरु यतात्मवान्।।', transliteration: 'athaita\'dapy ashakto\'si kartum mad-yogam ashritah', explanations: { en: 'If even this you cannot do, then taking refuge in his yoga, with self-controlled mind, renounce the fruits of all actions.', hi: 'यदि यह भी न कर सको, तो कृष्ण की शरण लेकर, संयमित मन से, सभी कर्मों के फल का त्याग करो।' } },
                { verse_number: 12, sanskrit: 'श्रेयो हि ज्ञानमभ्यासाज्ज्ञानाद्ध्यानं विशिष्यते। ध्यानात्कर्मफलत्यागस्त्यागाच्छान्तिरनन्तरम्।।', transliteration: 'shreyo hi jnanam abhyasaj jnanad dhyanam vishishyate', explanations: { en: 'Knowledge is better than practice; meditation is better than knowledge; renunciation of the fruits of action is better than meditation — from renunciation, peace follows immediately.', hi: 'अभ्यास से ज्ञान श्रेष्ठ है; ज्ञान से ध्यान श्रेष्ठ है; और कर्मफल के त्याग से ध्यान भी श्रेष्ठ है — क्योंकि त्याग से तुरंत शांति प्राप्त होती है।' } },
            ],
            questions: [{ question_text: 'Krishna gives four progressive levels of practice for those who struggle: fix the mind on him → practice → act for him → renounce fruits. What does this graduated teaching reveal about how Krishna understands human spiritual capacity?', options: [{ text: 'That most people are too weak to practice real spirituality', is_correct: false }, { text: 'That the path is wide enough for every level of capacity — there is always an accessible entry point, and each level is genuinely valid, not merely a consolation prize', is_correct: true }, { text: 'That only fruit-renunciation matters and the rest is inferior', is_correct: false }], explanation: 'This staircase of practices is one of the most compassionate passages in the Gita. Krishna doesn\'t insist on the highest practice and dismiss those who can\'t manage it. He meets practitioners wherever they are and offers them a genuine path forward from exactly that point.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 13,
            verse_end: 20,
            estimated_minutes: 5,
            verses: [
                { verse_number: 13, sanskrit: 'अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च। निर्ममो निरहङ्कारः समदुःखसुखः क्षमी।।', transliteration: 'adveshtaa sarva-bhutanam maitrah karuna eva cha', explanations: { en: 'One who hates no being, who is friendly and compassionate to all, who has no sense of "mine," no ego, who is equal in pain and pleasure, patient...', hi: 'जो किसी से द्वेष नहीं रखता, जो सभी प्राणियों के प्रति मैत्रीपूर्ण और करुणामय है, जिसमें "मेरेपन" और अहंकार का भाव नहीं है, जो सुख-दुख में समान है, क्षमाशील है...' } },
                { verse_number: 14, sanskrit: 'सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः। मय्यर्पितमनोबुद्धिर्यो मद्भक्तः स मे प्रियः।।', transliteration: 'santushttah satatam yogi yatatma dridha-nishchayah', explanations: { en: '...always content, meditative, self-controlled, of firm resolve, with mind and intellect dedicated to him — such a devotee of his is dear to him.', hi: '...सदा संतुष्ट, ध्यानशील, आत्मसंयमी, दृढ़ निश्चयी, जिसका मन और बुद्धि कृष्ण को समर्पित है — ऐसा भक्त उन्हें प्रिय है।' } },
                { verse_number: 15, sanskrit: 'यस्मान्नोद्विजते लोको लोकान्नोद्विजते च यः। हर्षामर्षभयोद्वेगैर्मुक्तो यः स च मे प्रियः।।', transliteration: 'yasман nodvijate loko lokan nodvijate cha yah', explanations: { en: 'One by whom the world is not troubled, and who is not troubled by the world — free from elation, envy, fear, and agitation — such a person is dear to him.', hi: 'जिससे संसार को कोई कष्ट नहीं होता, और जो संसार से कष्ट नहीं पाता — जो हर्ष, ईर्ष्या, भय और उद्वेग से मुक्त है — ऐसा व्यक्ति उन्हें प्रिय है।' } },
                { verse_number: 16, sanskrit: 'अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः। सर्वारम्भपरित्यागी यो मद्भक्तः स मे प्रियः।।', transliteration: 'anapekshah shuchir daksha udasino gata-vyathah', explanations: { en: 'One who is without expectation, pure, skilled, impartial, free from distress, who abandons all enterprises — such a devotee of his is dear to him.', hi: 'जो निरपेक्ष, पवित्र, कुशल, निष्पक्ष, दुख से मुक्त है, और जो सभी उपक्रमों का त्याग कर चुका है — ऐसा भक्त उन्हें प्रिय है।' } },
                { verse_number: 17, sanskrit: 'यो न हृष्यति न द्वेष्टि न शोचति न काङ्क्षति। शुभाशुभपरित्यागी भक्तिमान्यः स मे प्रियः।।', transliteration: 'yo na hrishyati na dveshti na shochati na kankshati', explanations: { en: 'One who neither rejoices nor hates, neither grieves nor craves, who has renounced good and evil — full of devotion, such a person is dear to him.', hi: 'जो न हर्षित होता है, न द्वेष करता है, न शोक करता है, न कामना करता है, जिसने शुभ और अशुभ दोनों का त्याग कर दिया है — ऐसा भक्तिमान व्यक्ति उन्हें प्रिय है।' } },
                { verse_number: 18, sanskrit: 'समः शत्रौ च मित्रे च तथा मानापमानयोः। शीतोष्णसुखदुःखेषु समः सङ्गविवर्जितः।।', transliteration: 'samah shatrau cha mitre cha tatha manapamana-yoh', explanations: { en: 'Equal to enemy and friend, equal in honor and disgrace, equal in cold and heat, pleasure and pain, free from attachment...', hi: 'जो शत्रु और मित्र में समान भाव रखता है, मान और अपमान में भी समान रहता है, सर्दी-गर्मी और सुख-दुख में समान रहता है, आसक्ति से मुक्त है...' } },
                { verse_number: 19, sanskrit: 'तुल्यनिन्दास्तुतिर्मौनी सन्तुष्टो येन केनचित्। अनिकेतः स्थिरमतिर्भक्तिमान्मे प्रियो नरः।।', transliteration: 'tulya-ninda-stutir mauni santushto yena kenachit', explanations: { en: '...equal in blame and praise, silent, content with anything, having no fixed abode, of steady mind — such a devotee is dear to him.', hi: '...जो निंदा और स्तुति में समान रहता है, मौन रहता है, जो कुछ भी मिले उसी में संतुष्ट रहता है, जिसका कोई स्थायी घर नहीं और मन स्थिर है — ऐसा भक्त उन्हें प्रिय है।' } },
                { verse_number: 20, sanskrit: 'ये तु धर्म्यामृतमिदं यथोक्तं पर्युपासते। श्रद्दधाना मत्परमा भक्तास्तेऽतीव मे प्रियाः।।', transliteration: 'ye tu dharmyamritam idam yathoktam paryupasate', explanations: { en: 'But those who honor this immortal dharma as described, with faith, taking him as the supreme — those devotees are exceedingly dear to him.', hi: 'परंतु जो इस अमृतमय धर्म का, जैसा बताया गया है, श्रद्धापूर्वक पालन करते हैं और कृष्ण को ही परम मानते हैं — ऐसे भक्त उन्हें अत्यंत प्रिय हैं।' } },
            ],
            questions: [{ question_text: 'The qualities Krishna describes in the beloved devotee — friendliness, compassion, equanimity, no envy, no fear, contentment — look more like a description of psychological health than a devotional checklist. Why might that be?', options: [{ text: 'Because psychology and spirituality are separate and Krishna confused them', is_correct: false }, { text: 'Because genuine devotion and genuine psychological freedom are not separate — a heart truly grounded in the divine naturally manifests as peace, compassion, and freedom from reactivity; these qualities are the fruit and the sign of real practice', is_correct: true }, { text: 'Because Krishna is setting impossibly high standards to humble devotees', is_correct: false }], explanation: 'The chapter ends by describing what a mature devotee looks like in ordinary life. The qualities are not requirements to earn God\'s love — they are the natural expression of a heart that has found its ground. This is why they look like flourishing: they are flourishing.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter12;
