// Complete Chapter 2 (Sankhya Yoga - "The Yoga of Knowledge"), all 72 verses,
// split into 17 Parts. This is the chapter where Krishna's actual teaching begins,
// responding to Arjuna's crisis from Chapter 1.
// Sanskrit/transliteration verified against enjoylearningsanskrit.com's chapter-2 text.
// Explanations are original simple paraphrases (not copied from any translator).

const chapter2 = {
    number: 2,
    title: 'The Yoga of Knowledge',
    total_verses: 72,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 3,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 1, sanskrit: 'सञ्जय उवाच। तं तथा कृपयाविष्टमश्रुपूर्णाकुलेक्षणम्। विषीदन्तमिदं वाक्यमुवाच मधुसूदनः।।', transliteration: 'sanjaya uvacha: tam tatha kripayavishtam ashru-purnakulekshanam', explanations: { en: 'Sanjaya tells Dhritarashtra that seeing Arjuna overwhelmed with compassion, his eyes filled with tears, Krishna begins to speak to him.' } },
                { verse_number: 2, sanskrit: 'श्रीभगवानुवाच। कुतस्त्वा कश्मलमिदं विषमे समुपस्थितम्। अनार्यजुष्टमस्वर्ग्यमकीर्तिकरमर्जुन।।', transliteration: 'shri bhagavan uvacha: kutas tva kashmalam idam vishame samupasthitam', explanations: { en: 'Krishna asks Arjuna where this weakness has suddenly come from at this critical moment - noting it isn\'t fitting for a person of his stature and won\'t lead anywhere good.' } },
                { verse_number: 3, sanskrit: 'क्लैब्यं मा स्म गमः पार्थ नैतत्त्वय्युपपद्यते। क्षुद्रं हृदयदौर्बल्यं त्यक्त्वोत्तिष्ठ परन्तप।।', transliteration: 'klaibyam ma sma gamah partha naitat tvayy upapadyate', explanations: { en: 'Krishna tells Arjuna not to give in to this weakness - it doesn\'t suit him - and urges him to cast off this faintheartedness and rise up.' } },
            ],
            questions: [{ question_text: 'What is Krishna\'s first response to Arjuna\'s grief?', options: [{ text: 'He agrees the war should be called off', is_correct: false }, { text: 'He directly challenges Arjuna, telling him this weakness doesn\'t suit him and urging him to rise above it', is_correct: true }, { text: 'He stays silent and lets Arjuna decide alone', is_correct: false }], explanation: 'Krishna doesn\'t validate Arjuna\'s despair as the final word - he immediately pushes back, calling it unworthy of him and asking him to rise above it. This sets the tone for the teaching that follows.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 4,
            verse_end: 8,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 4, sanskrit: 'अर्जुन उवाच। कथं भीष्ममहं संख्ये द्रोणं च मधुसूदन। इषुभिः प्रतियोत्स्यामि पूजार्हावरिसूदन।।', transliteration: 'arjuna uvacha: katham bhishmam aham sankhye dronam cha madhusudana', explanations: { en: 'Arjuna asks Krishna how he could possibly shoot arrows at Bhishma and Drona in battle, when both deserve his worship and respect.' } },
                { verse_number: 5, sanskrit: 'गुरूनहत्वा हि महानुभावाञ्श्रेयो भोक्तुं भैक्ष्यमपीह लोके। हत्वार्थकामांस्तु गुरूनिहैव भुञ्जीय भोगान्रुधिरप्रदिग्धान्।।', transliteration: 'gurun ahatva hi mahanubhavan shreyo bhoktum bhaikshyam api iha loke', explanations: { en: 'Arjuna says he would rather live on alms than kill these great teachers - even if their own desires are impure, killing them would taint every pleasure he might gain from victory.' } },
                { verse_number: 6, sanskrit: 'न चैतद्विद्मः कतरन्नो गरीयो यद्वा जयेम यदि वा नो जयेयुः। यानेव हत्वा न जिजीविषामस्तेऽवस्थिताः प्रमुखे धार्तराष्ट्राः।।', transliteration: 'na chaitad vidmah kataran no gariyo yad va jayema yadi va no jayeyuh', explanations: { en: 'He says he doesn\'t even know which would be better - winning or losing - since the very people he\'d need to kill to survive stand right in front of him.' } },
                { verse_number: 7, sanskrit: 'कार्पण्यदोषोपहतस्वभावः पृच्छामि त्वां धर्मसम्मूढचेताः। यच्छ्रेयः स्यान्निश्चितं ब्रूहि तन्मे शिष्यस्तेऽहं शाधि मां त्वां प्रपन्नम्।।', transliteration: 'karpanya-dosha-upahata-svabhavah prichchhami tvam dharma-sammudha-chetah', explanations: { en: 'Arjuna admits his mind is confused about what\'s right, and formally asks Krishna to teach him clearly - declaring himself Krishna\'s student, surrendered to his guidance.' } },
                { verse_number: 8, sanskrit: 'न हि प्रपश्यामि ममापनुद्याद्यच्छोकमुच्छोषणमिन्द्रियाणाम्। अवाप्य भूमावसपत्नमृद्धं राज्यं सुराणामपि चाधिपत्यम्।।', transliteration: 'na hi prapashyami mama apanudyad yach chhokam uchchhoshanam indriyanam', explanations: { en: 'He says even gaining an unrivaled kingdom on earth, or ruling over the gods themselves, wouldn\'t be enough to remove the grief drying up his senses right now.' } },
            ],
            questions: [{ question_text: 'What is significant about verse 7, where Arjuna calls himself Krishna\'s "disciple"?', options: [{ text: 'It\'s just a polite formality with no real meaning', is_correct: false }, { text: 'It marks the exact moment Arjuna shifts from arguing with Krishna as an equal to formally asking to be taught - which is what opens the door to the rest of the Gita\'s teaching', is_correct: true }, { text: 'It means Arjuna is giving up and leaving the battlefield', is_correct: false }], explanation: 'This is a pivotal moment - by calling himself a disciple and asking to be taught, Arjuna moves from simply venting his grief to actively seeking guidance, which is what allows Krishna\'s teaching to begin.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 9,
            verse_end: 11,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 9, sanskrit: 'सञ्जय उवाच। एवमुक्त्वा हृषीकेशं गुडाकेशः परन्तप। न योत्स्य इति गोविन्दमुक्त्वा तूष्णीं बभूव ह।।', transliteration: 'sanjaya uvacha: evam uktva hrishikesham gudakeshah parantapa', explanations: { en: 'Sanjaya reports that after saying all this, Arjuna tells Krishna "I will not fight" and falls silent.' } },
                { verse_number: 10, sanskrit: 'तमुवाच हृषीकेशः प्रहसन्निव भारत। सेनयोरुभयोर्मध्ये विषीदन्तमिदं वचः।।', transliteration: 'tam uvacha hrishikeshah prahasann iva bharata', explanations: { en: 'Sanjaya notes that Krishna, almost smiling, then begins to speak to the grieving Arjuna, standing between the two armies.' } },
                { verse_number: 11, sanskrit: 'श्रीभगवानुवाच। अशोच्यानन्वशोचस्त्वं प्रज्ञावादांश्च भाषसे। गतासूनगतासूंश्च नानुशोचन्ति पण्डिताः।।', transliteration: 'shri bhagavan uvacha: ashochyan anvashochas tvam prajna-vadamsh cha bhashase', explanations: { en: 'Krishna tells Arjuna he is grieving over things that don\'t truly call for grief, even while sounding wise - because the truly wise do not grieve over the living or the dead in the way Arjuna is.' } },
            ],
            questions: [{ question_text: 'Why might Krishna respond to Arjuna\'s grief "almost smiling," as verse 10 describes?', options: [{ text: 'Because he doesn\'t take Arjuna\'s crisis seriously', is_correct: false }, { text: 'Because Krishna sees the deeper truth beyond Arjuna\'s immediate distress and is about to gently show him a wider perspective', is_correct: true }, { text: 'Because he is mocking Arjuna for being weak', is_correct: false }], explanation: 'Krishna\'s slight smile isn\'t dismissive - it reflects his calm, elevated perspective. He\'s not making light of Arjuna\'s pain, but he can already see the understanding that will resolve it, which is what he\'s about to share.', difficulty: 'application' }],
        },
        {
            part_number: 4,
            verse_start: 12,
            verse_end: 16,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 12, sanskrit: 'न त्वेवाहं जातु नासं न त्वं नेमे जनाधिपाः। न चैव न भविष्यामः सर्वे वयमतः परम्।।', transliteration: 'na tv evaham jatu nasam na tvam neme janadhipah', explanations: { en: 'Krishna says there was never a time he, Arjuna, or any of the kings present didn\'t exist - and none of them will ever cease to exist either.' } },
                { verse_number: 13, sanskrit: 'देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा। तथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति।।', transliteration: 'dehino \'smin yatha dehe kaumaram yauvanam jara', explanations: { en: 'Just as a person passes through childhood, youth, and old age in one body, the soul similarly passes into another body - and a wise person isn\'t disturbed by this transition.' } },
                { verse_number: 14, sanskrit: 'मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः। आगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत।।', transliteration: 'matra-sparshas tu kaunteya shitoshna-sukha-duhkha-dah', explanations: { en: 'Krishna explains that sensations like heat, cold, pleasure, and pain come and go - they\'re temporary, so Arjuna should learn to endure them without being shaken.' } },
                { verse_number: 15, sanskrit: 'यं हि न व्यथयन्त्येते पुरुषं पुरुषर्षभ। समदुःखसुखं धीरं सोऽमृतत्वाय कल्पते।।', transliteration: 'yam hi na vyathayanty ete purusham purusharshabha', explanations: { en: 'He says the person who stays steady through both pain and pleasure, unshaken by these passing sensations, becomes fit for spiritual liberation.' } },
                { verse_number: 16, sanskrit: 'नासतो विद्यते भावो नाभावो विद्यते सतः। उभयोरपि दृष्टोऽन्तस्त्वनयोस्तत्त्वदर्शिभिः।।', transliteration: 'nasato vidyate bhavo nabhavo vidyate satah', explanations: { en: 'Krishna states a core principle: what is unreal never truly exists, and what is real never ceases to exist - those who see truth clearly understand this distinction.' } },
            ],
            questions: [{ question_text: 'What is the core idea Krishna introduces in verses 12-16?', options: [{ text: 'That physical strength matters more than emotional weakness', is_correct: false }, { text: 'That the true self (soul) is eternal and unaffected by temporary bodily experiences like pain, pleasure, or even death', is_correct: true }, { text: 'That kings and warriors have special immortality that ordinary people don\'t', is_correct: false }], explanation: 'This is the philosophical foundation Krishna is building: the real self isn\'t the body but something eternal beneath it, and understanding this shifts how Arjuna should think about "loss" in battle.', difficulty: 'application' }],
        },
        {
            part_number: 5,
            verse_start: 17,
            verse_end: 21,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 17, sanskrit: 'अविनाशि तु तद्विद्धि येन सर्वमिदं ततम्। विनाशमव्ययस्यास्य न कश्चित्कर्तुमर्हति।।', transliteration: 'avinashi tu tad viddhi yena sarvam idam tatam', explanations: { en: 'Krishna says the essence pervading everything in existence is indestructible - no one has the power to destroy this imperishable reality.' } },
                { verse_number: 18, sanskrit: 'अन्तवन्त इमे देहा नित्यस्योक्ताः शरीरिणः। अनाशिनोऽप्रमेयस्य तस्माद्युध्यस्व भारत।।', transliteration: 'antavanta ime deha nityasyoktah sharirinah', explanations: { en: 'He explains that only the physical body is temporary - the soul within it is eternal and beyond destruction. On this basis, he tells Arjuna to fight.' } },
                { verse_number: 19, sanskrit: 'य एनं वेत्ति हन्तारं यश्चैनं मन्यते हतम्। उभौ तौ न विजानीतो नायं हन्ति न हन्यते।।', transliteration: 'ya enam vetti hantaram yash chainam manyate hatam', explanations: { en: 'Krishna says both the person who thinks they can kill the soul, and the person who thinks the soul can be killed, are equally mistaken - the soul is neither killer nor killed.' } },
                { verse_number: 20, sanskrit: 'न जायते म्रियते वा कदाचिन्नायं भूत्वा भविता वा न भूयः। अजो नित्यः शाश्वतोऽयं पुराणो न हन्यते हन्यमाने शरीरे।।', transliteration: 'na jayate mriyate va kadachin nayam bhutva bhavita va na bhuyah', explanations: { en: 'He describes the soul as never being born and never dying - it is eternal, ancient, and unaffected even when the body it inhabits is destroyed.' } },
                { verse_number: 21, sanskrit: 'वेदाविनाशिनं नित्यं य एनमजमव्ययम्। कथं स पुरुषः पार्थ कं घातयति हन्ति कम्।।', transliteration: 'vedavinashinam nityam ya enam ajam avyayam', explanations: { en: 'Krishna asks Arjuna: for someone who truly understands the soul is indestructible and unborn, how could that person meaningfully cause anyone\'s death, or be killed themselves?' } },
            ],
            questions: [{ question_text: 'How does Krishna use the idea of the indestructible soul to address Arjuna\'s guilt about killing?', options: [{ text: 'He says killing is always wrong regardless of circumstances', is_correct: false }, { text: 'He argues that since the soul itself cannot actually be destroyed, Arjuna\'s fear of "killing" his relatives is based on a misunderstanding of what death really means at the deepest level', is_correct: true }, { text: 'He says the rules of killing don\'t apply to warriors', is_correct: false }], explanation: 'Krishna isn\'t dismissing the seriousness of violence - he\'s reframing Arjuna\'s understanding of what death actually is, arguing that the eternal self is untouched even when a body perishes.', difficulty: 'application' }],
        },
        {
            part_number: 6,
            verse_start: 22,
            verse_end: 25,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 22, sanskrit: 'वासांसि जीर्णानि यथा विहाय नवानि गृह्णाति नरोऽपराणि। तथा शरीराणि विहाय जीर्णान्यन्यानि संयाति नवानि देही।।', transliteration: 'vasamsi jirnani yatha vihaya navani grihnati naro \'parani', explanations: { en: 'Krishna gives his famous analogy: just as a person discards worn-out clothes for new ones, the soul discards a worn-out body and takes on a new one.' } },
                { verse_number: 23, sanskrit: 'नैनं छिन्दन्ति शस्त्राणि नैनं दहति पावकः। न चैनं क्लेदयन्त्यापो न शोषयति मारुतः।।', transliteration: 'nainam chhindanti shastrani nainam dahati pavakah', explanations: { en: 'He says weapons cannot cut the soul, fire cannot burn it, water cannot wet it, and wind cannot dry it out.' } },
                { verse_number: 24, sanskrit: 'अच्छेद्योऽयमदाह्योऽयमक्लेद्योऽशोष्य एव च। नित्यः सर्वगतः स्थाणुरचलोऽयं सनातनः।।', transliteration: 'achchhedyo \'yam adahyo \'yam akledyo \'shoshya eva cha', explanations: { en: 'Krishna reiterates that the soul is beyond being cut, burned, wetted, or dried - it is eternal, everywhere, unmoving, and unchanging.' } },
                { verse_number: 25, sanskrit: 'अव्यक्तोऽयमचिन्त्योऽयमविकार्योऽयमुच्यते। तस्मादेवं विदित्वैनं नानुशोचितुमर्हसि।।', transliteration: 'avyakto \'yam achintyo \'yam avikaryo \'yam uchyate', explanations: { en: 'He describes the soul as beyond ordinary perception, beyond full comprehension, and unchanging - and tells Arjuna that understanding this, he shouldn\'t grieve.' } },
            ],
            questions: [{ question_text: 'What is the purpose of the "changing clothes" analogy in verse 22?', options: [{ text: 'To suggest that death should be treated casually or without care', is_correct: false }, { text: 'To make an abstract philosophical idea (the eternal soul vs. the temporary body) easier to grasp using a familiar, everyday image', is_correct: true }, { text: 'To explain the process of reincarnation in scientific detail', is_correct: false }], explanation: 'This is one of the Gita\'s most quoted verses precisely because the clothing analogy makes a difficult metaphysical concept - the body\'s impermanence versus the soul\'s continuity - immediately relatable.', difficulty: 'application' }],
        },
        {
            part_number: 7,
            verse_start: 26,
            verse_end: 30,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 26, sanskrit: 'अथ चैनं नित्यजातं नित्यं वा मन्यसे मृतम्। तथापि त्वं महाबाहो नैनं शोचितुमर्हसि।।', transliteration: 'atha chainam nitya-jatam nityam va manyase mritam', explanations: { en: 'Krishna adds that even if Arjuna believes the soul is repeatedly born and repeatedly dies, he still shouldn\'t grieve.' } },
                { verse_number: 27, sanskrit: 'जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च। तस्मादपरिहार्येऽर्थे न त्वं शोचितुमर्हसि।।', transliteration: 'jatasya hi dhruvo mrityur dhruvam janma mritasya cha', explanations: { en: 'He explains that death is certain for anyone born, and birth is certain for anyone who has died - so grieving over something so unavoidable serves no purpose.' } },
                { verse_number: 28, sanskrit: 'अव्यक्तादीनि भूतानि व्यक्तमध्यानि भारत। अव्यक्तनिधनान्येव तत्र का परिदेवना।।', transliteration: 'avyaktadini bhutani vyakta-madhyani bharata', explanations: { en: 'Krishna points out that beings are unseen before birth and after death, only visible in between - so what is there really to lament?' } },
                { verse_number: 29, sanskrit: 'आश्चर्यवत्पश्यति कश्चिदेनमाश्चर्यवद्वदति तथैव चान्यः। आश्चर्यवच्चैनमन्यः शृणोति श्रुत्वाप्येनं वेद न चैव कश्चित्।।', transliteration: 'ashcharya-vat pashyati kashchid enam ashcharya-vad vadati tathaiva chanyah', explanations: { en: 'He notes that some see the soul as astonishing, some speak of it as astonishing, some hear of it as astonishing - and yet many still don\'t truly grasp it, even after hearing about it.' } },
                { verse_number: 30, sanskrit: 'देही नित्यमवध्योऽयं देहे सर्वस्य भारत। तस्मात्सर्वाणि भूतानि न त्वं शोचितुमर्हसि।।', transliteration: 'dehi nityam avadhyo \'yam dehe sarvasya bharata', explanations: { en: 'Krishna concludes this section by saying the soul within every being can never truly be killed - so Arjuna should not grieve for any living being.' } },
            ],
            questions: [{ question_text: 'Why does Krishna present two different views of the soul (verses 20-25 vs. verse 26) in this passage?', options: [{ text: 'Because he is contradicting himself', is_correct: false }, { text: 'To show that even if Arjuna doesn\'t accept the idea of an eternal, indestructible soul, the same conclusion - not to grieve - still follows from the simple fact that birth and death are natural and inevitable', is_correct: true }, { text: 'Because different philosophies existed and he wanted to confuse Arjuna', is_correct: false }], explanation: 'Krishna is making his argument airtight - whether Arjuna accepts the soul as eternal or believes it is repeatedly born and dies, either way excessive grief over what is natural and unavoidable doesn\'t serve him.', difficulty: 'application' }],
        },
        {
            part_number: 8,
            verse_start: 31,
            verse_end: 35,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 31, sanskrit: 'स्वधर्ममपि चावेक्ष्य न विकम्पितुमर्हसि। धर्म्याद्धि युद्धाच्छ्रेयोऽन्यत्क्षत्रियस्य न विद्यते।।', transliteration: 'svadharmam api chavekshya na vikampitum arhasi', explanations: { en: 'Krishna shifts to a different argument: considering Arjuna\'s own role and duty as a warrior, he shouldn\'t waver - there is no greater good for a warrior than a righteous battle.' } },
                { verse_number: 32, sanskrit: 'यदृच्छया चोपपन्नं स्वर्गद्वारमपावृतम्। सुखिनः क्षत्रियाः पार्थ लभन्ते युद्धमीदृशम्।।', transliteration: 'yadrichchhaya chopapannam svarga-dvaram apavritam', explanations: { en: 'He tells Arjuna that fortunate warriors get the opportunity for exactly this kind of righteous battle, which opens the door to honor.' } },
                { verse_number: 33, sanskrit: 'अथ चेत्त्वमिमं धर्म्यं संग्रामं न करिष्यसि। ततः स्वधर्मं कीर्तिं च हित्वा पापमवाप्स्यसि।।', transliteration: 'atha chet tvam imam dharmyam sangramam na karishyasi', explanations: { en: 'Krishna warns that if Arjuna refuses this righteous battle, he\'ll fail his own duty and reputation, and incur wrongdoing instead.' } },
                { verse_number: 34, sanskrit: 'अकीर्तिं चापि भूतानि कथयिष्यन्ति तेऽव्ययाम्। सम्भावितस्य चाकीर्तिर्मरणादतिरिच्यते।।', transliteration: 'akirtim chapi bhutani kathayishyanti te \'vyayam', explanations: { en: 'He tells Arjuna that people will remember his dishonor forever if he backs out now - and for a respected person, dishonor can feel worse than death itself.' } },
                { verse_number: 35, sanskrit: 'भयाद्रणादुपरतं मंस्यन्ते त्वां महारथाः। येषां च त्वं बहुमतो भूत्वा यास्यसि लाघवम्।।', transliteration: 'bhayad ranad uparatam mamsyante tvam maharathah', explanations: { en: 'Krishna points out that the great warriors who respect Arjuna now would assume he fled out of fear, and his reputation would fall.' } },
            ],
            questions: [{ question_text: 'How does Krishna\'s argument shift between verses 12-30 and verses 31-35?', options: [{ text: 'He moves from a purely philosophical argument about the eternal soul to a practical argument about Arjuna\'s duty and reputation as a warrior', is_correct: true }, { text: 'He starts repeating the same philosophical point over and over', is_correct: false }, { text: 'He switches to talking about Arjuna\'s family instead', is_correct: false }], explanation: 'Krishna layers his arguments - first establishing the philosophical truth about the eternal soul, then appealing to Arjuna\'s specific role and duty as a warrior (kshatriya), showing the teaching from multiple angles.', difficulty: 'application' }],
        },
        {
            part_number: 9,
            verse_start: 36,
            verse_end: 38,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 36, sanskrit: 'अवाच्यवादांश्च बहून्वदिष्यन्ति तवाहिताः। निन्दन्तस्तव सामर्थ्यं ततो दुःखतरं नु किम्।।', transliteration: 'avachya-vadamsh cha bahun vadishyanti tavahitah', explanations: { en: 'Krishna warns Arjuna that his enemies will mock his abilities with harsh words, and asks what could be more painful than that kind of humiliation.' } },
                { verse_number: 37, sanskrit: 'हतो वा प्राप्स्यसि स्वर्गं जित्वा वा भोक्ष्यसे महीम्। तस्मादुत्तिष्ठ कौन्तेय युद्धाय कृतनिश्चयः।।', transliteration: 'hato va prapsyasi svargam jitva va bhokshyase mahim', explanations: { en: 'He frames the outcome as a win either way: if Arjuna dies, he attains heaven; if he wins, he enjoys the earth. On this basis, Krishna urges him to rise with firm resolve.' } },
                { verse_number: 38, sanskrit: 'सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ। ततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि।।', transliteration: 'sukha-duhkhe same kritva labhalabhau jayajayau', explanations: { en: 'Krishna tells Arjuna to treat pleasure and pain, gain and loss, victory and defeat as the same, and to fight with that mindset - this way, he won\'t incur wrongdoing.' } },
            ],
            questions: [{ question_text: 'What is the key mental shift Krishna asks Arjuna to make in verse 38?', options: [{ text: 'To stop caring about the outcome of the battle entirely', is_correct: false }, { text: 'To act fully while remaining internally equanimous about results like victory/defeat or gain/loss - acting without being emotionally hijacked by outcomes', is_correct: true }, { text: 'To fight only if he\'s guaranteed to win', is_correct: false }], explanation: 'This introduces a central theme of the Gita: equanimity in action. Krishna isn\'t asking Arjuna to be indifferent to the battle, but to act fully without his mind being consumed by attachment to particular outcomes.', difficulty: 'application' }],
        },
        {
            part_number: 10,
            verse_start: 39,
            verse_end: 41,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 39, sanskrit: 'एषा तेऽभिहिता सांख्ये बुद्धिर्योगे त्विमां शृणु। बुद्ध्या युक्तो यया पार्थ कर्मबन्धं प्रहास्यसि।।', transliteration: 'esha te \'bhihita sankhye buddhir yoge tv imam shrinu', explanations: { en: 'Krishna says he has explained this understanding through knowledge (Sankhya); now he will explain it through the path of action (yoga), which will free Arjuna from the bondage caused by action.' } },
                { verse_number: 40, sanskrit: 'नेहाभिक्रमनाशोऽस्ति प्रत्यवायो न विद्यते। स्वल्पमप्यस्य धर्मस्य त्रायते महतो भयात्।।', transliteration: 'nehabhikrama-nasho \'sti pratyavayo na vidyate', explanations: { en: 'He assures Arjuna that on this path, no effort is ever wasted and there\'s no risk of a negative outcome - even a small amount of practice protects from great fear.' } },
                { verse_number: 41, sanskrit: 'व्यवसायात्मिका बुद्धिरेकेह कुरुनन्दन। बहुशाखा ह्यनन्ताश्च बुद्धयोऽव्यवसायिनाम्।।', transliteration: 'vyavasayatmika buddhir ekeha kuru-nandana', explanations: { en: 'Krishna explains that a resolved, focused mind on this path is single and clear, whereas the minds of the irresolute branch out endlessly, scattered in many directions.' } },
            ],
            questions: [{ question_text: 'What new concept does Krishna introduce in verse 39 that will become central to the rest of the Gita?', options: [{ text: 'The idea of physical strength training', is_correct: false }, { text: 'Karma yoga - the path of acting skillfully and without attachment, as a complement to philosophical knowledge', is_correct: true }, { text: 'The idea that only priests can achieve liberation', is_correct: false }], explanation: 'This marks a shift from pure philosophy (Sankhya) to practical action (yoga) - the idea that one can achieve the same liberation through the way one acts in the world, not just through abstract knowledge.', difficulty: 'application' }],
        },
        {
            part_number: 11,
            verse_start: 42,
            verse_end: 46,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 42, sanskrit: 'यामिमां पुष्पितां वाचं प्रवदन्त्यविपश्चितः। वेदवादरताः पार्थ नान्यदस्तीति वादिनः।।', transliteration: 'yam imam pushpitam vacham pravadanty avipashchitah', explanations: { en: 'Krishna cautions Arjuna about people who use flowery language, focused only on the ritual portions of scripture, insisting nothing else matters beyond that.' } },
                { verse_number: 43, sanskrit: 'कामात्मानः स्वर्गपरा जन्मकर्मफलप्रदाम्। क्रियाविशेषबहुलां भोगैश्वर्यगतिं प्रति।।', transliteration: 'kamatmanah svarga-para janma-karma-phala-pradam', explanations: { en: 'He describes such people as driven by desire, focused on heaven as a reward, caught up in elaborate rituals aimed at pleasure and status.' } },
                { verse_number: 44, sanskrit: 'भोगैश्वर्यप्रसक्तानां तयापहृतचेतसाम्। व्यवसायात्मिका बुद्धिः समाधौ न विधीयते।।', transliteration: 'bhogaishvarya-prasaktanam tayapahrita-chetasam', explanations: { en: 'Krishna says that people whose minds are captivated by pleasure and status this way don\'t develop the steady, focused intelligence needed for meditation.' } },
                { verse_number: 45, sanskrit: 'त्रैगुण्यविषया वेदा निस्त्रैगुण्यो भवार्जुन। निर्द्वन्द्वो नित्यसत्त्वस्थो निर्योगक्षेम आत्मवान्।।', transliteration: 'trai-gunya-vishaya veda nistrai-gunyo bhavarjuna', explanations: { en: 'He tells Arjuna to rise above the material dualities that much of scripture concerns itself with - to stay balanced, self-aware, and unconcerned with gain and security.' } },
                { verse_number: 46, sanskrit: 'यावानर्थ उदपाने सर्वतः सम्प्लुतोदके। तावान्सर्वेषु वेदेषु ब्राह्मणस्य विजानतः।।', transliteration: 'yavan artha udapane sarvatah samplutodake', explanations: { en: 'Krishna uses an analogy: just as a small well becomes irrelevant when there\'s a vast reservoir of water available, all the ritual portions of scripture become less relevant to someone who has true understanding.' } },
            ],
            questions: [{ question_text: 'What is Krishna cautioning against in this passage (verses 42-46)?', options: [{ text: 'Reading scripture at all', is_correct: false }, { text: 'Getting stuck at a surface level - performing rituals purely for status, pleasure, or heavenly rewards - without developing the deeper understanding scripture is meant to point toward', is_correct: true }, { text: 'Following any religious tradition whatsoever', is_correct: false }], explanation: 'Krishna isn\'t rejecting scripture itself - he\'s warning against treating its ritual aspects as the whole point, when true understanding goes beyond seeking rewards through ritual.', difficulty: 'application' }],
        },
        {
            part_number: 12,
            verse_start: 47,
            verse_end: 50,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 47, sanskrit: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि।।', transliteration: 'karmany evadhikaras te ma phaleshu kadachana', explanations: { en: 'This is one of the Gita\'s most famous verses: Krishna tells Arjuna he has the right to perform his duty, but never to the fruits of his actions - and he shouldn\'t be motivated by results, nor attached to inaction either.' } },
                { verse_number: 48, sanskrit: 'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय। सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते।।', transliteration: 'yoga-sthah kuru karmani sangam tyaktva dhananjaya', explanations: { en: 'Krishna tells Arjuna to perform action while established in yoga, letting go of attachment, staying balanced in success and failure - this balance itself is called yoga.' } },
                { verse_number: 49, sanskrit: 'दूरेण ह्यवरं कर्म बुद्धियोगाद्धनञ्जय। बुद्धौ शरणमन्विच्छ कृपणाः फलहेतवः।।', transliteration: 'durena hy avaram karma buddhi-yogad dhananjaya', explanations: { en: 'He says action done purely for results is far inferior to acting with this equanimous understanding - and tells Arjuna to take refuge in this wisdom, since those obsessed with results live in a kind of poverty of spirit.' } },
                { verse_number: 50, sanskrit: 'बुद्धियुक्तो जहातीह उभे सुकृतदुष्कृते। तस्माद्योगाय युज्यस्व योगः कर्मसु कौशल्यम्।।', transliteration: 'buddhi-yukto jahatiha ubhe sukrita-dushkrite', explanations: { en: 'Krishna says a person established in this understanding rises above both good and bad deeds in a worldly sense - and describes this skillful way of acting as the essence of yoga.' } },
            ],
            questions: [{ question_text: 'What does Krishna\'s teaching in verse 47 ("right to action, not to the fruits") actually mean in practice?', options: [{ text: 'That effort and outcomes don\'t matter at all', is_correct: false }, { text: 'That we should give our full effort to what we do, while releasing our grip on controlling or being emotionally consumed by the outcome, since outcomes depend on many factors beyond our control', is_correct: true }, { text: 'That people should stop working and let things happen on their own', is_correct: false }], explanation: 'This teaching doesn\'t mean indifference to results - it means acting wholeheartedly while not being enslaved by anxiety over outcomes, since results depend on far more than effort alone.', difficulty: 'application' }],
        },
        {
            part_number: 13,
            verse_start: 51,
            verse_end: 53,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 51, sanskrit: 'कर्मजं बुद्धियुक्ता हि फलं त्यक्त्वा मनीषिणः। जन्मबन्धविनिर्मुक्ताः पदं गच्छन्त्यनामयम्।।', transliteration: 'karma-jam buddhi-yukta hi phalam tyaktva manishinah', explanations: { en: 'Krishna says the wise, established in this equanimous understanding, let go of the results born from action and become free from the cycle of rebirth, reaching a state beyond sorrow.' } },
                { verse_number: 52, sanskrit: 'यदा ते मोहकलिलं बुद्धिर्व्यतितरिष्यति। तदा गन्तासि निर्वेदं श्रोतव्यस्य श्रुतस्य च।।', transliteration: 'yada te moha-kalilam buddhir vyatitarishyati', explanations: { en: 'He tells Arjuna that when his intellect crosses beyond the fog of confusion, he\'ll become indifferent to distinctions between what he has and hasn\'t yet heard in scripture.' } },
                { verse_number: 53, sanskrit: 'श्रुतिविप्रतिपन्ना ते यदा स्थास्यति निश्चला। समाधावचला बुद्धिस्तदा योगमवाप्स्यसि।।', transliteration: 'shruti-vipratipanna te yada sthasyati nishchala', explanations: { en: 'Krishna says when Arjuna\'s intellect, no longer confused by conflicting scriptural opinions, becomes steady in meditation, he will attain true yoga.' } },
            ],
            questions: [{ question_text: 'What does Krishna mean by becoming "indifferent" to scripture in verse 52?', options: [{ text: 'That scripture is worthless and should be ignored entirely', is_correct: false }, { text: 'That once genuine inner understanding is reached, one no longer needs to anxiously debate or chase every scriptural detail, since the deeper truth becomes directly clear', is_correct: true }, { text: 'That Arjuna should stop listening to Krishna\'s teaching', is_correct: false }], explanation: 'This isn\'t a rejection of scripture - it describes the natural settling that happens once real understanding takes root, where external debates matter less because the truth has become internally clear.', difficulty: 'application' }],
        },
        {
            part_number: 14,
            verse_start: 54,
            verse_end: 58,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 54, sanskrit: 'अर्जुन उवाच। स्थितप्रज्ञस्य का भाषा समाधिस्थस्य केशव। स्थितधीः किं प्रभाषेत किमासीत व्रजेत किम्।।', transliteration: 'arjuna uvacha: sthita-prajnasya ka bhasha samadhi-sthasya keshava', explanations: { en: 'Arjuna, curious now, asks Krishna what a person of steady wisdom looks like - how do they speak, sit, and move through the world?' } },
                { verse_number: 55, sanskrit: 'श्रीभगवानुवाच। प्रजहाति यदा कामान्सर्वान्पार्थ मनोगतान्। आत्मन्येवात्मना तुष्टः स्थितप्रज्ञस्तदोच्यते।।', transliteration: 'shri bhagavan uvacha: prajahati yada kaman sarvan partha mano-gatan', explanations: { en: 'Krishna answers that when someone gives up all the desires arising in the mind, finding contentment in the self alone, they are said to have steady wisdom.' } },
                { verse_number: 56, sanskrit: 'दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः। वीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते।।', transliteration: 'duhkheshv anudvigna-manah sukheshu vigata-sprihah', explanations: { en: 'He describes this person as unshaken by suffering, free of craving for pleasure, and free from attachment, fear, and anger.' } },
                { verse_number: 57, sanskrit: 'यः सर्वत्रानभिस्नेहस्तत्तत्प्राप्य शुभाशुभम्। नाभिनन्दति न द्वेष्टि तस्य प्रज्ञा प्रतिष्ठिता।।', transliteration: 'yah sarvatranabhisnehas tat tat prapya shubhashubham', explanations: { en: 'Krishna says such a person, without excessive attachment to anything, neither celebrates good fortune nor resents bad fortune - their wisdom is firmly established.' } },
                { verse_number: 58, sanskrit: 'यदा संहरते चायं कूर्मोऽङ्गानीव सर्वशः। इन्द्रियाणीन्द्रियार्थेभ्यस्तस्य प्रज्ञा प्रतिष्ठिता।।', transliteration: 'yada samharate chayam kurmo \'nganiva sarvashah', explanations: { en: 'He compares this person to a tortoise withdrawing its limbs - just as fully, they can withdraw their senses from external objects, and this too marks steady wisdom.' } },
            ],
            questions: [{ question_text: 'What prompts Arjuna to ask about the "person of steady wisdom" in verse 54?', options: [{ text: 'He wants to change the subject away from the war', is_correct: false }, { text: 'Having just heard about equanimity and freedom from attachment, he wants a concrete picture of what that actually looks like in a real person', is_correct: true }, { text: 'He is testing whether Krishna actually knows the answer', is_correct: false }], explanation: 'This question marks a natural turn in the dialogue - Arjuna moves from grief to genuine philosophical curiosity, wanting to understand practically what the ideal Krishna has described would look like in daily life.', difficulty: 'application' }],
        },
        {
            part_number: 15,
            verse_start: 59,
            verse_end: 63,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 59, sanskrit: 'विषया विनिवर्तन्ते निराहारस्य देहिनः। रसवर्जं रसोऽप्यस्य परं दृष्ट्वा निवर्तते।।', transliteration: 'vishaya vinivartante nirahara-sya dehinah', explanations: { en: 'Krishna notes that a person can outwardly abstain from indulgence, but the underlying craving may remain - it truly fades only once one experiences something higher.' } },
                { verse_number: 60, sanskrit: 'यततो ह्यपि कौन्तेय पुरुषस्य विपश्चितः। इन्द्रियाणि प्रमाथीनि हरन्ति प्रसभं मनः।।', transliteration: 'yatato hy api kaunteya purushasya vipashchitah', explanations: { en: 'He warns that even a wise, striving person can have their mind forcibly swept away by the turbulent senses.' } },
                { verse_number: 61, sanskrit: 'तानि सर्वाणि संयम्य युक्त आसीत मत्परः। वशे हि यस्येन्द्रियाणि तस्य प्रज्ञा प्रतिष्ठिता।।', transliteration: 'tani sarvani samyamya yukta asita mat-parah', explanations: { en: 'Krishna advises bringing all the senses under control and staying focused, centered on him - since a person whose senses are mastered has firmly established wisdom.' } },
                { verse_number: 62, sanskrit: 'ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते। सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते।।', transliteration: 'dhyayato vishayan pumsah sangas teshupajayate', explanations: { en: 'He explains a chain reaction: dwelling on sense objects creates attachment, attachment breeds desire, and desire gives rise to anger when thwarted.' } },
                { verse_number: 63, sanskrit: 'क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः। स्मृतिभ्रंशाद्बुद्धिनाशो बुद्धिनाशात्प्रणश्यति।।', transliteration: 'krodhad bhavati sammohah sammohat smriti-vibhramah', explanations: { en: 'Krishna continues the chain: anger leads to delusion, delusion confuses memory, confused memory destroys discernment, and losing discernment leads a person to ruin.' } },
            ],
            questions: [{ question_text: 'What is the "chain reaction" Krishna describes in verses 62-63, and why does it matter?', options: [{ text: 'A description of how good habits are formed', is_correct: false }, { text: 'A step-by-step breakdown of how uncontrolled dwelling on desires can spiral into anger, confusion, and ultimately self-destructive decisions - showing why controlling the mind\'s starting point matters', is_correct: true }, { text: 'A warning specifically about food and diet', is_correct: false }], explanation: 'This passage maps out psychologically how small, unchecked mental habits (dwelling on desires) can snowball into much larger consequences, which is why Krishna emphasizes catching this pattern early.', difficulty: 'application' }],
        },
        {
            part_number: 16,
            verse_start: 64,
            verse_end: 68,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 64, sanskrit: 'रागद्वेषवियुक्तैस्तु विषयानिन्द्रियैश्चरन्। आत्मवश्यैर्विधेयात्मा प्रसादमधिगच्छति।।', transliteration: 'raga-dvesha-viyuktais tu vishayan indriyaish charan', explanations: { en: 'Krishna says that a disciplined person, engaging with the world through senses free from attraction and aversion, attains inner clarity.' } },
                { verse_number: 65, sanskrit: 'प्रसादे सर्वदुःखानां हानिरस्योपजायते। प्रसन्नचेतसो ह्याशु बुद्धिः पर्यवतिष्ठते।।', transliteration: 'prasade sarva-duhkhanam hanir asyopajayate', explanations: { en: 'He explains that with this clarity, all sorrows dissolve, and the intellect of someone with a peaceful mind quickly becomes steady.' } },
                { verse_number: 66, sanskrit: 'नास्ति बुद्धिरयुक्तस्य न चायुक्तस्य भावना। न चाभावयतः शान्तिरशान्तस्य कुतः सुखम्।।', transliteration: 'nasti buddhir ayuktasya na chayuktasya bhavana', explanations: { en: 'Krishna states that without inner discipline, there\'s no true wisdom or peace of mind - and without peace, how could there be real happiness?' } },
                { verse_number: 67, sanskrit: 'इन्द्रियाणां हि चरतां यन्मनोऽनुविधीयते। तदस्य हरति प्रज्ञां वायुर्नावमिवाम्भसि।।', transliteration: 'indriyanam hi charatam yan mano \'nuvidhiyate', explanations: { en: 'He compares an undisciplined mind following the wandering senses to a boat being swept away by wind on water - it carries away one\'s wisdom.' } },
                { verse_number: 68, sanskrit: 'तस्माद्यस्य महाबाहो निगृहीतानि सर्वशः। इन्द्रियाणीन्द्रियार्थेभ्यस्तस्य प्रज्ञा प्रतिष्ठिता।।', transliteration: 'tasmad yasya mahabaho nigrihitani sarvashah', explanations: { en: 'Krishna concludes this passage: whoever has fully restrained their senses from their objects has firmly established wisdom.' } },
            ],
            questions: [{ question_text: 'What is the relationship between sense-control and peace of mind that Krishna describes here?', options: [{ text: 'They are unrelated - peace comes purely from external circumstances', is_correct: false }, { text: 'Mastery over the senses leads to inner clarity, which leads to lasting peace, which is the actual foundation for real happiness', is_correct: true }, { text: 'Only monks and ascetics can achieve any of this', is_correct: false }], explanation: 'Krishna is building a logical chain: sense discipline leads to clarity, clarity leads to peace, and peace is the real foundation of happiness - suggesting happiness isn\'t primarily about external gain.', difficulty: 'application' }],
        },
        {
            part_number: 17,
            verse_start: 69,
            verse_end: 72,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 69, sanskrit: 'या निशा सर्वभूतानां तस्यां जागर्ति संयमी। यस्यां जाग्रति भूतानि सा निशा पश्यतो मुनेः।।', transliteration: 'ya nisha sarva-bhutanam tasyam jagarti samyami', explanations: { en: 'Krishna offers a striking image: what is night for most beings, the self-controlled person is awake to; what most beings are awake to, is like night to the wise sage.' } },
                { verse_number: 70, sanskrit: 'आपूर्यमाणमचलप्रतिष्ठं समुद्रमापः प्रविशन्ति यद्वत्। तद्वत्कामा यं प्रविशन्ति सर्वे स शान्तिमाप्नोति न कामकामी।।', transliteration: 'apuryamanam achala-pratishtham samudram apah pravishanti yadvat', explanations: { en: 'He compares peace to the ocean: just as rivers flow into it without disturbing it, desires can enter a person\'s life without disturbing them - that person, not the one chasing desires, finds true peace.' } },
                { verse_number: 71, sanskrit: 'विहाय कामान्यः सर्वान्पुमांश्चरति निःस्पृहः। निर्ममो निरहङ्कारः स शान्तिमधिगच्छति।।', transliteration: 'vihaya kaman yah sarvan pumamsh charati nihsprihah', explanations: { en: 'Krishna says the person who lets go of all desires, moving through life without craving, possessiveness, or ego, attains true peace.' } },
                { verse_number: 72, sanskrit: 'एषा ब्राह्मी स्थितिः पार्थ नैनां प्राप्य विमुह्यति। स्थित्वास्यामन्तकालेऽपि ब्रह्मनिर्वाणमृच्छति।।', transliteration: 'esha brahmi sthitih partha nainam prapya vimuhyati', explanations: { en: 'Krishna closes the chapter by telling Arjuna this is the divine state - once attained, a person is never again bewildered, and even at the moment of death, they reach ultimate liberation.' } },
            ],
            questions: [{ question_text: 'How does Chapter 2 end, and what does it set up for the rest of the Gita?', options: [{ text: 'It ends with Arjuna still confused and refusing to fight, unchanged from Chapter 1', is_correct: false }, { text: 'It ends with Krishna having laid out the foundational philosophy - the eternal soul, equanimity, and disciplined action - setting the stage for the more detailed paths of yoga explored in later chapters', is_correct: true }, { text: 'It ends with the battle already being fought', is_correct: false }], explanation: 'Chapter 2 establishes the core philosophical foundation of the entire Gita - the eternal soul, equanimity, and skillful action - which later chapters will build on by exploring different paths (devotion, knowledge, meditation) toward the same understanding.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter2;
