// Complete Chapter 4 (Jnana Karma Sanyasa Yoga - "The Yoga of Knowledge and Action"),
// all 42 verses, split into 8 parts.

const chapter4 = {
    number: 4,
    title: 'The Yoga of Knowledge and Action',
    total_verses: 42,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 5,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 1, sanskrit: 'श्रीभगवानुवाच। इमं विवस्वते योगं प्रोक्तवानहमव्ययम्। विवस्वान्मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत्।।', transliteration: 'shri bhagavan uvacha: imam vivasvate yogam proktavan aham avyayam', explanations: { en: 'Krishna says he taught this eternal yoga to Vivasvan (the sun god), who passed it to Manu, who passed it to Ikshvaku — establishing a lineage for this teaching.' } },
                { verse_number: 2, sanskrit: 'एवं परम्पराप्राप्तमिमं राजर्षयो विदुः। स कालेनेह महता योगो नष्टः परन्तप।।', transliteration: 'evam parampara-praptam imam rajarshayo viduh', explanations: { en: 'The royal sages knew this yoga through this succession, but over time it was lost in this world.' } },
                { verse_number: 3, sanskrit: 'स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः। भक्तोऽसि मे सखा चेति रहस्यं ह्येतदुत्तमम्।।', transliteration: 'sa evayam maya te\'dya yogah proktah puratanah', explanations: { en: 'That same ancient yoga is what Krishna is now teaching Arjuna, because Arjuna is his devotee and friend — and this is the supreme secret.' } },
                { verse_number: 4, sanskrit: 'अर्जुन उवाच। अपरं भवतो जन्म परं जन्म विवस्वतः। कथमेतद्विजानीयां त्वमादौ प्रोक्तवानिति।।', transliteration: 'arjuna uvacha: aparam bhavato janma param janma vivasvata', explanations: { en: 'Arjuna asks how this is possible — Vivasvan was born long before Krishna, so how could Krishna have taught him?' } },
                { verse_number: 5, sanskrit: 'श्रीभगवानुवाच। बहूनि मे व्यतीतानि जन्मानि तव चार्जुन। तान्यहं वेद सर्वाणि न त्वं वेत्थ परन्तप।।', transliteration: 'shri bhagavan uvacha: bahuni me vyatitani janmani tava charjuna', explanations: { en: 'Krishna reveals: both he and Arjuna have passed through many births, but Krishna knows all of them while Arjuna does not — pointing to Krishna\'s divine, unbound nature.' } },
            ],
            questions: [{ question_text: 'Why does Krishna begin Chapter 4 by tracing his teaching back to Vivasvan and ancient kings?', options: [{ text: 'To prove his teaching is more popular than other philosophies', is_correct: false }, { text: 'To establish that this wisdom is eternal and not something he invented — it has been passed down through great beings and was only lost over time, not obsolete', is_correct: true }, { text: 'To show that only royalty can receive this teaching', is_correct: false }], explanation: 'By tracing the lineage, Krishna frames his teaching not as new philosophy but as the rediscovery of a timeless truth that was lost. This gives the teaching an authority beyond any single teacher or era.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 6,
            verse_end: 10,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 6, sanskrit: 'अजोऽपि सन्नव्ययात्मा भूतानामीश्वरोऽपि सन्। प्रकृतिं स्वामधिष्ठाय सम्भवाम्यात्ममायया।।', transliteration: 'ajo\'pi sann avyayatma bhutanam ishvaro\'pi san', explanations: { en: 'Though unborn and imperishable, and the Lord of all beings, Krishna says he appears in the world by his own creative power, governing his own nature.' } },
                { verse_number: 7, sanskrit: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्।।', transliteration: 'yada yada hi dharmasya glanir bhavati bharata', explanations: { en: 'Whenever righteousness declines and unrighteousness rises, Krishna says he creates himself — that is, takes form in the world.' } },
                { verse_number: 8, sanskrit: 'परित्राणाय साधूनां विनाशाय च दुष्कृताम्। धर्मसंस्थापनार्थाय सम्भवामि युगे युगे।।', transliteration: 'paritranaya sadhunam vinashaya cha dushkritam', explanations: { en: 'He comes age after age to protect the good, destroy the wicked, and re-establish righteousness.' } },
                { verse_number: 9, sanskrit: 'जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः। त्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन।।', transliteration: 'janma karma cha me divyam evam yo vetti tattvatah', explanations: { en: 'Whoever truly understands the divine nature of Krishna\'s birth and actions is freed from rebirth and comes to Krishna after leaving the body.' } },
                { verse_number: 10, sanskrit: 'वीतरागभयक्रोधा मन्मया मामुपाश्रिताः। बहवो ज्ञानतपसा पूता मद्भावमागताः।।', transliteration: 'vita-raga-bhaya-krodhah man-maya mam upashritah', explanations: { en: 'Many people, purified by the fire of knowledge, free from attachment, fear, and anger, devoted to Krishna, have reached his state.' } },
            ],
            questions: [{ question_text: 'What does verse 7\'s famous declaration — that Krishna appears whenever righteousness declines — say about how the divine interacts with the world?', options: [{ text: 'That God only appears once in history', is_correct: false }, { text: 'That the divine is not absent from the world but responds to its moral state — reappearing in whatever form needed when the balance tips too far toward harm', is_correct: true }, { text: 'That humans have no responsibility since God will fix everything', is_correct: false }], explanation: 'This verse describes a dynamic, responsive divine presence — not a one-time event. It also implicitly places a responsibility on humans: the need for divine intervention arises precisely because of human choices.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 11,
            verse_end: 15,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 11, sanskrit: 'ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम्। मम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः।।', transliteration: 'ye yatha mam prapadyante tams tathaiva bhajamy aham', explanations: { en: 'In whatever way people approach Krishna, he rewards them in exactly that way. All paths humans walk ultimately lead to him.' } },
                { verse_number: 12, sanskrit: 'काङ्क्षन्तः कर्मणां सिद्धिं यजन्त इह देवताः। क्षिप्रं हि मानुषे लोके सिद्धिर्भवति कर्मजा।।', transliteration: 'kankshantah karmanam siddhim yajanta iha devatah', explanations: { en: 'Those desiring the results of action worship the various deities in this world, since worldly success can come quickly through such action.' } },
                { verse_number: 13, sanskrit: 'चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः। तस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम्।।', transliteration: 'chatur-varnyam maya srishtam guna-karma-vibhagashah', explanations: { en: 'The four-fold social order was created by Krishna according to the division of qualities and activities — yet he, the creator, is beyond action and unchangeable.' } },
                { verse_number: 14, sanskrit: 'न मां कर्माणि लिम्पन्ति न मे कर्मफले स्पृहा। इति मां योऽभिजानाति कर्मभिर्न स बध्यते।।', transliteration: 'na mam karmani limpanti na me karma-phale spriha', explanations: { en: 'Actions don\'t bind Krishna because he has no desire for their results. Whoever understands this about him is also not bound by their actions.' } },
                { verse_number: 15, sanskrit: 'एवं ज्ञात्वा कृतं कर्म पूर्वैरपि मुमुक्षुभिः। कुरु कर्मैव तस्मात्त्वं पूर्वैः पूर्वतरं कृतम्।।', transliteration: 'evam jnatva kritam karma purvaih api mumukshubhih', explanations: { en: 'The ancient seekers of liberation also acted with this understanding. Arjuna should therefore perform his action as those predecessors did.' } },
            ],
            questions: [{ question_text: 'What is the significance of verse 11 — that Krishna responds to everyone in the way they approach him?', options: [{ text: 'That all religious paths lead to the same destination regardless of sincerity', is_correct: false }, { text: 'That the divine meets each person where they are — the depth and nature of what one receives reflects the depth and nature of how one approaches', is_correct: true }, { text: 'That worship of any deity is equally effective', is_correct: false }], explanation: 'This verse is often read as confirming the validity of multiple paths, but it also carries a subtler point: what you get from any spiritual practice reflects what you bring to it. A shallow approach yields shallow results; sincere devotion yields deeper return.', difficulty: 'application' }],
        },
        {
            part_number: 4,
            verse_start: 16,
            verse_end: 20,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 16, sanskrit: 'किं कर्म किमकर्मेति कवयोऽप्यत्र मोहिताः। तत्ते कर्म प्रवक्ष्यामि यज्ज्ञात्वा मोक्ष्यसेऽशुभात्।।', transliteration: 'kim karma kim akarmeti kavayo\'py atra mohitah', explanations: { en: 'Even the wise are confused about what is action and what is inaction. Krishna says he will explain this clearly so that Arjuna can be freed from misfortune.' } },
                { verse_number: 17, sanskrit: 'कर्मणो ह्यपि बोद्धव्यं बोद्धव्यं च विकर्मणः। अकर्मणश्च बोद्धव्यं गहना कर्मणो गतिः।।', transliteration: 'karmano hy api boddhavyam boddhavyam cha vikarmanas', explanations: { en: 'One must understand what is right action, what is wrong action, and what is inaction — the way of action is deep and difficult.' } },
                { verse_number: 18, sanskrit: 'कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः। स बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत्।।', transliteration: 'karmany akarma yah pashyed akarmani cha karma yah', explanations: { en: 'The person who sees inaction in action and action in inaction is wise among humans — they are a yogi even while performing all actions.' } },
                { verse_number: 19, sanskrit: 'यस्य सर्वे समारम्भाः कामसङ्कल्पवर्जिताः। ज्ञानाग्निदग्धकर्माणं तमाहुः पण्डितं बुद्धाः।।', transliteration: 'yasya sarve samarambhah kama-sankalpa-varjitah', explanations: { en: 'The wise call someone a true pandit whose every undertaking is free from desire-motivated will, and whose actions are burned up in the fire of knowledge.' } },
                { verse_number: 20, sanskrit: 'त्यक्त्वा कर्मफलासङ्गं नित्यतृप्तो निराश्रयः। कर्मण्यभिप्रवृत्तोऽपि नैव किञ्चित्करोति सः।।', transliteration: 'tyaktva karma-phalasangam nitya-tripto nirashriyah', explanations: { en: 'Giving up attachment to the results of action, always content, without dependence on anything — even while engaged in action, such a person does nothing at all in the deepest sense.' } },
            ],
            questions: [{ question_text: 'What does Krishna mean in verse 18 by "seeing inaction in action"?', options: [{ text: 'That physically active people are actually lazy inside', is_correct: false }, { text: 'That a person acting without ego or attachment is, at the deepest level, not the true doer — the action happens through them but doesn\'t accumulate karma for the self', is_correct: true }, { text: 'That one should meditate instead of working', is_correct: false }], explanation: 'This is one of the Gita\'s deepest paradoxes. The truly wise person acts fully in the world but is internally unattached — so at the level of the self, nothing is truly "done" in the ego-driven sense. This is what breaks the cycle of karma.', difficulty: 'application' }],
        },
        {
            part_number: 5,
            verse_start: 21,
            verse_end: 26,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 21, sanskrit: 'निराशीर्यतचित्तात्मा त्यक्तसर्वपरिग्रहः। शारीरं केवलं कर्म कुर्वन्नाप्नोति किल्बिषम्।।', transliteration: 'nirashir yata-chittatma tyakta-sarva-parigraahah', explanations: { en: 'Free from hope, with a controlled mind and self, having abandoned all possessiveness — performing only bodily action, such a person incurs no wrongdoing.' } },
                { verse_number: 22, sanskrit: 'यदृच्छालाभसन्तुष्टो द्वन्द्वातीतो विमत्सरः। समः सिद्धावसिद्धौ च कृत्वापि न निबध्यते।।', transliteration: 'yadrichchha-labha-santushtah dvandvatito vimatsarah', explanations: { en: 'Content with whatever comes on its own, beyond the pairs of opposites, free from envy, equal in success and failure — even while acting, such a person is not bound.' } },
                { verse_number: 23, sanskrit: 'गतसङ्गस्य मुक्तस्य ज्ञानावस्थितचेतसः। यज्ञायाचरतः कर्म समग्रं प्रविलीयते।।', transliteration: 'gata-sangasya muktasya jnanavasthita-chetasah', explanations: { en: 'For someone free from attachment and liberated, with mind established in knowledge, acting entirely as an offering — all their karma dissolves completely.' } },
                { verse_number: 24, sanskrit: 'ब्रह्मार्पणं ब्रह्म हविर्ब्रह्माग्नौ ब्रह्मणा हुतम्। ब्रह्मैव तेन गन्तव्यं ब्रह्मकर्मसमाधिना।।', transliteration: 'brahmarpanam brahma havir brahmagnau brahmana hutam', explanations: { en: 'The act of offering is Brahman, the offering is Brahman, poured by Brahman into the fire of Brahman — one who sees everything as Brahman reaches Brahman.' } },
                { verse_number: 25, sanskrit: 'दैवमेवापरे यज्ञं योगिनः पर्युपासते। ब्रह्माग्नावपरे यज्ञं यज्ञेनैवोपजुह्वति।।', transliteration: 'daivam evapare yajnam yoginah paryupasate', explanations: { en: 'Some yogis worship through rituals offered to the gods; others offer the act of sacrifice itself as an offering into the fire of Brahman.' } },
                { verse_number: 26, sanskrit: 'श्रोत्रादीनीन्द्रियाण्यन्ये संयमाग्निषु जुह्वति। शब्दादीन्विषयानन्य इन्द्रियाग्निषु जुह्वति।।', transliteration: 'shrotradinindriyany anye samyamagnishu juhvati', explanations: { en: 'Some offer the senses — like hearing — into the fires of restraint; others offer sense objects like sound into the fires of the senses.' } },
            ],
            questions: [{ question_text: 'Verse 24 describes everything as Brahman — the offering, the fire, the one who offers. What is the practical effect of seeing reality this way?', options: [{ text: 'It makes all actions equally meaningless', is_correct: false }, { text: 'It dissolves the sense of a separate "doer" performing actions for personal gain — when everything is seen as one reality, the ego-driven motivation behind action naturally falls away', is_correct: true }, { text: 'It means only formal rituals count as real action', is_correct: false }], explanation: 'Seeing everything as Brahman isn\'t a mental trick — it\'s a shift in how one experiences reality. When the distinction between self, act, and result collapses into unity, the grasping quality of action dissolves with it.', difficulty: 'application' }],
        },
        {
            part_number: 6,
            verse_start: 27,
            verse_end: 33,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 27, sanskrit: 'सर्वाणीन्द्रियकर्माणि प्राणकर्माणि चापरे। आत्मसंयमयोगाग्नौ जुह्वति ज्ञानदीपिते।।', transliteration: 'sarvani indriya-karmani prana-karmani cha apare', explanations: { en: 'Others offer all their sense activities and vital functions into the fire of the yoga of self-restraint, kindled by knowledge.' } },
                { verse_number: 28, sanskrit: 'द्रव्ययज्ञास्तपोयज्ञा योगयज्ञास्तथापरे। स्वाध्यायज्ञानयज्ञाश्च यतयः संशितव्रताः।।', transliteration: 'dravya-yajnas tapo-yajna yoga-yajnas tathaapare', explanations: { en: 'Some offer material gifts, some offer austerities, some offer yoga practice, and some offer self-study and knowledge — all as forms of yajna, with firm vows.' } },
                { verse_number: 29, sanskrit: 'अपाने जुह्वति प्राणं प्राणेऽपानं तथापरे। प्राणापानगती रुद्ध्वा प्राणायामपरायणाः।।', transliteration: 'apane juhvati pranam prane\'panam tathaapare', explanations: { en: 'Some devoted to breath-control offer the incoming breath into the outgoing and the outgoing into the incoming, restraining both.' } },
                { verse_number: 30, sanskrit: 'अपरे नियताहाराः प्राणान्प्राणेषु जुह्वति। सर्वेऽप्येते यज्ञविदो यज्ञक्षपितकल्मषाः।।', transliteration: 'apare niyataharah pranan pranesu juhvati', explanations: { en: 'Others, controlling their diet, offer the vital breath into the vital breath. All of these know what yajna is, and their wrongdoings are destroyed through it.' } },
                { verse_number: 31, sanskrit: 'यज्ञशिष्टामृतभुजो यान्ति ब्रह्म सनातनम्। नायं लोकोऽस्त्ययज्ञस्य कुतोऽन्यः कुरुसत्तम।।', transliteration: 'yajna-shishtamrita-bhujo yanti brahma sanatanam', explanations: { en: 'Those who taste the nectar left over from yajna reach the eternal Brahman. Even this world is not for one who performs no offering — how then the other world?' } },
                { verse_number: 32, sanskrit: 'एवं बहुविधा यज्ञा वितता ब्रह्मणो मुखे। कर्मजान्विद्धि तान्सर्वानेवं ज्ञात्वा विमोक्ष्यसे।।', transliteration: 'evam bahu-vidha yajna vitata brahmanao mukhe', explanations: { en: 'All these many kinds of yajna are spread before Brahman. Know them all as born of action — knowing this, you will be liberated.' } },
                { verse_number: 33, sanskrit: 'श्रेयान्द्रव्यमयाद्यज्ञाज्ज्ञानयज्ञः परन्तप। सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते।।', transliteration: 'shreyan dravya-mayad yajnaj jnana-yajnah parantapa', explanations: { en: 'The yajna of knowledge is superior to any material offering, Arjuna. All action in its entirety reaches its culmination in knowledge.' } },
            ],
            questions: [{ question_text: 'Why does Krishna list so many different forms of yajna — rituals, austerity, breath control, knowledge — rather than naming just one correct path?', options: [{ text: 'Because he couldn\'t decide which was best', is_correct: false }, { text: 'To show that the spirit of selfless offering can be expressed through many different practices — the common thread is the inner attitude, not the outer form', is_correct: true }, { text: 'Because different castes must follow different rituals strictly', is_correct: false }], explanation: 'The variety of yajnas listed here shows that the transformative principle isn\'t locked in one form. Whether through charity, breath work, knowledge, or ritual, what matters is the spirit of offering — releasing the grip of ego and self-interest.', difficulty: 'application' }],
        },
        {
            part_number: 7,
            verse_start: 34,
            verse_end: 38,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 34, sanskrit: 'तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया। उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः।।', transliteration: 'tad viddhi pranipatena pariprashnena sevaya', explanations: { en: 'To gain this knowledge, approach the wise with humility, sincere questions, and service — those who have seen the truth will teach you.' } },
                { verse_number: 35, sanskrit: 'यज्ज्ञात्वा न पुनर्मोहमेवं यास्यसि पाण्डव। येन भूतान्यशेषेण द्रक्ष्यस्यात्मन्यथो मयि।।', transliteration: 'yaj jnatva na punar moham evam yasyasi pandava', explanations: { en: 'Knowing this, Arjuna will not fall into delusion again, and will see all beings without exception in himself and in Krishna.' } },
                { verse_number: 36, sanskrit: 'अपि चेदसि पापेभ्यः सर्वेभ्यः पापकृत्तमः। सर्वं ज्ञानप्लवेनैव वृजिनं सन्तरिष्यसि।।', transliteration: 'api ched asi papebhyah sarvebhyah papa-krit-tamah', explanations: { en: 'Even if someone is the greatest sinner of all sinners, they will cross over all wrongdoing by the raft of knowledge.' } },
                { verse_number: 37, sanskrit: 'यथैधांसि समिद्धोऽग्निर्भस्मसात्कुरुतेऽर्जुन। ज्ञानाग्निः सर्वकर्माणि भस्मसात्कुरुते तथा।।', transliteration: 'yathaidhamsi samiddho\'gnir bhasmasat kurute\'rjuna', explanations: { en: 'Just as a blazing fire reduces wood to ashes, so the fire of knowledge reduces all karma to ashes.' } },
                { verse_number: 38, sanskrit: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते। तत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति।।', transliteration: 'na hi jnanena sadrisham pavitram iha vidyate', explanations: { en: 'There is nothing as purifying as knowledge in this world. One who is perfected in yoga finds this within the self in time.' } },
            ],
            questions: [{ question_text: 'Verse 34 describes how to approach a teacher — with humility, questions, and service. Why are all three needed, not just one?', options: [{ text: 'It\'s a formal ritual requirement with no deeper meaning', is_correct: false }, { text: 'Each quality addresses a different barrier to learning: humility removes ego, sincere questions show genuine seeking, and service demonstrates commitment — together they create the conditions for real transmission of knowledge', is_correct: true }, { text: 'Because only teachers who are served materially will share their best knowledge', is_correct: false }], explanation: 'Humility, inquiry, and service aren\'t arbitrary — they prepare the student. Ego blocks understanding; unclear questioning produces unclear answers; and service builds the trust and proximity needed for genuine teaching to happen.', difficulty: 'application' }],
        },
        {
            part_number: 8,
            verse_start: 39,
            verse_end: 42,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 39, sanskrit: 'श्रद्धावाँल्लभते ज्ञानं तत्परः संयतेन्द्रियः। ज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति।।', transliteration: 'shraddha-van labhate jnanam tat-parah samyatendriyah', explanations: { en: 'The person who has faith and is devoted to it, with senses under control, gains knowledge — and having gained it, quickly reaches supreme peace.' } },
                { verse_number: 40, sanskrit: 'अज्ञश्चाश्रद्दधानश्च संशयात्मा विनश्यति। नायं लोकोऽस्ति न परो न सुखं संशयात्मनः।।', transliteration: 'ajnash chashraddadhanash cha samshayatma vinashyati', explanations: { en: 'But the ignorant, the faithless, and the doubting self are destroyed. The doubting person finds happiness in neither this world nor the next.' } },
                { verse_number: 41, sanskrit: 'योगसंन्यस्तकर्माणं ज्ञानसञ्छिन्नसंशयम्। आत्मवन्तं न कर्माणि निबध्नन्ति धनञ्जय।।', transliteration: 'yoga-sannyasta-karmanam jnana-sanchhinna-samshayam', explanations: { en: 'Actions do not bind the person who has surrendered all action through yoga, whose doubts are cut away by knowledge, and who is established in the self.' } },
                { verse_number: 42, sanskrit: 'तस्मादज्ञानसम्भूतं हृत्स्थं ज्ञानासिनात्मनः। छित्त्वैनं संशयं योगमातिष्ठोत्तिष्ठ भारत।।', transliteration: 'tasmad ajnana-sambhutam hrit-stham jnanasina\'tmanah', explanations: { en: 'Therefore, with the sword of your own knowledge, cut away this doubt born of ignorance that lives in your heart — rise up in yoga, Arjuna.' } },
            ],
            questions: [{ question_text: 'Chapter 4 ends with Krishna telling Arjuna to cut doubt with the "sword of knowledge." What kind of doubt is Krishna referring to?', options: [{ text: 'Doubt about whether the battle plan is tactically sound', is_correct: false }, { text: 'The deep uncertainty about the self, duty, and reality that has paralyzed Arjuna — the kind of doubt that only dissolves through genuine understanding, not just reassurance', is_correct: true }, { text: 'Religious doubt about which god to pray to', is_correct: false }], explanation: 'Krishna is pointing to the root of Arjuna\'s crisis — confusion about who he is, what action means, and what the self truly is. That kind of existential doubt can\'t be resolved by argument alone; it dissolves only when the deeper truth is genuinely seen.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter4;
