// Complete Chapter 6 (Dhyana Yoga - "The Yoga of Meditation"), all 47 verses, 9 parts.

const chapter6 = {
    number: 6,
    title: 'The Yoga of Meditation',
    total_verses: 47,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 4,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 1, sanskrit: 'श्रीभगवानुवाच। अनाश्रितः कर्मफलं कार्यं कर्म करोति यः। स संन्यासी च योगी च न निरग्निर्न चाक्रियः।।', transliteration: 'shri bhagavan uvacha: anashritah karma-phalam karyam karma karoti yah', explanations: { en: 'Krishna says a true renunciant and yogi is one who does what must be done without relying on the fruit — not someone who has simply given up fire or action.' } },
                { verse_number: 2, sanskrit: 'यं संन्यासमिति प्राहुर्योगं तं विद्धि पाण्डव। न ह्यसंन्यस्तसङ्कल्पो योगी भवति कश्चन।।', transliteration: 'yam sannyasam iti prahur yogam tam viddhi pandava', explanations: { en: 'What people call renunciation is the same as yoga, Arjuna. No one becomes a yogi without giving up the will driven by selfish intention.' } },
                { verse_number: 3, sanskrit: 'आरुरुक्षोर्मुनेर्योगं कर्म कारणमुच्यते। योगारूढस्य तस्यैव शमः कारणमुच्यते।।', transliteration: 'arurukshor muner yogam karma karanam uchyate', explanations: { en: 'For a sage who is ascending toward yoga, action is the means. For one who has already attained yoga, stillness is said to be the means.' } },
                { verse_number: 4, sanskrit: 'यदा हि नेन्द्रियार्थेषु न कर्मस्वनुषज्जते। सर्वसङ्कल्पसंन्यासी योगारूढस्तदोच्यते।।', transliteration: 'yada hi nendriyartheshu na karmasv anushajjate', explanations: { en: 'When a person is attached neither to sense objects nor to actions, and has renounced all personal will — they are said to have attained yoga.' } },
            ],
            questions: [{ question_text: 'Krishna says in verse 3 that action is the means for one ascending yoga, but stillness for one who has attained it. What does this progression look like in practice?', options: [{ text: 'Beginners must work hard and advanced practitioners do nothing', is_correct: false }, { text: 'In earlier stages, disciplined action purifies and focuses the mind; once inner stability is achieved, the stillness that was being cultivated becomes natural and is itself the practice', is_correct: true }, { text: 'Only people who have quit their jobs can practice meditation properly', is_correct: false }], explanation: 'The progression from action to stillness isn\'t about doing less work — it\'s about what the practice looks like at different stages of inner development. Action disciplines the restless mind; once it\'s disciplined, the natural state of stillness can be dwelt in directly.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 5,
            verse_end: 9,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 5, sanskrit: 'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्। आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः।।', transliteration: 'uddhared atmanatmanam natmanam avasadayet', explanations: { en: 'One should elevate oneself by the self and not degrade the self — the self alone is the friend of the self, and the self alone is the enemy of the self.' } },
                { verse_number: 6, sanskrit: 'बन्धुरात्मात्मनस्तस्य येनात्मैवात्मना जितः। अनात्मनस्तु शत्रुत्वे वर्तेतात्मैव शत्रुवत्।।', transliteration: 'bandhur atmatmanas tasya yenatmaivat mana jitah', explanations: { en: 'The self is a friend to the person who has conquered the self by the self. But for one who has not, the self acts as an enemy.' } },
                { verse_number: 7, sanskrit: 'जितात्मनः प्रशान्तस्य परमात्मा समाहितः। शीतोष्णसुखदुःखेषु तथा मानापमानयोः।।', transliteration: 'jitatmanah prashantasya paramatma samahitah', explanations: { en: 'For one who has conquered the self and is at peace, the Supreme Self is steadily present — in cold and heat, pleasure and pain, honor and dishonor alike.' } },
                { verse_number: 8, sanskrit: 'ज्ञानविज्ञानतृप्तात्मा कूटस्थो विजितेन्द्रियः। युक्त इत्युच्यते योगी समलोष्टाश्मकाञ्चनः।।', transliteration: 'jnana-vijnana-triptatma kutastho vijitendriyah', explanations: { en: 'The yogi whose self is satisfied with knowledge and realized wisdom, who is established and whose senses are controlled, who sees a clod of earth, a stone, and gold as equal — is called absorbed in yoga.' } },
                { verse_number: 9, sanskrit: 'सुहृन्मित्रार्युदासीनमध्यस्थद्वेष्यबन्धुषु। साधुष्वपि च पापेषु समबुद्धिर्विशिष्यते।।', transliteration: 'suhrin-mitrary-udasina-madhyastha-dveshya-bandhushu', explanations: { en: 'One who has equal-minded understanding toward well-wishers, friends, enemies, the neutral, the mediators, the hateful, relatives, the good and the sinful — is distinguished.' } },
            ],
            questions: [{ question_text: 'What does Krishna mean when he says the self is both friend and enemy of the self (verses 5-6)?', options: [{ text: 'That people have split personalities', is_correct: false }, { text: 'That the same mind can either help or harm you depending on whether it has been trained and disciplined — an untrained mind is your worst enemy; a disciplined one is your greatest ally', is_correct: true }, { text: 'That one should distrust other people and rely only on themselves', is_correct: false }], explanation: 'This is one of the Gita\'s most empowering statements: your own liberation or bondage depends entirely on the quality of your inner life. No external force determines this — it\'s the relationship between the disciplined and undisciplined aspects of the same mind.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 10,
            verse_end: 15,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 10, sanskrit: 'योगी युञ्जीत सततमात्मानं रहसि स्थितः। एकाकी यतचित्तात्मा निराशीरपरिग्रहः।।', transliteration: 'yogi yunjita satatam atmanam rahasi sthitah', explanations: { en: 'The yogi should constantly engage the self in meditation, alone in a secluded place, with mind and self controlled, free from desire and possessiveness.' } },
                { verse_number: 11, sanskrit: 'शुचौ देशे प्रतिष्ठाप्य स्थिरमासनमात्मनः। नात्युच्छ्रितं नातिनीचं चैलाजिनकुशोत्तरम्।।', transliteration: 'shuchau deshe pratishthaapya sthiram asanam atmanah', explanations: { en: 'In a clean place, establishing a steady seat — neither too high nor too low — with cloth, deerskin, and kusha grass layered together...' } },
                { verse_number: 12, sanskrit: 'तत्रैकाग्रं मनः कृत्वा यतचित्तेन्द्रियक्रियः। उपविश्यासने युञ्ज्याद्योगमात्मविशुद्धये।।', transliteration: 'tatraikagram manah kritva yata-chittendriya-kriyah', explanations: { en: '...sitting there, making the mind one-pointed, with thought and sense activity controlled, one should practice yoga for purification of the self.' } },
                { verse_number: 13, sanskrit: 'समं कायशिरोग्रीवं धारयन्नचलं स्थिरः। सम्प्रेक्ष्य नासिकाग्रं स्वं दिशश्चानवलोकयन्।।', transliteration: 'samam kaya-shiro-grivam dharayann achalam sthirah', explanations: { en: 'Holding body, head, and neck erect and still, steady, gazing at the tip of the nose, not looking in any direction...' } },
                { verse_number: 14, sanskrit: 'प्रशान्तात्मा विगतभीर्ब्रह्मचारिव्रते स्थितः। मनः संयम्य मच्चित्तो युक्त आसीत मत्परः।।', transliteration: 'prashant-atma vigata-bhir brahmachari-vrate sthitah', explanations: { en: '...with a peaceful self, free from fear, established in the vow of brahmacharya, controlling the mind, with thoughts on Krishna, seated, devoted to him.' } },
                { verse_number: 15, sanskrit: 'युञ्जन्नेवं सदात्मानं योगी नियतमानसः। शान्तिं निर्वाणपरमां मत्संस्थामधिगच्छति।।', transliteration: 'yunjan evam sada\'tmanam yogi niyata-manasah', explanations: { en: 'Constantly engaging the self in this way, the yogi with a controlled mind reaches the peace that rests in Krishna — the supreme nirvana.' } },
            ],
            questions: [{ question_text: 'Krishna gives very specific instructions for meditation posture and environment. Why do these external details matter?', options: [{ text: 'Because the specific geometry of sitting is magically powerful', is_correct: false }, { text: 'Because the body, breath, and environment influence the mind — a stable, upright posture and a quiet space reduce the obstacles to concentration and create conditions where meditation can actually happen', is_correct: true }, { text: 'Because one can only meditate in perfect conditions', is_correct: false }], explanation: 'The instructions aren\'t arbitrary ritual — they reflect an understanding that the outer conditions support inner practice. A stable body stabilizes the mind; a distraction-free environment makes concentration easier. These are practical aids, not prerequisites for being "spiritual."', difficulty: 'application' }],
        },
        {
            part_number: 4,
            verse_start: 16,
            verse_end: 20,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 16, sanskrit: 'नात्यश्नतस्तु योगोऽस्ति न चैकान्तमनश्नतः। न चाति स्वप्नशीलस्य जाग्रतो नैव चार्जुन।।', transliteration: 'natyashnatas tu yogo\'sti na chaikantam anashnatah', explanations: { en: 'Yoga is not for one who overeats or does not eat at all, nor for one who sleeps too much or stays awake excessively, Arjuna.' } },
                { verse_number: 17, sanskrit: 'युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु। युक्तस्वप्नावबोधस्य योगो भवति दुःखहा।।', transliteration: 'yukta-ahara-viharasya yukta-cheshtasya karmasu', explanations: { en: 'For one who is balanced in eating and recreation, balanced in action, balanced in sleep and waking — yoga becomes the destroyer of suffering.' } },
                { verse_number: 18, sanskrit: 'यदा विनियतं चित्तमात्मन्येवावतिष्ठते। निःस्पृहः सर्वकामेभ्यो युक्त इत्युच्यते तदा।।', transliteration: 'yada viniyatam chittam atmany evavatishtate', explanations: { en: 'When the fully controlled mind rests only in the self, free from longing for all desires — then it is said to be absorbed in yoga.' } },
                { verse_number: 19, sanskrit: 'यथा दीपो निवातस्थो नेङ्गते सोपमा स्मृता। योगिनो यतचित्तस्य युञ्जतो योगमात्मनः।।', transliteration: 'yatha dipo nivata-stho nenggate sopama smrita', explanations: { en: 'As a lamp in a windless place does not flicker — that is the image used for the yogi of controlled mind practicing yoga of the self.' } },
                { verse_number: 20, sanskrit: 'यत्रोपरमते चित्तं निरुद्धं योगसेवया। यत्र चैवात्मनात्मानं पश्यन्नात्मनि तुष्यति।।', transliteration: 'yatroparamate chittam niruddham yoga-sevaya', explanations: { en: 'When the mind restrained by yoga practice comes to rest, when seeing the self by the self one is satisfied in the self...' } },
            ],
            questions: [{ question_text: 'What is the significance of the "lamp in a windless place" image for meditation?', options: [{ text: 'That meditation makes you motionless like an object', is_correct: false }, { text: 'That a properly meditative mind is present and aware but not flickering between distractions — stable without being rigid, like a flame that burns clearly rather than sputtering', is_correct: true }, { text: 'That meditation should only happen indoors', is_correct: false }], explanation: 'The lamp image captures something precise about meditative awareness — it\'s not blankness or unconsciousness, but a quality of steady, clear presence that isn\'t blown about by every passing thought or sensation.', difficulty: 'application' }],
        },
        {
            part_number: 5,
            verse_start: 21,
            verse_end: 27,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 21, sanskrit: 'सुखमात्यन्तिकं यत्तद्बुद्धिग्राह्यमतीन्द्रियम्। वेत्ति यत्र न चैवायं स्थितश्चलति तत्त्वतः।।', transliteration: 'sukham atyantikam yat tad buddhi-grahyam atindriyam', explanations: { en: '...where one knows that absolute happiness grasped by the intellect beyond the senses, and established there, does not move from truth...' } },
                { verse_number: 22, sanskrit: 'यं लब्ध्वा चापरं लाभं मन्यते नाधिकं ततः। यस्मिन्स्थितो न दुःखेन गुरुणापि विचाल्यते।।', transliteration: 'yam labdhva chaparam labham manyate nadhikam tatah', explanations: { en: '...having gained which, one thinks there is no greater gain, and established in which, one is not moved even by the greatest suffering...' } },
                { verse_number: 23, sanskrit: 'तं विद्याद्दुःखसंयोगवियोगं योगसञ्ज्ञितम्। स निश्चयेन योक्तव्यो योगोऽनिर्विण्णचेतसा।।', transliteration: 'tam vidyad duhkha-samyoga-viyogam yoga-sanjnitam', explanations: { en: '...that state, the disconnection from union with suffering, should be known as yoga. This yoga should be practiced with determination and with an unwearied mind.' } },
                { verse_number: 24, sanskrit: 'सङ्कल्पप्रभवान्कामांस्त्यक्त्वा सर्वानशेषतः। मनसैवेन्द्रियग्रामं विनियम्य समन्ततः।।', transliteration: 'sankalpa-prabhavan kaman tyaktva sarvan asheshatah', explanations: { en: 'Abandoning without exception all desires born of will, restraining the group of senses on all sides by the mind alone...' } },
                { verse_number: 25, sanskrit: 'शनैः शनैरुपरमेद्बुद्ध्या धृतिगृहीतया। आत्मसंस्थं मनः कृत्वा न किञ्चिदपि चिन्तयेत्।।', transliteration: 'shanaih shanaih uparamed buddhya dhritigrahitaya', explanations: { en: '...little by little, let one come to rest, with the intellect held by steadiness; having made the mind established in the self, one should think of nothing at all.' } },
                { verse_number: 26, sanskrit: 'यतो यतो निश्चलति मनश्चञ्चलमस्थिरम्। ततस्ततो नियम्यैतदात्मन्येव वशं नयेत्।।', transliteration: 'yato yato nishchalati manash chanchalamm asthiram', explanations: { en: 'Wherever the restless, unsteady mind wanders — from there, bringing it back, one should bring it under the sway of the self alone.' } },
                { verse_number: 27, sanskrit: 'प्रशान्तमनसं ह्येनं योगिनं सुखमुत्तमम्। उपैति शान्तरजसं ब्रह्मभूतमकल्मषम्।।', transliteration: 'prashanta-manasam hy enam yoginam sukham uttamam', explanations: { en: 'Supreme happiness comes to this yogi whose mind is truly peaceful, whose passion is stilled, who has become Brahman, and is without impurity.' } },
            ],
            questions: [{ question_text: 'Verse 26 says when the mind wanders, just bring it back — again and again. What does this tell us about how meditation actually works?', options: [{ text: 'That you\'re failing if your mind wanders at all', is_correct: false }, { text: 'That the practice of meditation IS the act of repeatedly noticing the mind has wandered and returning it — this isn\'t a sign of failure but the actual exercise, like a rep in physical training', is_correct: true }, { text: 'That only naturally calm people can meditate', is_correct: false }], explanation: 'This verse is often a relief to beginners: Krishna doesn\'t say "keep the mind still." He says when it wanders, bring it back. The return is the practice. Minds wander — this is normal. What matters is the quality of the return.', difficulty: 'application' }],
        },
        {
            part_number: 6,
            verse_start: 28,
            verse_end: 32,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 28, sanskrit: 'युञ्जन्नेवं सदात्मानं योगी विगतकल्मषः। सुखेन ब्रह्मसंस्पर्शमत्यन्तं सुखमश्नुते।।', transliteration: 'yunjan evam sada\'tmanam yogi vigata-kalmashah', explanations: { en: 'The yogi who constantly engages the self in this way, freed from impurities, easily experiences the touch of Brahman — supreme happiness.' } },
                { verse_number: 29, sanskrit: 'सर्वभूतस्थमात्मानं सर्वभूतानि चात्मनि। ईक्षते योगयुक्तात्मा सर्वत्र समदर्शनः।।', transliteration: 'sarva-bhuta-stham atmanam sarva-bhutani chatmani', explanations: { en: 'With the self established in yoga, seeing the self in all beings and all beings in the self — the yogi sees everywhere with equal vision.' } },
                { verse_number: 30, sanskrit: 'यो मां पश्यति सर्वत्र सर्वं च मयि पश्यति। तस्याहं न प्रणश्यामि स च मे न प्रणश्यति।।', transliteration: 'yo mam pashyati sarvatra sarvam cha mayi pashyati', explanations: { en: 'For one who sees Krishna everywhere and sees everything in Krishna — he is never lost to that person, nor is that person ever lost to him.' } },
                { verse_number: 31, sanskrit: 'सर्वभूतस्थितं यो मां भजत्येकत्वमास्थितः। सर्वथा वर्तमानोऽपि स योगी मयि वर्तते।।', transliteration: 'sarva-bhuta-sthitam yo mam bhajaty ekatvam asthitah', explanations: { en: 'The yogi who worships Krishna abiding in all beings, established in unity — that yogi lives in Krishna whatever way they live.' } },
                { verse_number: 32, sanskrit: 'आत्मौपम्येन सर्वत्र समं पश्यति योऽर्जुन। सुखं वा यदि वा दुःखं स योगी परमो मतः।।', transliteration: 'atmaupamyena sarvatra samam pashyati yo\'rjuna', explanations: { en: 'One who sees everywhere as equal — by comparison with the self — whether in pleasure or pain, Arjuna, is considered the supreme yogi.' } },
            ],
            questions: [{ question_text: 'Verse 32 says the supreme yogi sees others\' pleasure and pain as equal to their own. What does this mean in practice?', options: [{ text: 'That enlightened people feel nothing for others\' suffering', is_correct: false }, { text: 'That one develops genuine empathy — using one\'s own experience of pleasure and pain as a reference point to understand others\', rather than being indifferent to their experience', is_correct: true }, { text: 'That all experiences are identical and nothing matters', is_correct: false }], explanation: 'This is empathy in its deepest form, not indifference. By seeing others through the lens of your own experience — knowing how pain feels, how pleasure feels — you develop a natural responsiveness to others without the distortion of ego-driven comparison.', difficulty: 'application' }],
        },
        {
            part_number: 7,
            verse_start: 33,
            verse_end: 36,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 33, sanskrit: 'अर्जुन उवाच। योऽयं योगस्त्वया प्रोक्तः साम्येन मधुसूदन। एतस्याहं न पश्यामि चञ्चलत्वात्स्थितिं स्थिराम्।।', transliteration: 'arjuna uvacha: yo\'yam yogas tvaya proktah samyena madhusudana', explanations: { en: 'Arjuna objects: this yoga of equanimity you describe — he can\'t see how it can be sustained, because the mind is restless.' } },
                { verse_number: 34, sanskrit: 'चञ्चलं हि मनः कृष्ण प्रमाथि बलवद्दृढम्। तस्याहं निग्रहं मन्ये वायोरिव सुदुष्करम्।।', transliteration: 'chanchalamm hi manah krishna pramathi balavad dridham', explanations: { en: 'The mind is restless, Krishna — violent, powerful, and obstinate. I think controlling it is as difficult as controlling the wind.' } },
                { verse_number: 35, sanskrit: 'श्रीभगवानुवाच। असंशयं महाबाहो मनो दुर्निग्रहं चलम्। अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते।।', transliteration: 'shri bhagavan uvacha: asamshayam maha-baho mano durnigraham chalam', explanations: { en: 'Krishna agrees without doubt — the mind is hard to control and restless. But it is restrained by practice and non-attachment, Arjuna.' } },
                { verse_number: 36, sanskrit: 'असंयतात्मना योगो दुष्प्राप इति मे मतिः। वश्यात्मना तु यतता शक्योऽवाप्तुमुपायतः।।', transliteration: 'asamyatatmana yogo dushpraapa iti me matih', explanations: { en: 'For one with an uncontrolled self, yoga is difficult to attain — this is my view. But for one who strives with a disciplined self, it can be attained through proper means.' } },
            ],
            questions: [{ question_text: 'Arjuna says controlling the mind is like controlling the wind. How does Krishna\'s answer reframe this challenge?', options: [{ text: 'He denies that the mind is hard to control', is_correct: false }, { text: 'He agrees it\'s difficult, but offers a practical path — practice and non-attachment — rather than saying it\'s impossible or requires superhuman will', is_correct: true }, { text: 'He tells Arjuna to just try harder', is_correct: false }], explanation: 'Krishna\'s response is validating and practical: yes, the mind is restless (he doesn\'t dismiss Arjuna\'s experience), but the solution isn\'t pure willpower — it\'s the gradual cultivation of practice (abhyasa) and releasing grip on outcomes (vairagya).', difficulty: 'application' }],
        },
        {
            part_number: 8,
            verse_start: 37,
            verse_end: 45,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 37, sanskrit: 'अर्जुन उवाच। अयतिः श्रद्धयोपेतो योगाच्चलितमानसः। अप्राप्य योगसंसिद्धिं कां गतिं कृष्ण गच्छति।।', transliteration: 'arjuna uvacha: ayatih shraddhayopeto yogach chalita-manasah', explanations: { en: 'Arjuna asks: what happens to the sincere person who starts yoga practice but whose mind wanders — who doesn\'t reach perfection in yoga? Where do they go?' } },
                { verse_number: 38, sanskrit: 'कच्चिन्नोभयविभ्रष्टश्छिन्नाभ्रमिव नश्यति। अप्रतिष्ठो महाबाहो विमूढो ब्रह्मणः पथि।।', transliteration: 'kachchin nobhaya-vibhrashtash chinnabhram iva nashyati', explanations: { en: 'Does such a person fall from both paths — like a cloud split apart — and perish without support, confused on the path to Brahman?' } },
                { verse_number: 39, sanskrit: 'एतन्मे संशयं कृष्ण छेत्तुमर्हस्यशेषतः। त्वदन्यः संशयस्यास्य छेत्ता न ह्युपपद्यते।।', transliteration: 'etan me samshayam krishna chhettum arhasy asheshatah', explanations: { en: 'Please cut away this doubt completely, Krishna. No one other than you is fit to dispel this doubt.' } },
                { verse_number: 40, sanskrit: 'श्रीभगवानुवाच। पार्थ नैवेह नामुत्र विनाशस्तस्य विद्यते। न हि कल्याणकृत्कश्चिद्दुर्गतिं तात गच्छति।।', transliteration: 'shri bhagavan uvacha: partha naiveha namutra vinashas tasya vidyate', explanations: { en: 'Krishna answers: such a person is not destroyed, either here or hereafter. No one who does good, dear one, ever comes to a bad end.' } },
                { verse_number: 41, sanskrit: 'प्राप्य पुण्यकृतां लोकानुषित्वा शाश्वतीः समाः। शुचीनां श्रीमतां गेहे योगभ्रष्टोऽभिजायते।।', transliteration: 'prapya punya-kritam lokan ushitva shashvati samah', explanations: { en: 'The one who fell from yoga attains the worlds of the righteous, dwells there for immeasurable years, and is then born into the home of the pure and prosperous.' } },
                { verse_number: 42, sanskrit: 'अथवा योगिनामेव कुले भवति धीमताम्। एतद्धि दुर्लभतरं लोके जन्म यदीदृशम्।।', transliteration: 'athava yoginam eva kule bhavati dhimatam', explanations: { en: 'Or they may be born into a family of wise yogis — such a birth is indeed very rare in this world.' } },
                { verse_number: 43, sanskrit: 'तत्र तं बुद्धिसंयोगं लभते पौर्वदेहिकम्। यतते च ततो भूयः संसिद्धौ कुरुनन्दन।।', transliteration: 'tatra tam buddhi-samyogam labhate paurva-dehikam', explanations: { en: 'There, that person regains the intellectual connection from the previous body, and strives again for perfection.' } },
                { verse_number: 44, sanskrit: 'पूर्वाभ्यासेन तेनैव ह्रियते ह्यवशोऽपि सः। जिज्ञासुरपि योगस्य शब्दब्रह्मातिवर्तते।।', transliteration: 'purva-abhyasena tenaiva hriyate hy avasho\'pi sah', explanations: { en: 'Even without effort, that previous practice carries them forward involuntarily. Even the sincere seeker of yoga goes beyond the scriptural path.' } },
                { verse_number: 45, sanskrit: 'प्रयत्नाद्यतमानस्तु योगी संशुद्धकिल्बिषः। अनेकजन्मसंसिद्धस्ततो याति परां गतिम्।।', transliteration: 'prayatnad yatamanas tu yogi samshuddhha-kilbishah', explanations: { en: 'The yogi who strives earnestly, purified from impurities, perfected over many births, then goes to the supreme destination.' } },
            ],
            questions: [{ question_text: 'What is comforting about Krishna\'s answer to Arjuna\'s question about the person who falls short of yoga perfection?', options: [{ text: 'That they won\'t have to practice anymore in future lives', is_correct: false }, { text: 'That sincere spiritual effort is never wasted — even if this life ends before the goal is reached, the momentum carries forward, and the journey continues from where it left off', is_correct: true }, { text: 'That everyone automatically reaches the goal regardless of effort', is_correct: false }], explanation: 'This is one of the most reassuring passages in the Gita. The spiritual path isn\'t a one-shot deal where failure means total loss. Genuine effort accumulates across time and births — the sincere seeker is never truly left behind.', difficulty: 'application' }],
        },
        {
            part_number: 9,
            verse_start: 46,
            verse_end: 47,
            estimated_minutes: 2.5,
            verses: [
                { verse_number: 46, sanskrit: 'तपस्विभ्योऽधिको योगी ज्ञानिभ्योऽपि मतोऽधिकः। कर्मिभ्यश्चाधिको योगी तस्माद्योगी भवार्जुन।।', transliteration: 'tapasvibhyo\'dhiko yogi jnanibhyo\'pi mato\'dhikah', explanations: { en: 'The yogi is superior to ascetics, considered superior even to the knowledgeable, and superior to those absorbed in ritual action. Therefore, Arjuna, become a yogi.' } },
                { verse_number: 47, sanskrit: 'योगिनामपि सर्वेषां मद्गतेनान्तरात्मना। श्रद्धावान्भजते यो मां स मे युक्ततमो मतः।।', transliteration: 'yoginam api sarvesham mad-gatenantaratmana', explanations: { en: 'And among all yogis, the one who worships Krishna with faith, with their innermost self gone into Krishna — that person is considered by Krishna to be the most absorbed in yoga.' } },
            ],
            questions: [{ question_text: 'Chapter 6 ends by saying the highest yogi is the one whose inner self rests in Krishna with faith. How does this connect the entire chapter on meditation?', options: [{ text: 'It suddenly shifts the whole chapter to only mean formal worship rituals', is_correct: false }, { text: 'It brings the technical meditation instructions to their heart: all the posture, breath, and concentration work points toward a quality of inner devotion and surrender — that devotional quality is what makes the practice complete', is_correct: true }, { text: 'It means that yoga and devotion are completely separate practices', is_correct: false }], explanation: 'The chapter\'s closing verse is a integration point: the detailed meditation practice isn\'t an end in itself, but a vehicle for cultivating the deep inner trust and devotion described here. Technical mastery without that devotional heart is incomplete.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter6;
