// Complete Chapter 10 (Vibhuti Yoga - "The Yoga of Divine Manifestations"), all 42 verses, 7 parts.

const chapter10 = {
    number: 10,
    title: 'The Yoga of Divine Manifestations',
    total_verses: 42,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 7,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 1, sanskrit: 'श्रीभगवानुवाच। भूय एव महाबाहो शृणु मे परमं वचः। यत्तेऽहं प्रीयमाणाय वक्ष्यामि हितकाम्यया।।', transliteration: 'shri bhagavan uvacha: bhuya eva maha-baho shrinu me paramam vachas', explanations: { en: 'Krishna says he will speak again — the highest words — to Arjuna who is dear to him, out of his wish for Arjuna\'s wellbeing.' } },
                { verse_number: 2, sanskrit: 'न मे विदुः सुरगणाः प्रभवं न महर्षयः। अहमादिर्हि देवानां महर्षीणां च सर्वशः।।', transliteration: 'na me viduh sura-ganah prabhavam na maharshayah', explanations: { en: 'Neither the hosts of gods nor the great sages know Krishna\'s origin — for he is the source of gods and great sages in every way.' } },
                { verse_number: 3, sanskrit: 'यो मामजमनादिं च वेत्ति लोकमहेश्वरम्। असम्मूढः स मर्त्येषु सर्वपापैः प्रमुच्यते।।', transliteration: 'yo mam ajam anadim cha vetti loka-maheshvaram', explanations: { en: 'Whoever knows Krishna as unborn and beginningless, the great Lord of the worlds — undeluded among mortals — is freed from all wrongs.' } },
                { verse_number: 4, sanskrit: 'बुद्धिर्ज्ञानमसम्मोहः क्षमा सत्यं दमः शमः। सुखं दुःखं भवोऽभावो भयं चाभयमेव च।।', transliteration: 'buddhir jnanam asammohah kshama satyam damah shamah', explanations: { en: 'Intellect, knowledge, clarity, patience, truth, self-control, calmness, pleasure, pain, existence, non-existence, fear, and fearlessness...' } },
                { verse_number: 5, sanskrit: 'अहिंसा समता तुष्टिस्तपो दानं यशोऽयशः। भवन्ति भावा भूतानां मत्त एव पृथग्विधाः।।', transliteration: 'ahimsa samata tushtis tapo danam yasho\'yashah', explanations: { en: '...non-violence, equanimity, contentment, austerity, generosity, fame, and dishonor — all the various states of beings arise from Krishna alone.' } },
                { verse_number: 6, sanskrit: 'महर्षयः सप्त पूर्वे चत्वारो मनवस्तथा। मद्भावा मानसा जाता येषां लोक इमाः प्रजाः।।', transliteration: 'maharshayah sapta purve chatvaro manavas tatha', explanations: { en: 'The seven great ancient sages and the four Manus, endowed with Krishna\'s nature, born of his mind — from them these creatures of the world have descended.' } },
                { verse_number: 7, sanskrit: 'एतां विभूतिं योगं च मम यो वेत्ति तत्त्वतः। सोऽविकम्पेन योगेन युज्यते नात्र संशयः।।', transliteration: 'etam vibhutim yogam cha mama yo vetti tattvatah', explanations: { en: 'Whoever knows in truth this divine glory and power of Krishna — is united with Krishna through unwavering yoga. There is no doubt about this.' } },
            ],
            questions: [{ question_text: 'Krishna says even the gods don\'t know his true origin. What is the significance of this for a human seeker?', options: [{ text: 'It means the truth is unknowable so one shouldn\'t bother', is_correct: false }, { text: 'It establishes that intellectual or cosmological knowledge alone can\'t reach what is being pointed at — it requires a different mode of knowing, one rooted in direct devotion and experience', is_correct: true }, { text: 'It means only special people can ever understand', is_correct: false }], explanation: 'If gods with divine intellect don\'t know Krishna\'s origin through their own faculties, this tells the seeker that the usual methods of knowing are insufficient. The Gita consistently points beyond conceptual understanding toward a direct, devotional knowing.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 8,
            verse_end: 11,
            estimated_minutes: 3.5,
            verses: [
                { verse_number: 8, sanskrit: 'अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते। इति मत्वा भजन्ते मां बुधा भावसमन्विताः।।', transliteration: 'aham sarvasya prabhavo mattah sarvam pravartate', explanations: { en: 'Krishna is the source of everything — everything flows from him. Knowing this, the wise worship him full of devotion.' } },
                { verse_number: 9, sanskrit: 'मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम्। कथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च।।', transliteration: 'mac-chitta mad-gata-prana bodhayantah parasparam', explanations: { en: 'With minds fixed on him, lives given to him, enlightening each other, always speaking of him — they are content and rejoice.' } },
                { verse_number: 10, sanskrit: 'तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम्। ददामि बुद्धियोगं तं येन मामुपयान्ति ते।।', transliteration: 'tesham satata-yuktanam bhajatam priti-purvakam', explanations: { en: 'To those who are constantly devoted and worship with love, Krishna gives the yoga of intelligence by which they come to him.' } },
                { verse_number: 11, sanskrit: 'तेषामेवानुकम्पार्थमहमज्ञानजं तमः। नाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता।।', transliteration: 'tesham evanukaamparthama ham ajnana-jam tamah', explanations: { en: 'Out of compassion for them, dwelling in their own being, Krishna destroys the darkness born of ignorance with the shining lamp of knowledge.' } },
            ],
            questions: [{ question_text: 'Verse 11 says Krishna destroys ignorance from within — "dwelling in their own being." What does this mean about how spiritual illumination actually happens?', options: [{ text: 'That God externally intervenes to remove ignorance from chosen people', is_correct: false }, { text: 'That the source of liberation is already within — Krishna, as the indwelling Self, is the light that dispels ignorance from inside, not an external agent operating from outside', is_correct: true }, { text: 'That one must constantly pray for God to enter from outside', is_correct: false }], explanation: 'This is a profound statement: the divine presence that illumines the devotee isn\'t something imported from outside but is the deepest aspect of the devotee\'s own being. This is why devotion and self-knowledge ultimately converge — knowing the Self is knowing the divine.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 12,
            verse_end: 18,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 12, sanskrit: 'अर्जुन उवाच। परं ब्रह्म परं धाम पवित्रं परमं भवान्। पुरुषं शाश्वतं दिव्यमादिदेवमजं विभुम्।।', transliteration: 'arjuna uvacha: param brahma param dhama pavitram paramam bhavan', explanations: { en: 'Arjuna declares: Krishna is the supreme Brahman, the supreme abode, the supreme purifier — the eternal, divine, primal God, unborn, all-pervading.' } },
                { verse_number: 13, sanskrit: 'आहुस्त्वामृषयः सर्वे देवर्षिर्नारदस्तथा। असितो देवलो व्यासः स्वयं चैव ब्रवीषि मे।।', transliteration: 'ahus tvam rishayah sarve devarshir naradas tatha', explanations: { en: 'All the sages say this of you, as does the divine sage Narada, Asita, Devala, Vyasa — and you yourself are telling me.' } },
                { verse_number: 14, sanskrit: 'सर्वमेतदृतं मन्ये यन्मां वदसि केशव। न हि ते भगवन्व्यक्तिं विदुर्देवा न दानवाः।।', transliteration: 'sarvam etad ritam manye yan mam vadasi keshava', explanations: { en: 'Arjuna says he accepts all that Krishna has said as true. Neither gods nor demons know Krishna\'s full manifestation.' } },
                { verse_number: 15, sanskrit: 'स्वयमेवात्मनात्मानं वेत्थ त्वं पुरुषोत्तम। भूतभावन भूतेश देवदेव जगत्पते।।', transliteration: 'svayam evatmanatmanam vettha tvam purushottama', explanations: { en: 'You alone know yourself by your own self, O Highest Person, source of beings, Lord of beings, God of gods, Lord of the world.' } },
                { verse_number: 16, sanskrit: 'वक्तुमर्हस्यशेषेण दिव्या ह्यात्मविभूतयः। याभिर्विभूतिभिर्लोकानिमांस्त्वं व्याप्य तिष्ठसि।।', transliteration: 'vaktum arhasy asheshena divya hy atma-vibhutayah', explanations: { en: 'Arjuna asks Krishna to tell him fully of his divine manifestations — by which he pervades and dwells in all these worlds.' } },
                { verse_number: 17, sanskrit: 'कथं विद्यामहं योगिंस्त्वां सदा परिचिन्तयन्। केषु केषु च भावेषु चिन्त्योऽसि भगवन्मया।।', transliteration: 'katham vidyam aham yogims tvam sada parichintayan', explanations: { en: 'How should Arjuna know and always contemplate Krishna? In which of all the states of being should he think of Krishna?' } },
                { verse_number: 18, sanskrit: 'विस्तरेणात्मनो योगं विभूतिं च जनार्दन। भूयः कथय तृप्तिर्हि शृण्वतो नास्ति मेऽमृतम्।।', transliteration: 'vistarenatmano yogam vibhutim cha janardana', explanations: { en: 'Tell him again in full about his power and divine manifestations — listening to this nectar, Arjuna is never satisfied.' } },
            ],
            questions: [{ question_text: 'Arjuna says he is never satisfied hearing about Krishna\'s nature and asks for more (verse 18). What does this tell us about devotion?', options: [{ text: 'That Arjuna is being repetitive and indecisive', is_correct: false }, { text: 'Genuine devotion is not transactional — it doesn\'t reach a point of "enough." The desire to know and be near the beloved deepens with each encounter rather than being satisfied and exhausted', is_correct: true }, { text: 'That the teachings are unclear and need constant repetition', is_correct: false }], explanation: 'This moment in the dialogue reveals the nature of bhakti: the devotee\'s longing doesn\'t decrease with receiving — it deepens. This is very different from desire for an object, which diminishes once obtained. Devotion to the infinite grows with each taste.', difficulty: 'application' }],
        },
        {
            part_number: 4,
            verse_start: 19,
            verse_end: 26,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 19, sanskrit: 'श्रीभगवानुवाच। हन्त ते कथयिष्यामि दिव्या ह्यात्मविभूतयः। प्राधान्यतः कुरुश्रेष्ठ नास्त्यन्तो विस्तरस्य मे।।', transliteration: 'shri bhagavan uvacha: hanta te kathayishyami divya hy atma-vibhutayah', explanations: { en: 'Krishna says he will tell Arjuna the principal divine manifestations — there is no end to his divine extent.' } },
                { verse_number: 20, sanskrit: 'अहमात्मा गुडाकेश सर्वभूताशयस्थितः। अहमादिश्च मध्यं च भूतानामन्त एव च।।', transliteration: 'aham atma gudakesha sarva-bhutashaya-sthitah', explanations: { en: 'Krishna is the Self dwelling in the heart of all beings. He is the beginning, the middle, and the end of all beings.' } },
                { verse_number: 21, sanskrit: 'आदित्यानामहं विष्णुर्ज्योतिषां रविरंशुमान्। मरीचिर्मरुतामस्मि नक्षत्राणामहं शशी।।', transliteration: 'adityanam aham vishnur jyotisham ravir amsuman', explanations: { en: 'Among the Adityas he is Vishnu; among luminaries, the radiant sun; among the Maruts, Marichi; among stars, the moon.' } },
                { verse_number: 22, sanskrit: 'वेदानां सामवेदोऽस्मि देवानामस्मि वासवः। इन्द्रियाणां मनश्चास्मि भूतानामस्मि चेतना।।', transliteration: 'vedanam sama-vedo\'smi devanam asmi vasavah', explanations: { en: 'Among the Vedas he is the Sama Veda; among the gods, Indra; among the senses, the mind; among beings, consciousness.' } },
                { verse_number: 23, sanskrit: 'रुद्राणां शङ्करश्चास्मि वित्तेशो यक्षरक्षसाम्। वसूनां पावकश्चास्मि मेरुः शिखरिणामहम्।।', transliteration: 'rudranam shankarash chasmi vittesho yaksha-rakshasam', explanations: { en: 'Among the Rudras, Shankara; among the Yakshas and Rakshasas, the Lord of wealth; among the Vasus, fire; among mountains, Mount Meru.' } },
                { verse_number: 24, sanskrit: 'पुरोधसां च मुख्यं मां विद्धि पार्थ बृहस्पतिम्। सेनानीनामहं स्कन्दः सरसामस्मि सागरः।।', transliteration: 'purodhasam cha mukhyam mam viddhi partha brihaspatim', explanations: { en: 'Among priests he is Brihaspati; among war-leaders, Skanda; among bodies of water, the ocean.' } },
                { verse_number: 25, sanskrit: 'महर्षीणां भृगुरहं गिरामस्म्येकमक्षरम्। यज्ञानां जपयज्ञोऽस्मि स्थावराणां हिमालयः।।', transliteration: 'maharshiham bhrugur aham giram asmy ekam aksharam', explanations: { en: 'Among great sages, Bhrigu; among words, the single syllable Om; among sacrifices, the sacrifice of silent repetition; among immovable things, the Himalayas.' } },
                { verse_number: 26, sanskrit: 'अश्वत्थः सर्ववृक्षाणां देवर्षीणां च नारदः। गन्धर्वाणां चित्ररथः सिद्धानां कपिलो मुनिः।।', transliteration: 'ashvatthah sarva-vriskshanam devarshiham cha naradah', explanations: { en: 'Among all trees, the Ashvattha (sacred fig); among divine sages, Narada; among the Gandharvas, Chitraratha; among siddhas, the sage Kapila.' } },
            ],
            questions: [{ question_text: 'Why does Krishna list himself as the best of every category — best mountain, best river, best sage — rather than just claiming to be everything?', options: [{ text: 'To show off his superiority over all other things', is_correct: false }, { text: 'By pointing to the most excellent in each category, he shows how to recognize the divine in the world — the quality of excellence or radiance in anything is where the divine shines most clearly', is_correct: true }, { text: 'Because the lesser things in each category have nothing to do with God', is_correct: false }], explanation: 'The vibhuti teaching is a training in perception. Krishna isn\'t just listing resume items — he\'s showing Arjuna how to see divinity in the world: wherever you encounter peak excellence, beauty, or power in any domain, that\'s where the divine is most visible.', difficulty: 'application' }],
        },
        {
            part_number: 5,
            verse_start: 27,
            verse_end: 34,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 27, sanskrit: 'उच्चैःश्रवसमश्वानां विद्धि माममृतोद्भवम्। ऐरावतं गजेन्द्राणां नराणां च नराधिपम्।।', transliteration: 'uchchaih-shravasam ashvanam viddhi mam amritod-bhavam', explanations: { en: 'Among horses, Ucchaihshrava born from the ocean of nectar; among lordly elephants, Airavata; among humans, the king.' } },
                { verse_number: 28, sanskrit: 'आयुधानामहं वज्रं धेनूनामस्मि कामधुक्। प्रजनश्चास्मि कन्दर्पः सर्पाणामस्मि वासुकिः।।', transliteration: 'ayudhanam aham vajram dhenunam asmi kamadhuk', explanations: { en: 'Among weapons, the thunderbolt; among cows, the wish-fulfilling Kamadhenu; among procreative forces, Kandarpa (Eros); among serpents, Vasuki.' } },
                { verse_number: 29, sanskrit: 'अनन्तश्चास्मि नागानां वरुणो यादसामहम्। पितॄणामर्यमा चास्मि यमः संयमतामहम्।।', transliteration: 'anantash chasmi naganam varuno yadasam aham', explanations: { en: 'Among the Nagas, Ananta; among water beings, Varuna; among the ancestors, Aryama; among controllers, Yama.' } },
                { verse_number: 30, sanskrit: 'प्रह्लादश्चास्मि दैत्यानां कालः कलयतामहम्। मृगाणां च मृगेन्द्रोऽहं वैनतेयश्च पक्षिणाम्।।', transliteration: 'prahladas chasmi daityanan kalah kalayatam aham', explanations: { en: 'Among the Daityas, Prahlada; among reckoners, Time; among beasts, the lion; among birds, Garuda.' } },
                { verse_number: 31, sanskrit: 'पवनः पवतामस्मि रामः शस्त्रभृतामहम्। झषाणां मकरश्चास्मि स्रोतसामस्मि जाह्नवी।।', transliteration: 'pavanah pavatam asmi ramah shastra-bhritam aham', explanations: { en: 'Among purifiers, the wind; among warriors who bear weapons, Rama; among fish, the crocodile; among rivers, the Ganga.' } },
                { verse_number: 32, sanskrit: 'सर्गाणामादिरन्तश्च मध्यं चैवाहमर्जुन। अध्यात्मविद्या विद्यानां वादः प्रवदतामहम्।।', transliteration: 'sarganam adir antash cha madhyam chaivah am arjuna', explanations: { en: 'Among creations he is the beginning, middle, and end. Among branches of knowledge, knowledge of the self; among debates, the conclusive argument.' } },
                { verse_number: 33, sanskrit: 'अक्षराणामकारोऽस्मि द्वन्द्वः सामासिकस्य च। अहमेवाक्षयः कालो धाताहं विश्वतोमुखः।।', transliteration: 'aksharanam akaro\'smi dvandvah samasikasya cha', explanations: { en: 'Among letters, the letter A; among compound words, the dual compound. He alone is inexhaustible time, the all-faced sustainer.' } },
                { verse_number: 34, sanskrit: 'मृत्युः सर्वहरश्चाहमुद्भवश्च भविष्यताम्। कीर्तिः श्रीर्वाक्च नारीणां स्मृतिर्मेधा धृतिः क्षमा।।', transliteration: 'mrityuh sarva-harash chaham udbhavash cha bhavishyatam', explanations: { en: 'Among all-devouring things, death; among origins of future beings, prosperity. Among feminine qualities: fame, fortune, speech, memory, intelligence, steadfastness, patience.' } },
            ],
            questions: [{ question_text: 'Krishna names himself as "death, the all-devourer" among these manifestations. How should a devotee understand seeing the divine in something as frightening as death?', options: [{ text: 'It is meant to terrify people into submission', is_correct: false }, { text: 'It expands the devotee\'s vision to recognize the divine in all aspects of reality — not just the beautiful and pleasant, but even in endings and dissolution, which are equally expressions of the same ultimate reality', is_correct: true }, { text: 'It means death should be welcomed and sought', is_correct: false }], explanation: 'Including death as a vibhuti is theologically significant — it prevents the devotee from having a partial, only-positive view of the divine. If the divine is truly all-pervading, it must include endings, loss, and dissolution, not only creation and abundance.', difficulty: 'application' }],
        },
        {
            part_number: 6,
            verse_start: 35,
            verse_end: 39,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 35, sanskrit: 'बृहत्साम तथा साम्नां गायत्री छन्दसामहम्। मासानां मार्गशीर्षोऽहमृतूनां कुसुमाकरः।।', transliteration: 'brihat-sama tatha samnam gayatri chhandasam aham', explanations: { en: 'Among the Sama hymns, the Brihat Sama; among meters, the Gayatri; among months, Margashirsha; among seasons, the flower-bearing spring.' } },
                { verse_number: 36, sanskrit: 'द्यूतं छलयतामस्मि तेजस्तेजस्विनामहम्। जयोऽस्मि व्यवसायोऽस्मि सत्त्वं सत्त्ववतामहम्।।', transliteration: 'dyutam chhalayatam asmi tejas tejasvinam aham', explanations: { en: 'Among deceptive games, gambling; among the splendid, splendor; among victories, victory; among the resolute, resolution; among the sattvic, sattva.' } },
                { verse_number: 37, sanskrit: 'वृष्णीनां वासुदेवोऽस्मि पाण्डवानां धनञ्जयः। मुनीनामप्यहं व्यासः कवीनामुशना कविः।।', transliteration: 'vrishninam vasudevo\'smi pandavanam dhananjayah', explanations: { en: 'Among the Vrishnis, Vasudeva; among the Pandavas, Arjuna himself; among sages, Vyasa; among seers, the seer Ushana.' } },
                { verse_number: 38, sanskrit: 'दण्डो दमयतामस्मि नीतिरस्मि जिगीषताम्। मौनं चैवास्मि गुह्यानां ज्ञानं ज्ञानवतामहम्।।', transliteration: 'dando damayatam asmi nitir asmi jigiShatam', explanations: { en: 'Among disciplining forces, punishment; among those seeking victory, statecraft; among secrets, silence; among the knowledgeable, knowledge itself.' } },
                { verse_number: 39, sanskrit: 'यच्चापि सर्वभूतानां बीजं तदहमर्जुन। न तदस्ति विना यत्स्यान्मया भूतं चराचरम्।।', transliteration: 'yach chapi sarva-bhutanam bijam tad aham arjuna', explanations: { en: 'And whatever is the seed of all beings — that is Krishna. There is nothing, moving or unmoving, that exists without him.' } },
            ],
            questions: [{ question_text: 'In verse 37, Krishna names Arjuna himself as one of his manifestations. What effect does this have on Arjuna — and on the reader?', options: [{ text: 'It is just a compliment to flatter Arjuna', is_correct: false }, { text: 'It dissolves the separation between the teacher and student — Arjuna\'s own excellence is itself a manifestation of the divine, which means the seeker and the sought are not as separate as they appeared', is_correct: true }, { text: 'It means Arjuna is also a god', is_correct: false }], explanation: 'This is one of the chapter\'s most intimate moments. By naming Arjuna as a vibhuti, Krishna is saying: you too are an expression of what I am. The seeker carries the divine within them already — which is precisely what makes seeking possible.', difficulty: 'application' }],
        },
        {
            part_number: 7,
            verse_start: 40,
            verse_end: 42,
            estimated_minutes: 3.0,
            verses: [
                { verse_number: 40, sanskrit: 'नान्तोऽस्ति मम दिव्यानां विभूतीनां परन्तप। एष तूद्देशतः प्रोक्तो विभूतेर्विस्तरो मया।।', transliteration: 'nanto\'sti mama divyanam vibhutinam parantapa', explanations: { en: 'There is no end to Krishna\'s divine manifestations. What has been spoken is only an indication of his extent.' } },
                { verse_number: 41, sanskrit: 'यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा। तत्तदेवावगच्छ त्वं मम तेजोंऽशसम्भवम्।।', transliteration: 'yad yad vibhutimat sattvam shrimad urjitam eva va', explanations: { en: 'Whatever being has glory, prosperity, or power — know that to be born of a spark of Krishna\'s splendor.' } },
                { verse_number: 42, sanskrit: 'अथवा बहुनैतेन किं ज्ञातेन तवार्जुन। विष्टभ्याहमिदं कृत्स्नमेकांशेन स्थितो जगत्।।', transliteration: 'athava bahunaitena kim jnatena tavaarjuna', explanations: { en: 'But what need is there for Arjuna to know all this detail? Krishna sustains this entire world with just one fragment of himself.' } },
            ],
            questions: [{ question_text: 'The chapter closes with Krishna saying a single fragment of him sustains the whole universe. What is the point of this final statement after listing so many specific manifestations?', options: [{ text: 'That the list was unnecessary and a waste of time', is_correct: false }, { text: 'It puts the entire vibhuti list in perspective — all those magnificent examples of divine presence were just pointing at a single spark of something that is incomprehensibly vast; the divine is not exhausted by any list or any world', is_correct: true }, { text: 'That the physical universe is unimportant to God', is_correct: false }], explanation: 'The closing verse is deliberately humbling after an extensive list. Every example given — the Himalayas, the Ganga, the sun, Arjuna himself — is just a fragment of a fragment. This expands the listener\'s sense of scale and prevents any single example from being mistaken for the whole.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter10;
