// Complete Chapter 7 (Jnana Vijnana Yoga - "The Yoga of Knowledge and Wisdom"),
// all 30 verses, 5 parts.

const chapter7 = {
    number: 7,
    title: 'The Yoga of Knowledge and Wisdom',
    total_verses: 30,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 6,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 1, sanskrit: 'श्रीभगवानुवाच। मय्यासक्तमनाः पार्थ योगं युञ्जन्मदाश्रयः। असंशयं समग्रं मां यथा ज्ञास्यसि तच्छृणु।।', transliteration: 'shri bhagavan uvacha: mayy asakta-manah partha yogam yunjan mad-ashrayah', explanations: { en: 'Krishna says: with your mind attached to me, taking refuge in me, practicing yoga — hear how you will know me completely, without doubt.', hi: 'कृष्ण कहते हैं — अपना मन मुझमें लगाकर, मेरी शरण लेकर योग का अभ्यास करो; सुनो कि तुम मुझे पूरी तरह और बिना किसी संशय के कैसे जान सकोगे।' } },
                { verse_number: 2, sanskrit: 'ज्ञानं तेऽहं सविज्ञानमिदं वक्ष्याम्यशेषतः। यज्ज्ञात्वा नेह भूयोऽन्यज्ज्ञातव्यमवशिष्यते।।', transliteration: 'jnanam te\'ham sa-vijnanam idam vakshyamy asheshatah', explanations: { en: 'He promises to teach Arjuna knowledge along with realized wisdom, completely, after knowing which nothing further in this world remains to be known.', hi: 'वे अर्जुन को वचन देते हैं कि वे उन्हें ज्ञान और अनुभवजन्य विवेक दोनों पूर्ण रूप से बताएँगे, जिसे जान लेने के बाद इस संसार में जानने योग्य और कुछ शेष नहीं रहता।' } },
                { verse_number: 3, sanskrit: 'मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये। यततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः।।', transliteration: 'manushyanam sahasreshu kashchid yatati siddhaye', explanations: { en: 'Among thousands of humans, perhaps one strives for perfection; and among those who strive and are perfected, perhaps one truly knows Krishna in truth.', hi: 'हजारों मनुष्यों में शायद ही कोई एक सिद्धि के लिए प्रयास करता है, और प्रयास करने वाले सिद्ध पुरुषों में भी शायद ही कोई एक कृष्ण को यथार्थ रूप में जान पाता है।' } },
                { verse_number: 4, sanskrit: 'भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च। अहङ्कार इतीयं मे भिन्ना प्रकृतिरष्टधा।।', transliteration: 'bhumir apo\'nalo vayuh kham mano buddhir eva cha', explanations: { en: 'Earth, water, fire, air, ether, mind, intellect, and ego — these eight form Krishna\'s divided lower nature.', hi: 'पृथ्वी, जल, अग्नि, वायु, आकाश, मन, बुद्धि और अहंकार — ये आठ तत्व कृष्ण की विभाजित निम्न प्रकृति हैं।' } },
                { verse_number: 5, sanskrit: 'अपरेयमितस्त्वन्यां प्रकृतिं विद्धि मे पराम्। जीवभूतां महाबाहो ययेदं धार्यते जगत्।।', transliteration: 'apareyam itas tv anyam prakritim viddhi me param', explanations: { en: 'This lower nature is different from his higher nature — know that higher nature as the life-principle that sustains this world.', hi: 'यह निम्न प्रकृति उनकी उच्च प्रकृति से भिन्न है — उस उच्च प्रकृति को जीवन-तत्व के रूप में जानो, जो इस पूरे संसार को धारण करती है।' } },
                { verse_number: 6, sanskrit: 'एतद्योनीनि भूतानि सर्वाणीत्युपधारय। अहं कृत्स्नस्य जगतः प्रभवः प्रलयस्तथा।।', transliteration: 'etad-yonini bhutani sarvani\'ty upadharaya', explanations: { en: 'Understand that all beings have their origin in these two natures. Krishna is the origin and dissolution of the entire world.', hi: 'समझो कि सभी प्राणी इन्हीं दोनों प्रकृतियों से उत्पन्न होते हैं। कृष्ण ही समस्त संसार की उत्पत्ति और लय के कारण हैं।' } },
            ],
            questions: [{ question_text: 'Why does Krishna say so few people truly know him in truth (verse 3), even among those who seek?', options: [{ text: 'Because the knowledge is deliberately hidden from most people', is_correct: false }, { text: 'Because there is a difference between intellectual understanding and genuine realization — many can learn about Krishna, but the direct knowing of ultimate reality requires a depth of practice and grace that is rare', is_correct: true }, { text: 'Because most people are simply not spiritually qualified', is_correct: false }], explanation: 'This verse is a reality check, not an exclusion. The point isn\'t that the teaching is reserved for a few, but that the gap between knowledge about and direct knowledge of is vast, and requires sustained commitment to cross.', difficulty: 'application', hi: { question_text: 'खोजने वालों में भी कृष्ण यह क्यों कहते हैं कि बहुत कम लोग उन्हें सच में यथार्थ रूप से जानते हैं (श्लोक 3)?', options: [{ text: 'क्योंकि यह ज्ञान जानबूझकर अधिकतर लोगों से छुपाया गया है', is_correct: false }, { text: 'क्योंकि बौद्धिक समझ और सच्चे साक्षात्कार में अंतर है - कई लोग कृष्ण के बारे में सीख सकते हैं, पर परम सत्य का प्रत्यक्ष ज्ञान अभ्यास और अनुग्रह की एक ऐसी गहराई माँगता है जो दुर्लभ है', is_correct: true }, { text: 'क्योंकि अधिकतर लोग बस आध्यात्मिक रूप से योग्य नहीं हैं', is_correct: false }], explanation: 'यह श्लोक एक वास्तविकता-जाँच है, बहिष्करण नहीं। बात यह नहीं है कि यह शिक्षा कुछ ही लोगों के लिए आरक्षित है, बल्कि यह है कि किसी के बारे में जानने और उसे प्रत्यक्ष जानने के बीच का अंतर विशाल है, और उसे पार करने के लिए निरंतर प्रतिबद्धता चाहिए।' } }],
        },
        {
            part_number: 2,
            verse_start: 7,
            verse_end: 12,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 7, sanskrit: 'मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय। मयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव।।', transliteration: 'mattah parataram nanyat kinchid asti dhananjaya', explanations: { en: 'There is nothing higher than Krishna. Everything is strung on him like pearls on a thread.', hi: 'कृष्ण से बढ़कर कुछ भी नहीं है। यह सारा संसार उनमें उसी तरह पिरोया हुआ है जैसे धागे में मोतियाँ।' } },
                { verse_number: 8, sanskrit: 'रसोऽहमप्सु कौन्तेय प्रभास्मि शशिसूर्ययोः। प्रणवः सर्ववेदेषु शब्दः खे पौरुषं नृषु।।', transliteration: 'raso\'ham apsu kaunteya prabhasmi shashi-suryayoh', explanations: { en: 'Krishna is the taste in water, the light in the moon and sun, the sacred syllable Om in the Vedas, the sound in space, and the vitality in humans.', hi: 'कृष्ण जल में रस हैं, चाँद और सूरज में प्रकाश हैं, वेदों में ओंकार हैं, आकाश में ध्वनि हैं, और मनुष्यों में पुरुषार्थ हैं।' } },
                { verse_number: 9, sanskrit: 'पुण्यो गन्धः पृथिव्यां च तेजश्चास्मि विभावसौ। जीवनं सर्वभूतेषु तपश्चास्मि तपस्विषु।।', transliteration: 'punyo gandhah prithivyam cha tejash chasmi vibhavasau', explanations: { en: 'He is the pure fragrance of the earth, the brilliance in fire, the life in all beings, and the austerity in ascetics.', hi: 'वे पृथ्वी की पवित्र सुगंध हैं, अग्नि का तेज हैं, सभी प्राणियों में जीवन हैं, और तपस्वियों की तपस्या हैं।' } },
                { verse_number: 10, sanskrit: 'बीजं मां सर्वभूतानां विद्धि पार्थ सनातनम्। बुद्धिर्बुद्धिमतामस्मि तेजस्तेजस्विनामहम्।।', transliteration: 'bijam mam sarva-bhutanam viddhi partha sanatanam', explanations: { en: 'Know Krishna as the eternal seed of all beings. He is the intelligence of the intelligent and the brilliance of the brilliant.', hi: 'हे पार्थ, कृष्ण को सभी प्राणियों का सनातन बीज समझो। वे बुद्धिमानों की बुद्धि और तेजस्वियों का तेज हैं।' } },
                { verse_number: 11, sanskrit: 'बलं बलवतां चाहं कामरागविवर्जितम्। धर्माविरुद्धो भूतेषु कामोऽस्मि भरतर्षभ।।', transliteration: 'balam balavatam chaham kama-raga-vivarjitam', explanations: { en: 'He is the strength of the strong, free from desire and passion. In beings he is the desire that does not conflict with dharma.', hi: 'वे बलवानों का बल हैं, जो इच्छा और आसक्ति से मुक्त है। और प्राणियों में, धर्म के विरुद्ध न जाने वाली कामना भी वे स्वयं ही हैं।' } },
                { verse_number: 12, sanskrit: 'ये चैव सात्त्विका भावा राजसास्तामसाश्च ये। मत्त एवेति तान्विद्धि न त्वहं तेषु ते मयि।।', transliteration: 'ye chaiva sattvika bhava rajasas tamasash cha ye', explanations: { en: 'Whatever states exist — sattvic, rajasic, or tamasic — know that they all arise from Krishna. But he is not in them; they are in him.', hi: 'सत्त्व, रज और तम — जो भी भाव हैं, जान लो कि वे सब कृष्ण से ही उत्पन्न होते हैं। परंतु वे उनमें नहीं हैं, बल्कि वे सब उन्हीं में हैं।' } },
            ],
            questions: [{ question_text: 'Krishna says he is the taste in water, the light of the sun, the fragrance of the earth. What is the effect of this teaching on how one moves through daily life?', options: [{ text: 'It means one must always be thinking about God consciously while doing everything', is_correct: false }, { text: 'It invites a recognition that the divine is not somewhere else but present in the immediate qualities of ordinary experience — training the perception to find the sacred in what is already here', is_correct: true }, { text: 'It is only a poetic metaphor with no practical meaning', is_correct: false }], explanation: 'This is a profoundly practical teaching about where to look for the divine. Not in some distant realm, but in the very qualities of present experience — the refreshment of water, the warmth of sunlight. This reframes awareness itself as a form of devotion.', difficulty: 'application', hi: { question_text: 'कृष्ण कहते हैं कि वे जल में रस, सूर्य का प्रकाश, पृथ्वी की सुगंध हैं। यह शिक्षा रोज़मर्रा के जीवन को जीने के तरीके पर क्या प्रभाव डालती है?', options: [{ text: 'इसका मतलब है कि हर काम करते समय हमेशा सचेत रूप से ईश्वर के बारे में सोचना चाहिए', is_correct: false }, { text: 'यह इस पहचान की ओर आमंत्रित करता है कि ईश्वर कहीं और नहीं बल्कि सामान्य अनुभव के तात्कालिक गुणों में मौजूद है - यह अनुभूति को यह खोजने के लिए प्रशिक्षित करता है कि पवित्रता पहले से ही यहाँ मौजूद है', is_correct: true }, { text: 'यह केवल एक काव्यात्मक रूपक है जिसका कोई व्यावहारिक अर्थ नहीं', is_correct: false }], explanation: 'यह ईश्वर को कहाँ खोजें, इसके बारे में एक गहन व्यावहारिक शिक्षा है। किसी दूर के लोक में नहीं, बल्कि वर्तमान अनुभव के गुणों में ही - जल की ताज़गी, धूप की गर्माहट। यह जागरूकता को स्वयं भक्ति के एक रूप में बदल देता है।' } }],
        },
        {
            part_number: 3,
            verse_start: 13,
            verse_end: 19,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 13, sanskrit: 'त्रिभिर्गुणमयैर्भावैरेभिः सर्वमिदं जगत्। मोहितं नाभिजानाति मामेभ्यः परमव्ययम्।।', transliteration: 'tribhir guna-mayair bhavair ebhih sarvam idam jagat', explanations: { en: 'Deluded by the three qualities (gunas), this whole world does not know Krishna, who is beyond them and imperishable.', hi: 'इन तीनों गुणों से बने भावों से मोहित होकर, यह पूरा संसार कृष्ण को नहीं पहचान पाता, जो इन गुणों से परे और अविनाशी हैं।' } },
                { verse_number: 14, sanskrit: 'दैवी ह्येषा गुणमयी मम माया दुरत्यया। मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते।।', transliteration: 'daivi hy esha guna-mayi mama maya duratyaya', explanations: { en: 'This divine maya of his, made of the gunas, is hard to cross. But those who take refuge in Krishna alone cross beyond this maya.', hi: 'गुणों से बनी उनकी यह दिव्य माया लांघना अत्यंत कठिन है। परंतु जो केवल कृष्ण की शरण लेते हैं, वे इस माया को पार कर जाते हैं।' } },
                { verse_number: 15, sanskrit: 'न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः। माययापहृतज्ञाना आसुरं भावमाश्रिताः।।', transliteration: 'na mam dushkritino mudhah prapadyante naradhamah', explanations: { en: 'The wicked, the deluded, the lowest among humans — those whose knowledge is carried away by maya and who take to a demoniac nature — do not surrender to Krishna.', hi: 'दुष्ट, मूढ़ और नीच मनुष्य, जिनका ज्ञान माया द्वारा हर लिया गया है और जो आसुरी स्वभाव अपनाते हैं — वे कृष्ण की शरण नहीं लेते।' } },
                { verse_number: 16, sanskrit: 'चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन। आर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ।।', transliteration: 'chatur-vidha bhajante mam janah sukritino\'rjuna', explanations: { en: 'Four kinds of good people worship Krishna: the distressed, the seeker of knowledge, the one seeking wealth, and the wise.', hi: 'हे अर्जुन, चार प्रकार के सज्जन कृष्ण की भक्ति करते हैं — दुखी, ज्ञान का जिज्ञासु, धन चाहने वाला, और ज्ञानी।' } },
                { verse_number: 17, sanskrit: 'तेषां ज्ञानी नित्ययुक्त एकभक्तिर्विशिष्यते। प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः।।', transliteration: 'tesham jnani nitya-yukta eka-bhaktir vishishyate', explanations: { en: 'Of these, the wise person, always absorbed and devoted with single-minded devotion, is the most distinguished. Krishna is exceedingly dear to that person, and they are dear to Krishna.', hi: 'इनमें से नित्य कृष्ण में लीन रहने वाला और एकनिष्ठ भक्ति रखने वाला ज्ञानी सबसे श्रेष्ठ है। ज्ञानी को कृष्ण अत्यंत प्रिय हैं, और वह भी कृष्ण को अत्यंत प्रिय है।' } },
                { verse_number: 18, sanskrit: 'उदाराः सर्व एवैते ज्ञानी त्वात्मैव मे मतम्। आस्थितः स हि युक्तात्मा मामेवानुत्तमां गतिम्।।', transliteration: 'udarah sarva evaite jnani tv atmaiva me matam', explanations: { en: 'All of these are noble, but the wise person is considered my very self — for that person, with a disciplined self, is established in me alone as the supreme destination.', hi: 'ये सभी उदार हैं, परंतु ज्ञानी को कृष्ण अपनी ही आत्मा के समान मानते हैं — क्योंकि संयमित मन वाला वह व्यक्ति कृष्ण में ही, परम गति के रूप में, स्थित रहता है।' } },
                { verse_number: 19, sanskrit: 'बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते। वासुदेवः सर्वमिति स महात्मा सुदुर्लभः।।', transliteration: 'bahunam janmanam ante jnanavaan mam prapadyate', explanations: { en: 'At the end of many births, the person of wisdom surrenders to Krishna — knowing "Vasudeva is all." Such a great soul is very rare.', hi: 'अनेक जन्मों के अंत में ज्ञानी कृष्ण की शरण लेता है, यह जानकर कि "वासुदेव ही सब कुछ है।" ऐसा महात्मा अत्यंत दुर्लभ है।' } },
            ],
            questions: [{ question_text: 'Krishna describes four types of people who come to him — the distressed, the curious, the one seeking benefits, and the wise. Is one type "better" than the others?', options: [{ text: 'Yes, only the wise person\'s devotion is genuine', is_correct: false }, { text: 'All four are noble, but the wise person\'s devotion is the most complete — the others come for what they need, while the wise person comes knowing Krishna is everything, which is why the relationship is the deepest', is_correct: true }, { text: 'The distressed person\'s devotion is most sincere because it comes from genuine suffering', is_correct: false }], explanation: 'Krishna calls all four "noble" — turning to the divine in distress, curiosity, or need is valid. But the wise person\'s devotion is qualitatively different: it\'s not instrumental (seeking something) but a recognition that the divine is reality itself, which makes the relationship complete.', difficulty: 'application', hi: { question_text: 'कृष्ण चार प्रकार के लोगों का वर्णन करते हैं जो उनके पास आते हैं - दुखी, जिज्ञासु, लाभ चाहने वाला, और ज्ञानी। क्या एक प्रकार दूसरों से "बेहतर" है?', options: [{ text: 'हाँ, केवल ज्ञानी की भक्ति ही सच्ची है', is_correct: false }, { text: 'चारों ही उदार हैं, पर ज्ञानी की भक्ति सबसे पूर्ण है - बाकी जो उन्हें चाहिए उसके लिए आते हैं, जबकि ज्ञानी यह जानते हुए आता है कि कृष्ण ही सब कुछ हैं, इसीलिए यह संबंध सबसे गहरा है', is_correct: true }, { text: 'दुखी व्यक्ति की भक्ति सबसे सच्ची है क्योंकि यह वास्तविक पीड़ा से आती है', is_correct: false }], explanation: 'कृष्ण चारों को ही "उदार" कहते हैं - संकट, जिज्ञासा या आवश्यकता में ईश्वर की ओर मुड़ना वैध है। पर ज्ञानी की भक्ति गुणात्मक रूप से अलग है: यह साधनात्मक नहीं (कुछ पाने के लिए) बल्कि यह पहचान है कि ईश्वर ही स्वयं वास्तविकता है, जो इस संबंध को पूर्ण बनाता है।' } }],
        },
        {
            part_number: 4,
            verse_start: 20,
            verse_end: 25,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 20, sanskrit: 'कामैस्तैस्तैर्हृतज्ञानाः प्रपद्यन्तेऽन्यदेवताः। तं तं नियममास्थाय प्रकृत्या नियताः स्वया।।', transliteration: 'kamais tais tair hrita-jnanah prapadyante\'nya-devatah', explanations: { en: 'Those whose knowledge is carried away by various desires resort to other deities, following various religious rules, led by their own nature.', hi: 'जिनका ज्ञान विभिन्न इच्छाओं से हर लिया गया है, वे अपने स्वभाव से प्रेरित होकर विभिन्न नियमों का पालन करते हुए अन्य देवताओं की शरण लेते हैं।' } },
                { verse_number: 21, sanskrit: 'यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति। तस्य तस्याचलां श्रद्धां तामेव विदधाम्यहम्।।', transliteration: 'yo yo yam yam tanum bhaktah shraddhayarchitum ichchhati', explanations: { en: 'Whatever form a devotee wishes to worship with faith — Krishna makes that very faith steady in them.', hi: 'जो भक्त जिस भी रूप को श्रद्धापूर्वक पूजना चाहता है, कृष्ण उसी की श्रद्धा को उसमें स्थिर कर देते हैं।' } },
                { verse_number: 22, sanskrit: 'स तया श्रद्धया युक्तस्तस्याराधनमीहते। लभते च ततः कामान्मयैव विहितान्हि तान्।।', transliteration: 'sa taya shraddhaya yuktas tasyaradhanam ihate', explanations: { en: 'Endowed with that faith, they seek to propitiate that form, and they obtain their desired results from it — results that are granted by Krishna alone.', hi: 'उस श्रद्धा से युक्त होकर वह उस रूप की आराधना करता है, और उससे अपनी इच्छित वस्तुएँ प्राप्त करता है — जो वास्तव में कृष्ण द्वारा ही प्रदान की जाती हैं।' } },
                { verse_number: 23, sanskrit: 'अन्तवत्तु फलं तेषां तद्भवत्यल्पमेधसाम्। देवान्देवयजो यान्ति मद्भक्ता यान्ति मामपि।।', transliteration: 'antavat tu phalam tesham tad bhavaty alpa-medhasam', explanations: { en: 'But the fruit of those lesser intelligences is finite. Those who worship the gods go to the gods; those who worship Krishna come to Krishna.', hi: 'परंतु ऐसे अल्पबुद्धि लोगों को मिलने वाला फल नाशवान होता है। देवताओं की पूजा करने वाले देवताओं को प्राप्त होते हैं; कृष्ण के भक्त कृष्ण को प्राप्त होते हैं।' } },
                { verse_number: 24, sanskrit: 'अव्यक्तं व्यक्तिमापन्नं मन्यन्ते मामबुद्धयः। परं भावमजानन्तो ममाव्ययमनुत्तमम्।।', transliteration: 'avyaktam vyaktim apannam manyante mam abuddhayah', explanations: { en: 'The foolish think Krishna has come from the unmanifest into manifestation — not knowing his supreme, imperishable, highest nature.', hi: 'मूर्ख लोग सोचते हैं कि कृष्ण अव्यक्त से व्यक्त रूप में प्रकट हुए हैं — वे उनके परम, अविनाशी और सर्वोच्च स्वभाव को नहीं जानते।' } },
                { verse_number: 25, sanskrit: 'नाहं प्रकाशः सर्वस्य योगमायासमावृतः। मूढोऽयं नाभिजानाति लोको मामजमव्ययम्।।', transliteration: 'naham prakashahah sarvasya yoga-maya-samavritah', explanations: { en: 'He is not revealed to everyone, being veiled by his yoga-maya. This deluded world does not know him as the unborn and imperishable.', hi: 'वे अपनी योगमाया से आवृत होने के कारण सबके सामने प्रकट नहीं होते। यह मोहित संसार उन्हें अजन्मा और अविनाशी रूप में नहीं पहचान पाता।' } },
            ],
            questions: [{ question_text: 'Krishna says he grants and sustains the faith of all worshipers, even those worshiping other forms. What does this say about different religious paths?', options: [{ text: 'That all religions are identical and it doesn\'t matter what you believe', is_correct: false }, { text: 'That sincere faith in any direction is supported by the divine, though different destinations have different qualities — the path toward the ultimate itself leads to something more lasting than finite boons', is_correct: true }, { text: 'That only Krishna-worship is valid and all other forms are wrong', is_correct: false }], explanation: 'Krishna doesn\'t deny the reality or validity of other forms of worship — he says he sustains those paths too. But he draws a distinction: some paths yield finite results, others lead to something limitless. The difference isn\'t moral; it\'s about the depth of what\'s being sought.', difficulty: 'application', hi: { question_text: 'कृष्ण कहते हैं कि वे सभी उपासकों की श्रद्धा को स्थिर करते हैं, यहाँ तक कि जो अन्य रूपों की पूजा करते हैं उनकी भी। यह अलग-अलग धार्मिक मार्गों के बारे में क्या कहता है?', options: [{ text: 'कि सभी धर्म एक समान हैं और आप क्या मानते हैं इससे कोई फर्क नहीं पड़ता', is_correct: false }, { text: 'कि किसी भी दिशा में सच्ची श्रद्धा को ईश्वर का समर्थन मिलता है, हालांकि अलग-अलग मंज़िलों के गुण अलग हैं - परम की ओर जाने वाला मार्ग स्वयं सीमित वरदानों से अधिक स्थायी किसी चीज़ की ओर ले जाता है', is_correct: true }, { text: 'कि केवल कृष्ण-भक्ति ही वैध है और बाकी सभी रूप गलत हैं', is_correct: false }], explanation: 'कृष्ण अन्य पूजा-रूपों की वास्तविकता या वैधता को नकारते नहीं हैं - वे कहते हैं कि वे उन मार्गों को भी बनाए रखते हैं। पर वे एक भेद बताते हैं: कुछ मार्ग सीमित परिणाम देते हैं, कुछ असीम किसी चीज़ की ओर ले जाते हैं। यह अंतर नैतिक नहीं है; यह इस बारे में है कि क्या खोजा जा रहा है, उसकी गहराई कितनी है।' } }],
        },
        {
            part_number: 5,
            verse_start: 26,
            verse_end: 30,
            estimated_minutes: 4.0,
            verses: [
                { verse_number: 26, sanskrit: 'वेदाहं समतीतानि वर्तमानानि चार्जुन। भविष्याणि च भूतानि मां तु वेद न कश्चन।।', transliteration: 'vedaham samatitani vartamanani charjuna', explanations: { en: 'Krishna knows all beings of the past, present, and future, but no one knows him.', hi: 'कृष्ण भूत, वर्तमान और भविष्य के सभी प्राणियों को जानते हैं, परंतु उन्हें कोई नहीं जानता।' } },
                { verse_number: 27, sanskrit: 'इच्छाद्वेषसमुत्थेन द्वन्द्वमोहेन भारत। सर्वभूतानि संमोहं सर्गे यान्ति परन्तप।।', transliteration: 'ichchha-dvesha-samutthena dvandva-mohena bharata', explanations: { en: 'All beings at birth fall into delusion, confused by the duality arising from desire and aversion.', hi: 'सभी प्राणी जन्म लेते ही इच्छा और द्वेष से उत्पन्न द्वंद्व के मोह में फँसकर भ्रमित हो जाते हैं।' } },
                { verse_number: 28, sanskrit: 'येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम्। ते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः।।', transliteration: 'yesham tv anta-gatam papam jananam punya-karmanam', explanations: { en: 'But those whose wrongdoing has ended, whose actions are righteous — freed from the delusion of duality, they worship Krishna with firm vows.', hi: 'परंतु जिनके पाप समाप्त हो चुके हैं और जिनके कर्म पुण्यमय हैं — वे द्वंद्व के मोह से मुक्त होकर दृढ़ संकल्प के साथ कृष्ण की भक्ति करते हैं।' } },
                { verse_number: 29, sanskrit: 'जरामरणमोक्षाय मामाश्रित्य यतन्ति ये। ते ब्रह्म तद्विदुः कृत्स्नमध्यात्मं कर्म चाखिलम्।।', transliteration: 'jara-marana-mokshaya mam ashritya yatanti ye', explanations: { en: 'Those who strive for liberation from old age and death, taking refuge in Krishna, know Brahman completely, along with all that pertains to the self and to action.', hi: 'जो लोग बुढ़ापे और मृत्यु से मुक्ति के लिए कृष्ण की शरण लेकर प्रयास करते हैं, वे ब्रह्म को, आत्मा से संबंधित सब कुछ को, और समस्त कर्म को पूरी तरह जान लेते हैं।' } },
                { verse_number: 30, sanskrit: 'साधिभूताधिदैवं मां साधियज्ञं च ये विदुः। प्रयाणकालेऽपि च मां ते विदुर्युक्तचेतसः।।', transliteration: 'sadhibhutadhidaivam mam sadhiyajnam cha ye viduh', explanations: { en: 'Those who know Krishna as the overseeing principle of the material and divine realms and of all sacrifice — those with integrated minds know Krishna even at the moment of death.', hi: 'जो लोग कृष्ण को अधिभूत, अधिदैव और अधियज्ञ सहित समग्र रूप में जानते हैं — वे एकाग्र मन वाले लोग मृत्यु के समय भी कृष्ण को जानते हैं।' } },
            ],
            questions: [{ question_text: 'Chapter 7 closes by saying the fully devoted know Krishna even at the moment of death. Why does death appear as the final test of this knowledge?', options: [{ text: 'Because only after death can you truly meet God', is_correct: false }, { text: 'Because the moment of death strips away all the comforts and distractions that ordinarily prop up the mind — whatever is genuinely internalized remains, and whatever was only surface-level does not', is_correct: true }, { text: 'Because the chapter is about a ritual performed at death', is_correct: false }], explanation: 'Death appears as the culminating test throughout the Gita because it\'s the moment of maximum stripping away. Genuine realization persists; intellectual knowledge without genuine internalization dissolves under pressure. This is why the Gita\'s whole teaching matters for how one lives, not just what one believes.', difficulty: 'application', hi: { question_text: 'अध्याय 7 का समापन यह कहते हुए होता है कि पूर्ण रूप से समर्पित व्यक्ति मृत्यु के समय भी कृष्ण को जानता है। मृत्यु इस ज्ञान की अंतिम परीक्षा के रूप में क्यों प्रकट होती है?', options: [{ text: 'क्योंकि केवल मृत्यु के बाद ही आप सच में ईश्वर से मिल सकते हैं', is_correct: false }, { text: 'क्योंकि मृत्यु का क्षण उन सभी सुविधाओं और विकर्षणों को हटा देता है जो सामान्यतः मन को सहारा देते हैं - जो वास्तव में आत्मसात हो चुका है वह बना रहता है, और जो केवल सतही था वह नहीं बचता', is_correct: true }, { text: 'क्योंकि यह अध्याय मृत्यु के समय किए जाने वाले एक कर्मकांड के बारे में है', is_correct: false }], explanation: 'गीता में मृत्यु को अंतिम परीक्षा के रूप में इसलिए प्रस्तुत किया गया है क्योंकि यह अधिकतम उतार का क्षण है। सच्चा साक्षात्कार बना रहता है; सच्चे आत्मसातीकरण के बिना बौद्धिक ज्ञान दबाव में घुल जाता है। इसीलिए गीता की पूरी शिक्षा इस बात के लिए मायने रखती है कि व्यक्ति कैसे जीता है, केवल वह क्या मानता है इसके लिए नहीं।' } }],
        },
    ],
};

module.exports = chapter7;
