// Complete Chapter 8 (Aksara Brahma Yoga - "The Yoga of the Imperishable Brahman"),
// all 28 verses, 5 parts.

const chapter8 = {
    number: 8,
    title: 'The Yoga of the Imperishable',
    total_verses: 28,
    parts: [
        {
            part_number: 1,
            verse_start: 1,
            verse_end: 7,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 1, sanskrit: 'अर्जुन उवाच। किं तद्ब्रह्म किमध्यात्मं किं कर्म पुरुषोत्तम। अधिभूतं च किं प्रोक्तमधिदैवं किमुच्यते।।', transliteration: 'arjuna uvacha: kim tad brahma kim adhyatmam kim karma purushottama', explanations: { en: 'Arjuna asks seven questions at once: What is Brahman? What is the self? What is action? What is the material basis? What is the divine basis? What is sacrifice? And how are you known at the moment of death?', hi: 'अर्जुन एक साथ सात प्रश्न पूछता है: ब्रह्म क्या है? अध्यात्म क्या है? कर्म क्या है? अधिभूत क्या है? अधिदैव क्या है? अधियज्ञ क्या है? और मृत्यु के समय आपको कैसे जाना जा सकता है?' } },
                { verse_number: 2, sanskrit: 'अधियज्ञः कथं कोऽत्र देहेऽस्मिन्मधुसूदन। प्रयाणकाले च कथं ज्ञेयोऽसि नियतात्मभिः।।', transliteration: 'adhi-yajnah katham ko\'tra dehe\'smin madhusudana', explanations: { en: '...and who is the basis of sacrifice in this body, and how are you to be known at the time of death by the self-controlled?', hi: '...और इस शरीर में अधियज्ञ कौन है, तथा संयमी पुरुषों के द्वारा मृत्यु के समय आपको कैसे जाना जा सकता है?' } },
                { verse_number: 3, sanskrit: 'श्रीभगवानुवाच। अक्षरं ब्रह्म परमं स्वभावोऽध्यात्ममुच्यते। भूतभावोद्भवकरो विसर्गः कर्मसंज्ञितः।।', transliteration: 'shri bhagavan uvacha: aksharam brahma paramam svabhavo\'dhyatmam uchyate', explanations: { en: 'Krishna answers: Brahman is the supreme imperishable. The self\'s own nature is called adhyatma. The creative power that causes the existence and development of beings is called karma.', hi: 'कृष्ण उत्तर देते हैं: परम अविनाशी तत्व ब्रह्म है। आत्मा का अपना स्वभाव अध्यात्म कहलाता है। प्राणियों के अस्तित्व और विकास को जन्म देने वाली सृजनात्मक शक्ति कर्म कहलाती है।' } },
                { verse_number: 4, sanskrit: 'अधिभूतं क्षरो भावः पुरुषश्चाधिदैवतम्। अधियज्ञोऽहमेवात्र देहे देहभृतां वर।।', transliteration: 'adhibhutam ksharo bhavah purushash chadhidaivatam', explanations: { en: 'The perishable realm of matter is adhibhuta; the cosmic Person is adhidaivata; and Krishna himself is the adhiyajna (basis of sacrifice) here in this body.', hi: 'नाशवान भौतिक जगत अधिभूत है; ब्रह्मांडीय पुरुष अधिदैव है; और स्वयं कृष्ण ही इस शरीर में अधियज्ञ हैं।' } },
                { verse_number: 5, sanskrit: 'अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्। यः प्रयाति स मद्भावं याति नास्त्यत्र संशयः।।', transliteration: 'anta-kale cha mam eva smaran muktva kalevaram', explanations: { en: 'Whoever remembers Krishna alone at the moment of death, leaving the body — that person attains Krishna\'s state. There is no doubt about this.', hi: 'जो कोई मृत्यु के समय शरीर छोड़ते हुए केवल कृष्ण का स्मरण करता है, वह कृष्ण के स्वरूप को प्राप्त होता है। इसमें कोई संदेह नहीं है।' } },
                { verse_number: 6, sanskrit: 'यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम्। तं तमेवैति कौन्तेय सदा तद्भावभावितः।।', transliteration: 'yam yam vapi smaran bhavam tyajaty ante kalevaram', explanations: { en: 'Whatever state of being one remembers when leaving the body at the end — that state one attains, always shaped by that feeling.', hi: 'अंत समय में शरीर छोड़ते हुए व्यक्ति जिस भी भाव का स्मरण करता है, उसे वही भाव प्राप्त होता है, क्योंकि वह सदा उसी भावना से रचा जाता है।' } },
                { verse_number: 7, sanskrit: 'तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च। मय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयम्।।', transliteration: 'tasmaat sarveshu kaleshu mam anusmara yudhya cha', explanations: { en: 'Therefore, at all times remember Krishna and fight. With mind and intellect offered to him, you will undoubtedly come to Krishna alone.', hi: 'इसलिए हर समय कृष्ण का स्मरण करते हुए युद्ध करो। मन और बुद्धि उन्हें अर्पित करने से तुम निःसंदेह कृष्ण को ही प्राप्त होगे।' } },
            ],
            questions: [{ question_text: 'Verse 6 says whatever state of mind one is in at death is what one attains after. What does this teach about how to live?', options: [{ text: 'That only the last moment of life matters, so you can do whatever you want until then', is_correct: false }, { text: 'That the moment of death reflects the whole orientation of a life — you can\'t suddenly shift at the end what hasn\'t been cultivated throughout, which is why practice matters now, not later', is_correct: true }, { text: 'That only people who die peacefully get a good afterlife', is_correct: false }], explanation: 'This is a teaching about the momentum of habit. The mind at death doesn\'t choose randomly — it naturally settles into what it has been practicing and dwelling on throughout life. This makes the daily quality of attention and practice the most important thing, not some last-minute effort.', difficulty: 'application' }],
        },
        {
            part_number: 2,
            verse_start: 8,
            verse_end: 13,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 8, sanskrit: 'अभ्यासयोगयुक्तेन चेतसा नान्यगामिना। परमं पुरुषं दिव्यं याति पार्थानुचिन्तयन्।।', transliteration: 'abhyasa-yoga-yuktena chetasa nanya-gamina', explanations: { en: 'With the mind made steadfast by the yoga of practice, not wandering to anything else — meditating on the supreme divine Person, Arjuna, one attains that Person.', hi: 'अभ्यास के योग से स्थिर किए गए मन से, जो कहीं और नहीं भटकता — हे अर्जुन, उस परम दिव्य पुरुष का ध्यान करते हुए मनुष्य उन्हें ही प्राप्त होता है।' } },
                { verse_number: 9, sanskrit: 'कविं पुराणमनुशासितारमणोरणीयांसमनुस्मरेद्यः। सर्वस्य धातारमचिन्त्यरूपमादित्यवर्णं तमसः परस्तात्।।', transliteration: 'kavim puranam anushasitaram anor aniyamsam anusmared yah', explanations: { en: 'One who remembers the ancient seer, the ruler, smaller than the smallest, the sustainer of all, with inconceivable form, sun-colored, beyond darkness...', hi: 'जो पुरातन द्रष्टा, शासक, सूक्ष्म से भी सूक्ष्म, सबके पालनकर्ता, अचिंत्य स्वरूप वाले, सूर्य के समान तेजस्वी और अंधकार से परे उस सत्ता का स्मरण करता है...' } },
                { verse_number: 10, sanskrit: 'प्रयाणकाले मनसाचलेन भक्त्या युक्तो योगबलेन चैव। भ्रुवोर्मध्ये प्राणमावेश्य सम्यक्स तं परं पुरुषमुपैति दिव्यम्।।', transliteration: 'prayana-kale manasachalena bhaktya yukto yoga-balena chaiva', explanations: { en: '...at the time of death, with unmoving mind, endowed with devotion and the power of yoga, fixing the life-breath between the eyebrows — that person reaches that supreme divine Person.', hi: '...मृत्यु के समय अचल मन से, भक्ति और योगबल से युक्त होकर, प्राण को भौंहों के बीच स्थिर करते हुए — वह व्यक्ति उस परम दिव्य पुरुष को प्राप्त होता है।' } },
                { verse_number: 11, sanskrit: 'यदक्षरं वेदविदो वदन्ति विशन्ति यद्यतयो वीतरागाः। यदिच्छन्तो ब्रह्मचर्यं चरन्ति तत्ते पदं संग्रहेण प्रवक्ष्ये।।', transliteration: 'yad aksharam veda-vido vadanti vishanti yad yatayo vita-ragah', explanations: { en: 'That imperishable which the Veda-knowers speak of, which the passionless ascetics enter, desiring which they practice brahmacharya — that goal Krishna will briefly explain.', hi: 'वेदों के ज्ञाता जिस अविनाशी तत्व की बात करते हैं, जिसमें आसक्तिरहित तपस्वी प्रवेश करते हैं, और जिसकी चाह में वे ब्रह्मचर्य का पालन करते हैं — उस लक्ष्य को कृष्ण संक्षेप में बताएंगे।' } },
                { verse_number: 12, sanskrit: 'सर्वद्वाराणि संयम्य मनो हृदि निरुध्य च। मूर्ध्न्याधायात्मनः प्राणमास्थितो योगधारणाम्।।', transliteration: 'sarva-dvarani samyamya mano hridi nirudhya cha', explanations: { en: 'Controlling all the gates, confining the mind in the heart, fixing the life-breath in the head, established in yogic concentration...', hi: 'शरीर के सभी द्वारों को संयमित करके, मन को हृदय में स्थिर करके, प्राण को मस्तक में स्थापित करके, योगिक एकाग्रता में स्थित होकर...' } },
                { verse_number: 13, sanskrit: 'ओमित्येकाक्षरं ब्रह्म व्याहरन्मामनुस्मरन्। यः प्रयाति त्यजन्देहं स याति परमां गतिम्।।', transliteration: 'om ity ekaksharam brahma vyaharan mam anusmaran', explanations: { en: '...uttering the single syllable Om — Brahman — and remembering Krishna, one who departs leaving the body reaches the supreme goal.', hi: '...ब्रह्मरूपी एकाक्षर ॐ का उच्चारण करते हुए और कृष्ण का स्मरण करते हुए, जो शरीर त्यागकर प्रस्थान करता है, वह परम गति को प्राप्त होता है।' } },
            ],
            questions: [{ question_text: 'Why is the syllable Om so significant that it appears here as a gateway at the moment of death?', options: [{ text: 'Because Om is a magic sound that grants passage to heaven', is_correct: false }, { text: 'Because Om represents the essence of the Vedas and of Brahman itself — it is both a symbol and a direct sonic expression of what lies beyond ordinary speech, making it the natural resonance for the final transition', is_correct: true }, { text: 'Because it is a specific religious ritual requirement', is_correct: false }], explanation: 'Om\'s significance in this context isn\'t arbitrary ritual — it is understood as the primordial sound underlying all of existence, the most concentrated expression of Brahman. Uttering it while remembering Krishna brings the dissolving consciousness into alignment with what is most real.', difficulty: 'application' }],
        },
        {
            part_number: 3,
            verse_start: 14,
            verse_end: 19,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 14, sanskrit: 'अनन्यचेताः सततं यो मां स्मरति नित्यशः। तस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः।।', transliteration: 'ananya-chetah satatam yo mam smarati nityashah', explanations: { en: 'For the yogi who constantly remembers Krishna with undivided mind, always connected — for that person, Krishna is easily attained.', hi: 'जो योगी अनन्य मन से निरंतर कृष्ण का स्मरण करता है और सदा उनसे जुड़ा रहता है, उसके लिए कृष्ण को पाना सहज हो जाता है।' } },
                { verse_number: 15, sanskrit: 'मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम्। नाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः।।', transliteration: 'mam upetya punar janma duhkhalayam ashashvatam', explanations: { en: 'Having reached Krishna, the great souls do not return to rebirth — the impermanent home of suffering. They have reached the highest perfection.', hi: 'कृष्ण को प्राप्त होकर महात्मा दुख के इस क्षणभंगुर घर, यानी पुनर्जन्म, में नहीं लौटते। वे परम सिद्धि को प्राप्त कर चुके होते हैं।' } },
                { verse_number: 16, sanskrit: 'आब्रह्मभुवनाल्लोकाः पुनरावर्तिनोऽर्जुन। मामुपेत्य तु कौन्तेय पुनर्जन्म न विद्यते।।', transliteration: 'a-brahma-bhuvanal lokah punar avartino\'rjuna', explanations: { en: 'All worlds up to the realm of Brahma are subject to return, Arjuna. But having come to Krishna, there is no rebirth.', hi: 'हे अर्जुन, ब्रह्मलोक तक के सभी लोक पुनरावर्तन के अधीन हैं। परंतु कृष्ण को प्राप्त होने पर पुनर्जन्म नहीं होता।' } },
                { verse_number: 17, sanskrit: 'सहस्रयुगपर्यन्तमहर्यद्ब्रह्मणो विदुः। रात्रिं युगसहस्रान्तां तेऽहोरात्रविदो जनाः।।', transliteration: 'sahasra-yuga-paryantam ahar yad brahmanao viduh', explanations: { en: 'A day of Brahma lasts a thousand cosmic ages, and a night lasts as long — those who know this understand cosmic time.', hi: 'ब्रह्मा का एक दिन एक हजार युगों के बराबर होता है, और रात्रि भी उतनी ही लंबी होती है — जो यह जानते हैं, वे ब्रह्मांडीय समय को समझते हैं।' } },
                { verse_number: 18, sanskrit: 'अव्यक्ताद्व्यक्तयः सर्वाः प्रभवन्त्यहरागमे। रात्र्यागमे प्रलीयन्ते तत्रैवाव्यक्तसंज्ञके।।', transliteration: 'avyaktat vyaktayah sarvah prabhavanty ahar-agame', explanations: { en: 'At the coming of Brahma\'s day, all manifestations emerge from the unmanifest; at the coming of night, they dissolve back into that same unmanifest.', hi: 'ब्रह्मा के दिन के आगमन पर सभी सृष्टियां अव्यक्त से प्रकट होती हैं; रात्रि के आगमन पर वे उसी अव्यक्त में पुनः विलीन हो जाती हैं।' } },
                { verse_number: 19, sanskrit: 'भूतग्रामः स एवायं भूत्वा भूत्वा प्रलीयते। रात्र्यागमेऽवशः पार्थ प्रभवत्यहरागमे।।', transliteration: 'bhuta-gramah sa evayam bhutva bhutva praliyate', explanations: { en: 'This same multitude of beings, arising again and again, dissolves helplessly at nightfall and emerges again at the coming of day.', hi: 'प्राणियों का यही समूह बार-बार उत्पन्न होकर रात्रि होते ही विवश होकर लीन हो जाता है, और दिन आते ही पुनः प्रकट हो जाता है।' } },
            ],
            questions: [{ question_text: 'What is the point of the cosmic time scale in verses 17-19 — Brahma\'s days and nights lasting thousands of ages?', options: [{ text: 'It is an astronomical calculation with no spiritual meaning', is_correct: false }, { text: 'It contextualizes even the highest heavenly realms as still within the cycle of time and impermanence — showing that liberation must mean something beyond even the grandest temporal existence', is_correct: true }, { text: 'It proves that the Gita is scientifically accurate', is_correct: false }], explanation: 'By showing that even Brahma\'s realm is subject to dissolution at the cosmic scale, Krishna establishes that true liberation must transcend the cycle entirely — not just reach a very long-lasting heaven, but attain what is beyond time altogether.', difficulty: 'application' }],
        },
        {
            part_number: 4,
            verse_start: 20,
            verse_end: 22,
            estimated_minutes: 3.0,
            verses: [
                { verse_number: 20, sanskrit: 'परस्तस्मात्तु भावोऽन्योऽव्यक्तोऽव्यक्तात्सनातनः। यः स सर्वेषु भूतेषु नश्यत्सु न विनश्यति।।', transliteration: 'paras tasmat tu bhavo\'nyo\'vyakto\'vyaktat sanatanah', explanations: { en: 'But beyond that unmanifest, there is another unmanifest existence — eternal — which does not perish when all beings perish.', hi: 'परंतु उस अव्यक्त से भी परे एक और सनातन अव्यक्त सत्ता है, जो सभी प्राणियों के नष्ट होने पर भी नष्ट नहीं होती।' } },
                { verse_number: 21, sanskrit: 'अव्यक्तोऽक्षर इत्युक्तस्तमाहुः परमां गतिम्। यं प्राप्य न निवर्तन्ते तद्धाम परमं मम।।', transliteration: 'avyakto\'kshara ity uktas tam ahuh paramam gatim', explanations: { en: 'That unmanifest is called the imperishable — it is called the supreme destination. Those who reach it do not return. That is Krishna\'s supreme abode.', hi: 'उस अव्यक्त को अक्षर कहा जाता है — उसे परम गति कहा जाता है। जो उसे प्राप्त कर लेते हैं, वे वापस नहीं लौटते। वही कृष्ण का परम धाम है।' } },
                { verse_number: 22, sanskrit: 'पुरुषः स परः पार्थ भक्त्या लभ्यस्त्वनन्यया। यस्यान्तःस्थानि भूतानि येन सर्वमिदं ततम्।।', transliteration: 'purushah sa parah partha bhaktya labhyas tv ananyaya', explanations: { en: 'That supreme Person, within whom all beings exist and by whom all this is pervaded, is attainable by exclusive devotion.', hi: 'वह परम पुरुष, जिसके भीतर सभी प्राणी स्थित हैं और जिसके द्वारा यह सब व्याप्त है, अनन्य भक्ति से ही प्राप्त होता है।' } },
            ],
            questions: [{ question_text: 'Krishna says the supreme destination is attained through exclusive devotion. Why devotion specifically, rather than just knowledge or practice?', options: [{ text: 'Because rituals and knowledge are useless', is_correct: false }, { text: 'Because devotion implies a total orientation of the whole being — not just intellectual understanding or disciplined effort, but the heart\'s complete turning toward the ultimate', is_correct: true }, { text: 'Because only devotees are saved and everyone else is lost', is_correct: false }], explanation: 'Devotion (bhakti) in this sense isn\'t sentiment — it\'s the complete reorientation of desire, attention, and love toward the ultimate. Knowledge can remain intellectual; practice can remain mechanical. Devotion, when genuine, involves the whole person.', difficulty: 'application' }],
        },
        {
            part_number: 5,
            verse_start: 23,
            verse_end: 28,
            estimated_minutes: 4.5,
            verses: [
                { verse_number: 23, sanskrit: 'यत्र काले त्वनावृत्तिमावृत्तिं चैव योगिनः। प्रयाता यान्ति तं कालं वक्ष्यामि भरतर्षभ।।', transliteration: 'yatra kale tv anavritim avritim chaiva yoginah', explanations: { en: 'Krishna says he will now explain the times at which yogis depart and either do not return or do return.', hi: 'कृष्ण कहते हैं कि अब वे उन समयों के बारे में बताएंगे जिनमें योगी देह त्यागकर या तो वापस नहीं लौटते या वापस लौट आते हैं।' } },
                { verse_number: 24, sanskrit: 'अग्निर्ज्योतिरहः शुक्लः षण्मासा उत्तरायणम्। तत्र प्रयाता गच्छन्ति ब्रह्म ब्रह्मविदो जनाः।।', transliteration: 'agnir jyotir ahah shuklah shan-masa uttarayanam', explanations: { en: 'Fire, light, day, the bright fortnight, the six months of the northern path — departing then, knowers of Brahman go to Brahman.', hi: 'अग्नि, प्रकाश, दिन, शुक्ल पक्ष, उत्तरायण के छह महीने — इस मार्ग से प्रस्थान करने वाले ब्रह्मज्ञानी ब्रह्म को प्राप्त होते हैं।' } },
                { verse_number: 25, sanskrit: 'धूमो रात्रिस्तथा कृष्णः षण्मासा दक्षिणायनम्। तत्र चान्द्रमसं ज्योतिर्योगी प्राप्य निवर्तते।।', transliteration: 'dhumo ratris tatha krishnah shan-masa dakshinayanam', explanations: { en: 'Smoke, night, the dark fortnight, the six months of the southern path — the yogi departing thus reaches the lunar light and returns.', hi: 'धुआं, रात्रि, कृष्ण पक्ष, दक्षिणायन के छह महीने — इस मार्ग से प्रस्थान करने वाला योगी चंद्रलोक को प्राप्त होकर वापस लौट आता है।' } },
                { verse_number: 26, sanskrit: 'शुक्लकृष्णे गती ह्येते जगतः शाश्वते मते। एकया यात्यनावृत्तिमन्ययावर्तते पुनः।।', transliteration: 'shukla-krishne gati hy ete jagatah shashvate mate', explanations: { en: 'These two paths — bright and dark — are considered eternal for the world. By one, one goes to non-return; by the other, one returns again.', hi: 'ये दोनों मार्ग — शुक्ल और कृष्ण — संसार के लिए सनातन माने जाते हैं। एक से जाकर मनुष्य वापस नहीं लौटता, दूसरे से जाकर वह पुनः लौट आता है।' } },
                { verse_number: 27, sanskrit: 'नैते सृती पार्थ जानन्योगी मुह्यति कश्चन। तस्मात्सर्वेषु कालेषु योगयुक्तो भवार्जुन।।', transliteration: 'naite sritipartha janan yogi muhyati kashchana', explanations: { en: 'Knowing these two paths, Arjuna, no yogi is deluded. Therefore be steadfast in yoga at all times.', hi: 'हे अर्जुन, इन दोनों मार्गों को जानकर कोई भी योगी मोहित नहीं होता। इसलिए सदा योग में स्थिर रहो।' } },
                { verse_number: 28, sanskrit: 'वेदेषु यज्ञेषु तपःसु चैव दानेषु यत्पुण्यफलं प्रदिष्टम्। अत्येति तत्सर्वमिदं विदित्वा योगी परं स्थानमुपैति चाद्यम्।।', transliteration: 'vedeshu yajneshu tapahsu chaiva daneshu yat punya-phalam pradish.tam', explanations: { en: 'The yogi who knows all this transcends all the meritorious fruits declared for the Vedas, sacrifices, austerities, and gifts — and reaches the supreme primal state.', hi: 'यह सब जानने वाला योगी वेदों, यज्ञों, तपों और दानों से मिलने वाले सभी पुण्यफलों से परे चला जाता है — और परम आदि अवस्था को प्राप्त होता है।' } },
            ],
            questions: [{ question_text: 'Chapter 8 ends saying the yogi who understands all this transcends the results of Vedas, sacrifices, and austerities. What does "transcend" mean here?', options: [{ text: 'That these practices are worthless and should be abandoned', is_correct: false }, { text: 'That genuine understanding takes one beyond the limited, finite fruits these practices ordinarily produce — to the source rather than its particular expressions', is_correct: true }, { text: 'That the yogi becomes more powerful than priests or scholars', is_correct: false }], explanation: 'This closing verse describes the culmination of genuine practice — reaching what all the rituals and austerities were pointing toward, rather than collecting their limited rewards. It\'s the difference between the finger pointing at the moon and the moon itself.', difficulty: 'application' }],
        },
    ],
};

module.exports = chapter8;
